Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2018-12, with the labels that each got.

#248 Fix Deployment acceptance tests
  kubernetes/resource_kubernetes_deployment_test.go
Labels: size/XS

#253 Add missing automount_service_account_token doc
  website/docs/r/service_account.html.markdown
Labels: documentation, size/XS

#249 Add allow_privilege_escalation to container security contexts attributes
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/resource_kubernetes_replication_controller_test.go
  kubernetes/schema_container.go
  kubernetes/schema_pod_spec.go
  kubernetes/structures_container.go
  kubernetes/structures_pod.go
  website/docs/r/deployment.html.markdown
  website/docs/r/pod.html.markdown
  website/docs/r/replication_controller.html.markdown
Labels: documentation, size/L

#252 Fix updates of stateful set images
  kubernetes/resource_kubernetes_stateful_set_test.go
  kubernetes/structures_pod.go
  kubernetes/structures_stateful_set.go
Labels: size/M, waiting-response

#243 add kubernetes_secret datasource
  kubernetes/data_source_kubernetes_secret.go
  kubernetes/data_source_kubernetes_secret_test.go
  kubernetes/provider.go
  website/docs/d/secret.html.markdown
Labels: documentation, size/M

#259 GKE test infra writes kubeconfig file
  kubernetes/test-infra/gke/kubeconfig-template.yaml
  kubernetes/test-infra/gke/main.tf
Labels: size/M
