Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2018-11, with the labels that each got.

#211 Wait for deployment rollout status
  kubernetes/resource_kubernetes_deployment.go
  kubernetes/resource_kubernetes_deployment_test.go
Labels: size/S

#213 Add ReclaimPolicy attribute to Storage class
  kubernetes/data_source_kubernetes_storage_class.go
  kubernetes/data_source_kubernetes_storage_class_test.go
  kubernetes/resource_kubernetes_storage_class.go
  kubernetes/resource_kubernetes_storage_class_test.go
  website/docs/d/storage_class.html.markdown
  website/docs/r/storage_class.html.markdown
Labels: size/XS

#222 Fix configuration for ServiceAccount token automount test.
  kubernetes/resource_kubernetes_service_account_test.go
Labels: size/S

#223 Kops on AWS test env - create state S3 bucket via Terraform
  kubernetes/test-infra/kops-on-aws/kops-create.sh
  kubernetes/test-infra/kops-on-aws/kops-delete.sh
  kubernetes/test-infra/kops-on-aws/main.tf
Labels: size/S

#228 Fix deployment acc tests
  kubernetes/provider_test.go
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/test-infra/gke/main.tf
Labels: enhancement, size/XL

#203 New resource: StatefulSets - CRUD & acceptance tests
  kubernetes/provider.go
  kubernetes/provider_test.go
  kubernetes/resource_kubernetes_persistent_volume_claim.go
  kubernetes/resource_kubernetes_stateful_set.go
  kubernetes/resource_kubernetes_stateful_set_test.go
  kubernetes/schema_persistent_volume_claim.go
  kubernetes/schema_pod_template.go
  kubernetes/schema_stateful_set_spec.go
  kubernetes/structure_persistent_volume_claim.go
  kubernetes/structures_stateful_set.go
  kubernetes/validators.go
  website/docs/d/service.html.markdown
  website/docs/d/storage_class.html.markdown
  website/docs/r/cluster_role_binding.html.markdown
  website/docs/r/config_map.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/horizontal_pod_autoscaler.html.markdown
  website/docs/r/limit_range.html.markdown
  website/docs/r/namespace.html.markdown
  website/docs/r/persistent_volume.html.markdown
  website/docs/r/persistent_volume_claim.html.markdown
  website/docs/r/pod.html.markdown
  website/docs/r/replication_controller.html.markdown
  website/docs/r/resource_quota.html.markdown
  website/docs/r/secret.html.markdown
  website/docs/r/service.html.markdown
  website/docs/r/service_account.html.markdown
  website/docs/r/stateful_set.html.markdown
  website/docs/r/storage_class.html.markdown
  website/kubernetes.erb
Labels: size/XXL

#230 Format inline HCL in ACC tests
  kubernetes/resource_kubernetes_cluster_role_binding_test.go
  kubernetes/resource_kubernetes_config_map_test.go
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_test.go
  kubernetes/resource_kubernetes_limit_range_test.go
  kubernetes/resource_kubernetes_namespace_test.go
  kubernetes/resource_kubernetes_persistent_volume_claim_test.go
  kubernetes/resource_kubernetes_persistent_volume_test.go
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/resource_kubernetes_replication_controller_test.go
  kubernetes/resource_kubernetes_resource_quota_test.go
  kubernetes/resource_kubernetes_secret_test.go
  kubernetes/resource_kubernetes_service_account_test.go
  kubernetes/resource_kubernetes_service_test.go
  kubernetes/resource_kubernetes_stateful_set_test.go
  kubernetes/resource_kubernetes_storage_class_test.go
Labels: size/XXL

#232 Bring back 'wait_until_bound' parameter on PVCs
  kubernetes/schema_persistent_volume_claim.go
Labels: size/XS

#234 Expose 'wait_until_bound' only on stand-alone PVCs
  kubernetes/resource_kubernetes_persistent_volume_claim.go
  kubernetes/schema_persistent_volume_claim.go
Labels: size/XS

#231 Convert returned types to pointers
  kubernetes/resource_kubernetes_deployment.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler.go
  kubernetes/resource_kubernetes_limit_range.go
  kubernetes/resource_kubernetes_persistent_volume.go
  kubernetes/resource_kubernetes_persistent_volume_claim.go
  kubernetes/resource_kubernetes_pod.go
  kubernetes/resource_kubernetes_replication_controller.go
  kubernetes/resource_kubernetes_resource_quota.go
  kubernetes/resource_kubernetes_stateful_set.go
  kubernetes/structure_horizontal_pod_autoscaler.go
  kubernetes/structure_persistent_volume_claim.go
  kubernetes/structure_persistent_volume_spec.go
  kubernetes/structures.go
  kubernetes/structures_container.go
  kubernetes/structures_deployment.go
  kubernetes/structures_pod.go
  kubernetes/structures_replication_controller.go
  kubernetes/structures_stateful_set.go
Labels: size/L
