Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2018-03, with the labels that each got.

#116 Fix adding labels/annotations to resources or data to config maps/secrets when those were empty
  kubernetes/patch_operations.go
  kubernetes/patch_operations_test.go
  kubernetes/resource_kubernetes_config_map_test.go
  kubernetes/resource_kubernetes_namespace_test.go
  kubernetes/resource_kubernetes_secret_test.go
Labels: bug

#130 tests: Add AWS EBS tests for PV + separate test for hostPath
  kubernetes/provider_test.go
  kubernetes/resource_kubernetes_persistent_volume_test.go
  kubernetes/test-infra/kops-on-aws/main.tf
Labels: tests

#132 resource/kubernetes_limit_range: Avoid spurious diff when spec is empty
  kubernetes/resource_kubernetes_limit_range_test.go
  kubernetes/structures.go
Labels: bug

#133 resource/kubernetes_persistent_volume: Use correct operation when updating persistent_volume_source (1.8)
  kubernetes/structure_persistent_volume_spec.go
Labels: bug

#138 test-infra: Re-auth for kops@GCE deletion
  kubernetes/test-infra/kops-on-gce/kops-delete.sh
  kubernetes/test-infra/kops-on-gce/main.tf
Labels: tests

#137 test-infra: Add DNS check to kops
  kubernetes/test-infra/kops-on-aws/kops-create.sh
  kubernetes/test-infra/kops-on-gce/kops-create.sh
  kubernetes/test-infra/kops-waiter.sh
Labels: tests

#136 resource/kubernetes_pod: Bump timeout to 5 mins
  kubernetes/resource_kubernetes_pod.go
Labels: bug

#135 resource/*: Treat non-string label values as invalid
  kubernetes/resource_kubernetes_namespace_test.go
  kubernetes/schema_metadata.go
  kubernetes/validators.go
Labels: bug, crash

#148 vendor: github.com/hashicorp/terraform/...@v0.11.4
  vendor/github.com/hashicorp/terraform/helper/resource/id.go
  vendor/github.com/hashicorp/terraform/helper/resource/testing.go
  vendor/github.com/hashicorp/terraform/helper/resource/wait.go
  vendor/github.com/hashicorp/terraform/helper/schema/field_reader.go
  vendor/github.com/hashicorp/terraform/helper/schema/field_reader_config.go
  vendor/github.com/hashicorp/terraform/helper/schema/field_reader_diff.go
  vendor/github.com/hashicorp/terraform/helper/schema/field_reader_map.go
  vendor/github.com/hashicorp/terraform/helper/schema/resource_diff.go
  vendor/github.com/hashicorp/terraform/helper/schema/schema.go
  vendor/github.com/hashicorp/terraform/helper/validation/validation.go
  vendor/github.com/hashicorp/terraform/httpclient/client.go
  vendor/github.com/hashicorp/terraform/httpclient/useragent.go
  vendor/github.com/hashicorp/terraform/plugin/discovery/get.go
  vendor/github.com/hashicorp/terraform/registry/client.go
  vendor/github.com/hashicorp/terraform/registry/errors.go
  vendor/github.com/hashicorp/terraform/svchost/disco/disco.go
  vendor/github.com/hashicorp/terraform/terraform/eval_apply.go
  vendor/github.com/hashicorp/terraform/terraform/eval_validate.go
  vendor/github.com/hashicorp/terraform/terraform/graph_builder_apply.go
  vendor/github.com/hashicorp/terraform/terraform/interpolate.go
  vendor/github.com/hashicorp/terraform/terraform/node_local.go
  vendor/github.com/hashicorp/terraform/terraform/node_output.go
  vendor/github.com/hashicorp/terraform/terraform/node_resource_apply.go
  vendor/github.com/hashicorp/terraform/terraform/node_resource_refresh.go
  vendor/github.com/hashicorp/terraform/terraform/state.go
  vendor/github.com/hashicorp/terraform/terraform/transform_output.go
  vendor/github.com/hashicorp/terraform/terraform/transform_reference.go
  vendor/github.com/hashicorp/terraform/terraform/user_agent.go
  vendor/github.com/hashicorp/terraform/version/version.go
  vendor/vendor.json
Labels: dependencies

#139 resource/kubernetes_persistent_volume: Mark persistent_volume_source as ForceNew on 1.9+
  kubernetes/resource_kubernetes_persistent_volume.go
  kubernetes/resource_kubernetes_persistent_volume_test.go
Labels: bug, tests
