Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2018-02, with the labels that each got.

#105 fix argument name in example
  website/docs/r/storage_class.html.markdown
Labels: documentation

#107 Fix link to secrets design proposal
  website/docs/r/secret.html.markdown
Labels: documentation

#112 Typo: config map => storage class
  kubernetes/resource_kubernetes_storage_class.go
Labels: bug

#103 resource/kubernetes_secret: Prevent binary data corruption
  kubernetes/resource_kubernetes_secret.go
  kubernetes/resource_kubernetes_secret_test.go
  kubernetes/structures.go
  kubernetes/test-fixtures/binary.data
  kubernetes/test-fixtures/binary2.data
Labels: bug

#120 test-infra: Add more targets (kops + minikube)
  kubernetes/test-infra/README.md
  kubernetes/test-infra/gke/README.md
  kubernetes/test-infra/gke/main.tf
  kubernetes/test-infra/kops-on-aws/README.md
  kubernetes/test-infra/kops-on-aws/kops-create.sh
  kubernetes/test-infra/kops-on-aws/kops-delete.sh
  kubernetes/test-infra/kops-on-aws/main.tf
  kubernetes/test-infra/kops-on-gce/README.md
  kubernetes/test-infra/kops-on-gce/kops-create.sh
  kubernetes/test-infra/kops-on-gce/kops-delete.sh
  kubernetes/test-infra/kops-on-gce/main.tf
  kubernetes/test-infra/minikube-on-packet/.gitignore
  kubernetes/test-infra/minikube-on-packet/10-install-virtualbox.sh
  kubernetes/test-infra/minikube-on-packet/20-install-minikube.sh
  kubernetes/test-infra/minikube-on-packet/README.md
  kubernetes/test-infra/minikube-on-packet/main.tf
Labels: tests

#121 test-infra: Expose google_zone from kops @ GCE
  kubernetes/test-infra/gke/main.tf
  kubernetes/test-infra/kops-on-gce/main.tf
Labels: tests

#123 tests: Ignore resource_version in import tests
  kubernetes/resource_kubernetes_config_map_test.go
  kubernetes/resource_kubernetes_limit_range_test.go
  kubernetes/resource_kubernetes_namespace_test.go
  kubernetes/resource_kubernetes_persistent_volume_claim_test.go
  kubernetes/resource_kubernetes_replication_controller_test.go
  kubernetes/resource_kubernetes_resource_quota_test.go
  kubernetes/resource_kubernetes_secret_test.go
  kubernetes/resource_kubernetes_service_test.go
  kubernetes/resource_kubernetes_storage_class_test.go
Labels: tests

#122 tests: Ignore internal k8s annotations+labels
  kubernetes/resource_kubernetes_namespace_test.go
Labels: tests

#124 tests: Fix wrong access_modes for PVC
  kubernetes/resource_kubernetes_persistent_volume_claim_test.go
  kubernetes/resource_kubernetes_persistent_volume_test.go
Labels: tests

#111 resource/kubernetes_persistent_volume: Add support for storage_class_name
  kubernetes/resource_kubernetes_persistent_volume.go
  kubernetes/resource_kubernetes_persistent_volume_claim_test.go
  kubernetes/resource_kubernetes_persistent_volume_test.go
  kubernetes/structure_persistent_volume_spec.go
  website/docs/r/persistent_volume.html.markdown
Labels: bug, enhancement

#126 tests: Skip GCP-dependent test if not on GCP
  kubernetes/resource_kubernetes_persistent_volume_test.go
Labels: tests

#127 resource/kubernetes_service: Update external_ips correctly on K8S 1.8+
  kubernetes/resource_kubernetes_service.go
  kubernetes/structure_service_spec.go
Labels: bug
