Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2018-10, with the labels that each got.

#101 Deployment
  kubernetes/provider.go
  kubernetes/resource_kubernetes_deployment.go
  kubernetes/resource_kubernetes_pod.go
  kubernetes/structures.go
  kubernetes/structures_deployment.go
Labels: kubernetes/1.9, new-resource, size/XL

#82 Add support for envFrom on container definitions
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/schema_container.go
  kubernetes/structures_container.go
  website/docs/r/pod.html.markdown
  website/docs/r/replication_controller.html.markdown
Labels: enhancement, kubernetes/1.6, size/L

#191 Fix Deployment attributes expansion
  kubernetes/resource_kubernetes_deployment.go
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/structures_deployment.go
Labels: size/XXL

#196 Bump Go version to 1.10 on Travis CI.
  .travis.yml
Labels: size/XS

#197 Remove maintainer section with broken link
  README.md
Labels: size/XS

#198 Allow automount service account token on the service account resource
  kubernetes/resource_kubernetes_service_account.go
  kubernetes/resource_kubernetes_service_account_test.go
Labels: size/M
