Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2019-06, with the labels that each got.

#498 Test infra - autodetect K8s version on AKS
  kubernetes/test-infra/aks/main.tf
Labels: size/XS

#501 Adapt all documentation examples to terraform 0.12
  website/docs/guides/getting-started.html.markdown
  website/docs/r/cluster_role.html.markdown
  website/docs/r/cluster_role_binding.html.markdown
  website/docs/r/config_map.html.markdown
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/ingress.html.markdown
  website/docs/r/limit_range.html.markdown
  website/docs/r/namespace.html.markdown
  website/docs/r/network_policy.html.markdown
  website/docs/r/persistent_volume.html.markdown
  website/docs/r/persistent_volume_claim.html.markdown
  website/docs/r/replication_controller.html.markdown
  website/docs/r/resource_quota.html.markdown
  website/docs/r/role.html.markdown
  website/docs/r/role_binding.html.markdown
  website/docs/r/secret.html.markdown
  website/docs/r/service.html.markdown
  website/docs/r/stateful_set.html.markdown
  website/docs/r/storage_class.html.markdown
Labels: documentation, size/XL

#465 Adapt examples syntax to TF 0.12
  _examples/google-gke-cluster/README.md
  _examples/google-gke-cluster/main.tf
  _examples/http-nginx/README.md
  _examples/http-nginx/replication-controller.tf
  _examples/http-nginx/service.tf
  _examples/http-nginx/variables.tf
  _examples/ingress/README.md
  _examples/ingress/main.tf
  _examples/wordpress-mysql-gce-pv/README.md
  _examples/wordpress-mysql-gce-pv/gce-volumes.tf
  _examples/wordpress-mysql-gce-pv/mysql.tf
  _examples/wordpress-mysql-gce-pv/wordpress.tf
Labels: size/L

#502 Fix sometimes deployment is not waited
  kubernetes/resource_kubernetes_deployment.go
Labels: size/XS

#411 Add support for Job and CronJob (closes #86 and #212)
  go.mod
  go.sum
  kubernetes/provider.go
  kubernetes/resource_kubernetes_cron_job.go
  kubernetes/resource_kubernetes_cron_job_test.go
  kubernetes/resource_kubernetes_job.go
  kubernetes/resource_kubernetes_job_test.go
  kubernetes/schema_cron_job_spec.go
  kubernetes/schema_job_spec.go
  kubernetes/structure_cron_job.go
  kubernetes/structure_job.go
  kubernetes/structures_stateful_set.go
  vendor/github.com/robfig/cron/.gitignore
  vendor/github.com/robfig/cron/.travis.yml
  vendor/github.com/robfig/cron/LICENSE
  vendor/github.com/robfig/cron/README.md
  vendor/github.com/robfig/cron/constantdelay.go
  vendor/github.com/robfig/cron/cron.go
  vendor/github.com/robfig/cron/doc.go
  vendor/github.com/robfig/cron/parser.go
  vendor/github.com/robfig/cron/spec.go
  vendor/modules.txt
  website/docs/r/cron_job.html.markdown
  website/docs/r/job.html.markdown
  website/kubernetes.erb
Labels: dependencies, documentation, size/XXL

#520 Bump Go version in Travis to 1.12.x
  .travis.yml
Labels: size/XS

#516 Add Share Process Namespace option
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/schema_pod_spec.go
  kubernetes/structures_pod.go
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/pod.html.markdown
Labels: documentation, size/M

#525 Remove default value of Job template's spec.backoff_limit
  kubernetes/schema_job_spec.go
Labels: size/XS

#261 add missing automount_service_account_token to the pod spec
  kubernetes/resource_kubernetes_deployment.go
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/resource_kubernetes_pod.go
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/resource_kubernetes_replication_controller.go
  kubernetes/schema_container.go
  kubernetes/schema_pod_spec.go
  kubernetes/structures_pod.go
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/pod.html.markdown
Labels: documentation, size/L
