Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2019-01, with the labels that each got.

#266 Add support for volumeBindingMode in storageClass
  kubernetes/resource_kubernetes_storage_class.go
  kubernetes/resource_kubernetes_storage_class_test.go
  website/docs/d/storage_class.html.markdown
Labels: documentation, size/XS

#257 Update changelog for #249 and #252
  CHANGELOG.md
Labels: size/XS

#226 Add kubernetes_role resource
  kubernetes/provider.go
  kubernetes/resource_kubernetes_role.go
  kubernetes/resource_kubernetes_role_test.go
  website/docs/r/role.html.markdown
  website/kubernetes.erb
Labels: size/XL

#267 Add support for local PVs
  kubernetes/resource_kubernetes_persistent_volume_test.go
  kubernetes/schema_volume_source.go
  kubernetes/structure_persistent_volume_spec.go
Labels: size/M

#118 Add network policy resource with support for 1.8+ fields
  CHANGELOG.md
  kubernetes/provider.go
  kubernetes/resource_kubernetes_network_policy.go
  kubernetes/resource_kubernetes_network_policy_test.go
  kubernetes/schema_label_selector.go
  kubernetes/schema_persistent_volume_claim.go
  kubernetes/schema_stateful_set_spec.go
  kubernetes/structure_network_policy.go
  kubernetes/structure_network_policy_test.go
  website/docs/r/network_policy.html.markdown
  website/kubernetes.erb
Labels: documentation, kubernetes/1.8, new-resource, size/XXL

#193 Add pod metadata to replication controller spec template
  CHANGELOG.md
  kubernetes/resource_kubernetes_deployment.go
  kubernetes/resource_kubernetes_pod.go
  kubernetes/resource_kubernetes_replication_controller.go
  kubernetes/resource_kubernetes_replication_controller_deprecated_test.go
  kubernetes/resource_kubernetes_replication_controller_test.go
  kubernetes/schema_pod_spec.go
  kubernetes/schema_pod_template.go
  kubernetes/structures_replication_controller.go
  website/docs/r/replication_controller.html.markdown
Labels: documentation, size/XXL

#271 trivial .travis.yml cleanups
  .travis.yml
Labels: size/XS

#235 Add kubernetes_role_binding resource
  kubernetes/provider.go
  kubernetes/resource_kubernetes_role_binding.go
  kubernetes/resource_kubernetes_role_binding_test.go
  website/docs/r/role_binding.html.markdown
  website/kubernetes.erb
Labels: documentation, size/XL

#277 Dev: fix test infra for GKE
  .gitignore
  kubernetes/test-infra/gke/README.md
Labels: size/XS

#279 typo
  website/docs/r/cluster_role_binding.html.markdown
Labels: documentation, size/XS

#278 Correct automount_service_account_token location
  website/docs/r/service_account.html.markdown
Labels: documentation, size/XS

#229 Add DaemonSet and ClusterRole resources
  kubernetes/provider.go
  kubernetes/resource_kubernetes_cluster_role.go
  kubernetes/resource_kubernetes_cluster_role_test.go
  kubernetes/resource_kubernetes_daemonset.go
  kubernetes/resource_kubernetes_daemonset_test.go
  kubernetes/schema_rbac.go
  kubernetes/structures.go
  kubernetes/structures_daemonset.go
  kubernetes/structures_rbac.go
  website/docs/r/cluster_role.html.markdown
  website/docs/r/daemonset.html.markdown
  website/kubernetes.erb
Labels: documentation, size/XXL

#282 Remove redundant assignments
  kubernetes/resource_kubernetes_daemonset.go
Labels: size/XS

#288 Alter ClusterRole validation to closer match that of Kubernetes
  kubernetes/resource_kubernetes_cluster_role_test.go
  kubernetes/schema_rbac.go
  website/docs/r/cluster_role.html.markdown
Labels: documentation, size/XS

#281 select default_secret for service account if there is more than one
  kubernetes/resource_kubernetes_service_account.go
  website/docs/r/service_account.html.markdown
Labels: documentation, size/S
