Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2019-07, with the labels that each got.

#527 Allow non-negative replicas in 'kubernetes_stateful_set'.
  kubernetes/resource_kubernetes_stateful_set_test.go
  kubernetes/schema_stateful_set_spec.go
  kubernetes/structures_stateful_set.go
  kubernetes/validators.go
  kubernetes/validators_test.go
Labels: size/M

#389 fix: check isUpdatable for ForceNew when considering deployment updates
  kubernetes/schema_container.go
Labels: size/XS

#448 Tolerations
  kubernetes/resource_kubernetes_daemonset_test.go
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/schema_pod_spec.go
  kubernetes/structures_pod.go
  kubernetes/structures_pod_test.go
  kubernetes/validators.go
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/pod.html.markdown
Labels: documentation, size/XL

#539 Add expansion logic for 'working_dir' attribute
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/structures_container.go
Labels: size/S

#544 Update getting started guide to Terraform 0.12 syntax.
  website/docs/guides/getting-started.html.markdown
Labels: documentation, size/XL

#551 Align validation of names of Role and ClusterRole to K8s
  kubernetes/resource_kubernetes_cluster_role.go
  kubernetes/resource_kubernetes_cluster_role_test.go
  kubernetes/resource_kubernetes_role.go
  kubernetes/resource_kubernetes_role_test.go
  kubernetes/schema_rbac.go
  vendor/k8s.io/apimachinery/pkg/api/validation/path/name.go
  vendor/modules.txt
Labels: dependencies, size/M

#560 Add missing PR numbers to 1.8.1 changelog
  CHANGELOG.md
Labels: size/XS

#563 Migrate test infra to TF 0.12
  kubernetes/test-infra/aks/main.tf
  kubernetes/test-infra/aks/outputs.tf
  kubernetes/test-infra/aks/variables.tf
  kubernetes/test-infra/aks/versions.tf
  kubernetes/test-infra/eks/main.tf
  kubernetes/test-infra/eks/node-config/config.tf
  kubernetes/test-infra/eks/node-config/variables.tf
  kubernetes/test-infra/eks/node-config/versions.tf
  kubernetes/test-infra/eks/output.tf
  kubernetes/test-infra/eks/variables.tf
  kubernetes/test-infra/eks/versions.tf
  kubernetes/test-infra/eks/vpc/outputs.tf
  kubernetes/test-infra/eks/vpc/versions.tf
  kubernetes/test-infra/eks/vpc/vpc.tf
  kubernetes/test-infra/gke/main.tf
  kubernetes/test-infra/gke/versions.tf
Labels: size/L
