Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2019-10, with the labels that each got.

#630 Enable HTTP requests/responses tracing in debug mode
  kubernetes/provider.go
Labels: size/XS

#632 Allow 0 for backoff_limit on kubernetes_job
  kubernetes/schema_job_spec.go
Labels: size/XS

#626 Updated Kubernetes links
  kubernetes/data_source_kubernetes_service.go
  kubernetes/resource_kubernetes_api_service.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler.go
  kubernetes/resource_kubernetes_ingress.go
  kubernetes/resource_kubernetes_limit_range.go
  kubernetes/resource_kubernetes_resource_quota.go
  kubernetes/resource_kubernetes_service.go
  kubernetes/schema_metadata.go
  website/docs/d/secret.html.markdown
  website/docs/d/service.html.markdown
  website/docs/d/storage_class.html.markdown
  website/docs/r/api_service.html.markdown
  website/docs/r/cluster_role.html.markdown
  website/docs/r/cluster_role_binding.html.markdown
  website/docs/r/config_map.html.markdown
  website/docs/r/cron_job.html.markdown
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/endpoints.html.markdown
  website/docs/r/horizontal_pod_autoscaler.html.markdown
  website/docs/r/ingress.html.markdown
  website/docs/r/job.html.markdown
  website/docs/r/limit_range.html.markdown
  website/docs/r/namespace.html.markdown
  website/docs/r/network_policy.html.markdown
  website/docs/r/persistent_volume.html.markdown
  website/docs/r/persistent_volume_claim.html.markdown
  website/docs/r/pod.html.markdown
  website/docs/r/priority_class.markdown
  website/docs/r/replication_controller.html.markdown
  website/docs/r/resource_quota.html.markdown
  website/docs/r/role.html.markdown
  website/docs/r/role_binding.html.markdown
  website/docs/r/secret.html.markdown
  website/docs/r/service.html.markdown
  website/docs/r/service_account.html.markdown
  website/docs/r/stateful_set.html.markdown
  website/docs/r/storage_class.html.markdown
Labels: documentation, size/L

#607 Parametrise all timeouts
  kubernetes/resource_kubernetes_cron_job.go
  kubernetes/resource_kubernetes_job.go
  kubernetes/resource_kubernetes_persistent_volume.go
  kubernetes/resource_kubernetes_resource_quota.go
  kubernetes/resource_kubernetes_service.go
  kubernetes/resource_kubernetes_service_account.go
Labels: size/S

#497 Support in-cluster configuration with service accounts
  kubernetes/provider.go
Labels: size/XS

#643 set cascading delete policy to default delete option
  kubernetes/options_helpers.go
  kubernetes/resource_kubernetes_daemonset.go
  kubernetes/resource_kubernetes_deployment.go
  kubernetes/resource_kubernetes_job.go
  kubernetes/resource_kubernetes_replication_controller.go
  kubernetes/resource_kubernetes_storage_class.go
Labels: size/XS

#646 Support priorityClassName in PodSpec.
  kubernetes/schema_pod_spec.go
  kubernetes/structures_pod.go
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/pod.html.markdown
Labels: documentation, size/XS
