Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2019-08, with the labels that each got.

#583 Correct validation of RoleBinding and ClusterRoleBinding
  kubernetes/resource_kubernetes_cluster_role.go
  kubernetes/resource_kubernetes_cluster_role_binding.go
  kubernetes/resource_kubernetes_cluster_role_binding_test.go
  kubernetes/resource_kubernetes_role.go
  kubernetes/resource_kubernetes_role_binding.go
  kubernetes/resource_kubernetes_role_binding_test.go
  kubernetes/schema_rbac.go
Labels: size/S

#566 Fix some long-failing acceptance tests
  kubernetes/resource_kubernetes_persistent_volume_test.go
  kubernetes/resource_kubernetes_service_test.go
Labels: size/S

#570 #401 configurable delete timeout for kubernetes_namespace resource
  kubernetes/resource_kubernetes_namespace.go
  kubernetes/resource_kubernetes_namespace_test.go
  website/docs/r/namespace.html.markdown
Labels: documentation, size/S

#587 allow more values for deployment rolling update config
  kubernetes/resource_kubernetes_deployment.go
  kubernetes/resource_kubernetes_deployment_test.go
Labels: size/XS

#537 Fix provider crash on malformed network policy
  kubernetes/structure_network_policy.go
Labels: size/M

#595 inappropriate reference doc link
  website/docs/r/limit_range.html.markdown
Labels: documentation, size/XS

#553 Add type to volume hostPath (closes #358)
  kubernetes/resource_kubernetes_persistent_volume_test.go
  kubernetes/schema_volume_source.go
  kubernetes/structure_persistent_volume_spec.go
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/persistent_volume.html.markdown
  website/docs/r/pod.html.markdown
Labels: documentation, size/XS
