Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2019-03, with the labels that each got.

#354 Make worker count configurable in GKE test infra
  kubernetes/test-infra/gke/main.tf
Labels: size/XS

#350 Add endpoint resource (#167)
  kubernetes/provider.go
  kubernetes/resource_kubernetes_endpoint.go
  kubernetes/resource_kubernetes_endpoint_test.go
  kubernetes/structure_endpoint.go
  kubernetes/structure_endpoint_test.go
  website/docs/r/endpoint.html.markdown
Labels: documentation, size/XXL

#349 Fix service account secrets parsing
  kubernetes/resource_kubernetes_service_account.go
Labels: size/XS

#369 test-infra: Remove kops and minikube
  kubernetes/test-infra/README.md
  kubernetes/test-infra/kops-on-aws/README.md
  kubernetes/test-infra/kops-on-aws/kops-create.sh
  kubernetes/test-infra/kops-on-aws/kops-delete.sh
  kubernetes/test-infra/kops-on-aws/main.tf
  kubernetes/test-infra/kops-on-gce/README.md
  kubernetes/test-infra/kops-on-gce/kops-create.sh
  kubernetes/test-infra/kops-on-gce/kops-delete.sh
  kubernetes/test-infra/kops-on-gce/main.tf
  kubernetes/test-infra/kops-waiter.sh
  kubernetes/test-infra/minikube-on-packet/.gitignore
  kubernetes/test-infra/minikube-on-packet/10-install-kvm.sh
  kubernetes/test-infra/minikube-on-packet/20-install-minikube.sh
  kubernetes/test-infra/minikube-on-packet/README.md
  kubernetes/test-infra/minikube-on-packet/main.tf
Labels: size/XL

#370 Test infra GKE: auto-detect available cluster versions
  kubernetes/test-infra/gke/main.tf
Labels: size/XS

#378 Amend README to relax restrictions on beta K8s resources
  README.md
Labels: size/XS

#379 Simplify DefaultFunc to just Default
  kubernetes/schema_pod_spec.go
Labels: size/XS

#377 Add support for importing service accounts
  kubernetes/resource_kubernetes_service_account.go
  kubernetes/resource_kubernetes_service_account_test.go
  website/docs/r/service_account.html.markdown
Labels: documentation, size/M

#372 fix update strategy for deployment
  kubernetes/resource_kubernetes_daemonset.go
  kubernetes/resource_kubernetes_daemonset_test.go
  kubernetes/resource_kubernetes_deployment.go
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/structures_daemonset.go
  kubernetes/structures_deployment.go
Labels: size/XL
