Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2019-11, with the labels that each got.

#665 Add support for kubernetes_api_service.spec.service.port
  kubernetes/resource_kubernetes_api_service.go
  kubernetes/resource_kubernetes_api_service_test.go
  kubernetes/structure_api_service_spec.go
  website/docs/r/api_service.html.markdown
Labels: dependencies, documentation, size/XS

#670 Updated host_alias property name to host_aliases
  website/docs/r/deployment.html.markdown
Labels: documentation, size/XS

#275 Do not set default namespace for replication controller and deployment pod templates
  kubernetes/resource_kubernetes_deployment.go
  kubernetes/resource_kubernetes_replication_controller.go
  kubernetes/schema_helpers.go
  kubernetes/schema_metadata.go
  kubernetes/schema_pod_spec.go
Labels: size/S

#552 Add mount_propagation to volume mount
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/schema_container.go
  kubernetes/structures_container.go
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/pod.html.markdown
Labels: documentation, size/XS

#338 Add PodDisruptionBudget (closes #320)
  kubernetes/provider.go
  kubernetes/resource_kubernetes_pod_disruption_budget.go
  kubernetes/resource_kubernetes_pod_disruption_budget_test.go
  kubernetes/structure_network_policy.go
  kubernetes/structure_pod_disruption_budget.go
  kubernetes/structures_container.go
  kubernetes/validators.go
  website/docs/r/pod_disruption_budget.html.markdown
  website/kubernetes.erb
Labels: documentation, size/XL

#682 Fix namespacing on kubernetes_priority_class
  kubernetes/resource_kubernetes_priority_class.go
  kubernetes/resource_kubernetes_priority_class_test.go
Labels: size/S

#699 Update description to match other official providers
  README.md
Labels: size/XS

#700 Fix GKE test infra attributes for Google provider v3.x.x
  kubernetes/test-infra/gke/main.tf
Labels: size/XS
