Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2020-08, with the labels that each got.

#757 Recreate Storage Class on VolumeBindingMode update
  kubernetes/resource_kubernetes_storage_class.go
Labels: size/XS

#687 No need to skip TestProvider_configure unit test if TEST_ACC is set
  kubernetes/provider_test.go
Labels: size/S

#799 Removing restart_policy from example
  website/docs/r/cron_job.html.markdown
Labels: documentation, size/XS

#922 Add resource for CertificateSigningRequest
  _examples/certificate-signing-request/README.md
  _examples/certificate-signing-request/main.tf
  _examples/certificate-signing-request/variables.tf
  kubernetes/provider.go
  kubernetes/resource_kubernetes_certificate_signing_request.go
  kubernetes/resource_kubernetes_certificate_signing_request_test.go
  kubernetes/schema_metadata.go
  kubernetes/structures.go
  kubernetes/structures_certificate_signing_request.go
  kubernetes/validators.go
  website/docs/r/certificate_signing_request.html.markdown
  website/kubernetes.erb
Labels: dependencies, documentation, size/XL

#957 Allow in-place update of PVC's storage request
  kubernetes/resource_kubernetes_persistent_volume_claim.go
  kubernetes/resource_kubernetes_persistent_volume_claim_test.go
  kubernetes/schema_persistent_volume_claim.go
  kubernetes/structure_persistent_volume_claim.go
  kubernetes/structures_stateful_set.go
Labels: size/L

#938 Support Sysctl in pod spec
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/schema_pod_spec.go
  kubernetes/structures_pod.go
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/pod.html.markdown
Labels: documentation, size/L

#937 r/deployment - wait for deployment to delete
  kubernetes/resource_kubernetes_deployment.go
Labels: size/XS

#959 Fix url attribute in admissionregistration client_config.service block
  kubernetes/resource_kubernetes_mutating_webhook_configuration_test.go
  kubernetes/schema_webhook_client_config.go
  kubernetes/structures_admissionregistration.go
Labels: size/S

#912 Add support for `size_limit` for `empty_dir` block
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/schema_pod_spec.go
  kubernetes/structures_pod.go
  website/docs/d/pod.html.markdown
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/pod.html.markdown
Labels: documentation, size/XL

#876 add default_service_account resource
  kubernetes/provider.go
  kubernetes/resource_kubernetes_default_service_account.go
  kubernetes/resource_kubernetes_default_service_account_test.go
  kubernetes/resource_kubernetes_service_account.go
  website/docs/r/default_service_account.html.markdown
Labels: documentation, size/XL

#939 r/persistent_volume - add support for volume mode
  kubernetes/resource_kubernetes_persistent_volume.go
  kubernetes/resource_kubernetes_persistent_volume_test.go
  kubernetes/structure_persistent_volume_spec.go
  website/docs/r/persistent_volume.html.markdown
Labels: documentation, size/M

#972 Fix failing test for data source kubernetes_service
  kubernetes/data_source_kubernetes_service.go
  kubernetes/data_source_kubernetes_service_test.go
Labels: size/XS

#847 fix: add termination_message_policy to container schema (closes #442)
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/schema_container.go
  kubernetes/structures_container.go
  website/docs/r/pod.html.markdown
Labels: documentation, size/M, theme/coverage

#597 Update Cronjob Resource documentation to remove suspend = true from example
  website/docs/r/cron_job.html.markdown
Labels: documentation, size/XS
