Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2020-02, with the labels that each got.

#690 Refactor kubernetes client config initialization and fix in-cluster config
  README.md
  _examples/cross-cluster/README.md
  _examples/cross-cluster/main.tf
  _examples/google-gke-cluster/README.md
  _examples/http-nginx/README.md
  _examples/in-cluster/README.md
  _examples/in-cluster/main.tf
  _examples/ingress/README.md
  _examples/wordpress-mysql-gce-pv/README.md
  kubernetes/provider.go
  website/docs/guides/getting-started.html.markdown
  website/docs/index.html.markdown
Labels: documentation, size/XL

#735 Do not force base64 encoding for the ca_bundle in the API Service resource
  kubernetes/resource_kubernetes_api_service.go
  kubernetes/resource_kubernetes_api_service_test.go
Labels: size/XS

#653 Support for mount_options for StorageClass
  kubernetes/data_source_kubernetes_storage_class.go
  kubernetes/data_source_kubernetes_storage_class_test.go
  kubernetes/resource_kubernetes_storage_class.go
  kubernetes/resource_kubernetes_storage_class_test.go
  website/docs/d/storage_class.html.markdown
  website/docs/r/storage_class.html.markdown
Labels: documentation, size/S

#429 add mount_options argument to kubernetes_persistent_volume
  kubernetes/resource_kubernetes_persistent_volume.go
  kubernetes/resource_kubernetes_persistent_volume_claim_test.go
  kubernetes/resource_kubernetes_persistent_volume_test.go
  kubernetes/structure_persistent_volume_spec.go
  kubernetes/structures.go
  website/docs/r/persistent_volume.html.markdown
Labels: documentation, size/M

#771 Fix static provider config code block
  website/docs/guides/getting-started.html.markdown
Labels: documentation, size/XS

#767 Defer client initialization to improve resilience
  kubernetes/provider.go
  kubernetes/provider_test.go
  kubernetes/resource_kubernetes_api_service.go
  kubernetes/resource_kubernetes_api_service_test.go
  kubernetes/resource_kubernetes_cluster_role.go
  kubernetes/resource_kubernetes_cluster_role_binding.go
  kubernetes/resource_kubernetes_cluster_role_binding_test.go
  kubernetes/resource_kubernetes_cluster_role_test.go
  kubernetes/resource_kubernetes_config_map.go
  kubernetes/resource_kubernetes_config_map_test.go
  kubernetes/resource_kubernetes_cron_job.go
  kubernetes/resource_kubernetes_cron_job_test.go
  kubernetes/resource_kubernetes_daemonset.go
  kubernetes/resource_kubernetes_daemonset_test.go
  kubernetes/resource_kubernetes_deployment.go
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/resource_kubernetes_endpoints.go
  kubernetes/resource_kubernetes_endpoints_test.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_test.go
  kubernetes/resource_kubernetes_ingress.go
  kubernetes/resource_kubernetes_ingress_test.go
  kubernetes/resource_kubernetes_job.go
  kubernetes/resource_kubernetes_job_test.go
  kubernetes/resource_kubernetes_limit_range.go
  kubernetes/resource_kubernetes_limit_range_test.go
  kubernetes/resource_kubernetes_namespace.go
  kubernetes/resource_kubernetes_namespace_test.go
  kubernetes/resource_kubernetes_network_policy.go
  kubernetes/resource_kubernetes_network_policy_test.go
  kubernetes/resource_kubernetes_persistent_volume.go
  kubernetes/resource_kubernetes_persistent_volume_claim.go
  kubernetes/resource_kubernetes_persistent_volume_claim_test.go
  kubernetes/resource_kubernetes_persistent_volume_test.go
  kubernetes/resource_kubernetes_pod.go
  kubernetes/resource_kubernetes_pod_disruption_budget.go
  kubernetes/resource_kubernetes_pod_disruption_budget_test.go
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/resource_kubernetes_priority_class.go
  kubernetes/resource_kubernetes_priority_class_test.go
  kubernetes/resource_kubernetes_replication_controller.go
  kubernetes/resource_kubernetes_replication_controller_test.go
  kubernetes/resource_kubernetes_resource_quota.go
  kubernetes/resource_kubernetes_resource_quota_test.go
  kubernetes/resource_kubernetes_role.go
  kubernetes/resource_kubernetes_role_binding.go
  kubernetes/resource_kubernetes_role_binding_test.go
  kubernetes/resource_kubernetes_role_test.go
  kubernetes/resource_kubernetes_secret.go
  kubernetes/resource_kubernetes_secret_test.go
  kubernetes/resource_kubernetes_service.go
  kubernetes/resource_kubernetes_service_account.go
  kubernetes/resource_kubernetes_service_account_test.go
  kubernetes/resource_kubernetes_service_test.go
  kubernetes/resource_kubernetes_stateful_set.go
  kubernetes/resource_kubernetes_stateful_set_test.go
  kubernetes/resource_kubernetes_storage_class.go
  kubernetes/resource_kubernetes_storage_class_test.go
  website/docs/index.html.markdown
Labels: size/XXL

#778 Fix AKS test stage
  kubernetes/test-infra/aks/main.tf
Labels: size/XS
