Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2020-01, with the labels that each got.

#730 Fix broken link in ResourceQuota documentation
  website/docs/r/resource_quota.html.markdown
Labels: documentation, size/XS

#733 Bump github.com/hashicorp/terraform-plugin-sdk to v1.4.1
  go.mod
  go.sum
Labels: size/XS

#739 Add support for startup_probe
  kubernetes/provider_test.go
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/schema_container.go
  kubernetes/structures_container.go
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/pod.html.markdown
Labels: documentation, size/M

#750 Add `load_config_file = false` to static configurations
  website/docs/guides/getting-started.html.markdown
Labels: documentation, size/XS

#748 Allow 3s age gap between serviceaccount and secret
  kubernetes/resource_kubernetes_service_account.go
Labels: size/XS
