Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2020-10, with the labels that each got.

#949 r/deployment - add support for readiness_gate
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/schema_pod_spec.go
  kubernetes/structures_pod.go
  website/docs/r/deployment.html.markdown
  website/docs/r/pod.html.markdown
Labels: documentation, size/L, waiting-response

#1033 Update changelog for v1.13.3
  CHANGELOG.md
Labels: size/XS

#1035 Expose kubeconfig path out of Typhoon test environment.
  kubernetes/test-infra/typhoon-aws/main.tf
  kubernetes/test-infra/typhoon-aws/module_1_18.tf
  kubernetes/test-infra/typhoon-aws/module_1_19.tf
Labels: size/XS

#1046 Pin down golang.org/x/sys working version to fix builds for macOS
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/mkall.sh
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_darwin.1_12.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_darwin_386.1_11.go
  vendor/golang.org/x/sys/unix/syscall_darwin_386.go
  vendor/golang.org/x/sys/unix/syscall_darwin_amd64.1_11.go
  vendor/golang.org/x/sys/unix/syscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/syscall_darwin_arm.1_11.go
  vendor/golang.org/x/sys/unix/syscall_darwin_arm.go
  vendor/golang.org/x/sys/unix/syscall_darwin_arm64.1_11.go
  vendor/golang.org/x/sys/unix/syscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_386.1_11.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.1_11.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm.1_11.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.1_11.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsysnum_darwin_386.go
  vendor/golang.org/x/sys/unix/zsysnum_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_darwin_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/types_windows_386.go
  vendor/golang.org/x/sys/windows/types_windows_amd64.go
  vendor/golang.org/x/sys/windows/types_windows_arm.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#1042 Update job documentation
  website/docs/r/job.html.markdown
Labels: documentation, size/XS

#1048 Fix typo in error message
  kubernetes/resource_kubernetes_job.go
Labels: size/XS
