Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2020-05, with the labels that each got.

#830 Add wait_for_load_balancer field to kubernetes_ingress
  kubernetes/resource_kubernetes_ingress.go
  kubernetes/resource_kubernetes_ingress_test.go
  website/docs/r/ingress.html.markdown
Labels: documentation, size/M

#834 Add release badge and license badge
  README.md
Labels: size/XS

#845 Add ingress data source and move to swagger docs for ingress
  kubernetes/data_source_kubernetes_ingress.go
  kubernetes/data_source_kubernetes_ingress_test.go
  kubernetes/provider.go
  kubernetes/resource_kubernetes_ingress.go
  website/docs/d/ingress.html.markdown
  website/kubernetes.erb
Labels: documentation, size/XL

#701 New datasources: kubernetes_namespace & kubernetes_all_namespaces
  README.md
  go.mod
  go.sum
  kubernetes/data_source_kubernetes_all_namespaces.go
  kubernetes/data_source_kubernetes_all_namespaces_test.go
  kubernetes/data_source_kubernetes_namespace.go
  kubernetes/data_source_kubernetes_namespace_test.go
  kubernetes/provider.go
  vendor/modules.txt
  website/docs/d/all_namespaces.html.markdown
  website/docs/d/namespace.html.markdown
  website/kubernetes.erb
Labels: dependencies, documentation, size/XL

#840 Add an example for GKE + NFS + PVC
  _examples/google-gke-cluster/README.md
  _examples/google-gke-nfs-filestore/README.md
  _examples/google-gke-nfs-filestore/kubeconfig-template.yaml
  _examples/google-gke-nfs-filestore/main.tf
Labels: size/XL

#852 Update cron_job.html.markdown
  website/docs/r/cron_job.html.markdown
Labels: documentation, size/XS

#832 Add missing space
  website/docs/index.html.markdown
Labels: documentation, size/XS

#858 Remove namespace from metadata attributes
  website/docs/r/mutating_webhook_configuration.html.markdown
  website/docs/r/validating_webhook_configuration.html.markdown
Labels: documentation, size/XS, theme/docs

#831 Update getting-started.html.markdown
  website/docs/guides/getting-started.html.markdown
Labels: documentation, size/XS

#859 Update metadata name attribute to required for kubernetes_service data source
  website/docs/d/service.html.markdown
Labels: documentation, size/XS

#857 Improve readme and associated documentation
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  README.md
  _about/CODE_OF_CONDUCT.md
  _about/CONTRIBUTING.md
  _about/FAQ.md
  _about/ISSUES.md
  _about/PULL_REQUESTS.md
  _about/SUPPORT.md
Labels: size/XL
