Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2020-11, with the labels that each got.

#1055 Fix TC test issue from SDKv2 upgrade
  kubernetes/provider_test.go
  kubernetes/resource_kubernetes_persistent_volume_claim_test.go
  kubernetes/resource_kubernetes_persistent_volume_test.go
  kubernetes/resource_kubernetes_service_test.go
  kubernetes/resource_kubernetes_stateful_set_test.go
  kubernetes/resource_kubernetes_storage_class_test.go
  website/docs/r/certificate_signing_request.html.markdown
Labels: documentation, size/M

#1053 Normalize wait defaults across Deployment, DaemonSet, StatefulSet, Service, Ingress, and Job
  kubernetes/resource_kubernetes_daemonset.go
  kubernetes/resource_kubernetes_daemonset_test.go
  kubernetes/resource_kubernetes_deployment.go
  kubernetes/resource_kubernetes_ingress.go
  kubernetes/resource_kubernetes_job.go
  kubernetes/resource_kubernetes_job_test.go
  kubernetes/resource_kubernetes_service.go
  kubernetes/resource_kubernetes_service_test.go
  kubernetes/resource_kubernetes_stateful_set.go
  kubernetes/schema_job_spec.go
  kubernetes/structure_job.go
  website/docs/r/daemonset.html.markdown
  website/docs/r/ingress.html.markdown
  website/docs/r/job.html.markdown
  website/docs/r/service.html.markdown
  website/docs/r/stateful_set.html.markdown
Labels: documentation, size/M

#1054 Normalize automount_service_account_token to be in line with the K8s API
  kubernetes/data_source_kubernetes_service_account.go
  kubernetes/data_source_kubernetes_service_account_test.go
  kubernetes/resource_kubernetes_pod.go
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/resource_kubernetes_service_account.go
  kubernetes/resource_kubernetes_service_account_test.go
  kubernetes/schema_pod_spec.go
  website/docs/d/pod.html.markdown
  website/docs/guides/getting-started.html.markdown
  website/docs/r/daemonset.html.markdown
  website/docs/r/default_service_account.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/pod.html.markdown
  website/docs/r/service_account.html.markdown
Labels: documentation, size/M

#1064 Add upgrade test for daemonset
  kubernetes/resource_kubernetes_daemonset_test.go
Labels: size/M

#1070 Fix service load balancer crash
  kubernetes/resource_kubernetes_service.go
Labels: size/XS

#1065 Change resources requests and limits to TypeMap
  _examples/google-gke-nfs-filestore/main.tf
  _examples/http-nginx/replication-controller.tf
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/resource_kubernetes_replication_controller_deprecated_test.go
  kubernetes/resource_kubernetes_replication_controller_test.go
  kubernetes/schema_container.go
  kubernetes/structures_container.go
  website/docs/guides/getting-started.html.markdown
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/pod.html.markdown
  website/docs/r/replication_controller.html.markdown
  website/docs/r/stateful_set.html.markdown
Labels: documentation, size/L

#1063 Add divisor to resource_field_ref
  kubernetes/resource_kubernetes_deployment.go
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/schema_container.go
  kubernetes/schema_pod_spec.go
  kubernetes/structures_container.go
Labels: size/L

#1071 Restructure service and ingress to match K8s API
  kubernetes/data_source_kubernetes_ingress.go
  kubernetes/data_source_kubernetes_service.go
  kubernetes/resource_kubernetes_ingress.go
  kubernetes/resource_kubernetes_ingress_test.go
  kubernetes/resource_kubernetes_service.go
  kubernetes/resource_kubernetes_service_test.go
  kubernetes/structure_service_spec.go
Labels: size/M

#1067 fix assertion in TestAccKubernetesPersistentVolume_hostPath_nodeAffinity
  kubernetes/resource_kubernetes_persistent_volume_test.go
Labels: size/XS

#1062 Docs Overview k8 [Grammatical changes]
  website/docs/index.html.markdown
Labels: documentation, size/XS

#1047 Add timeout argument to kubernetes_stateful_set
  kubernetes/resource_kubernetes_stateful_set.go
  kubernetes/resource_kubernetes_stateful_set_test.go
  website/docs/r/stateful_set.html.markdown
Labels: documentation, size/XS

#1057 add ingressClassName as field in Ingress manifest
  kubernetes/resource_kubernetes_ingress.go
  kubernetes/resource_kubernetes_ingress_test.go
  kubernetes/structure_ingress_spec.go
Labels: size/XS
