Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2020-03, with the labels that each got.

#745 Add ttlSecondsAfterFinished to kubernetes_job and kubernetes_cron_job
  kubernetes/provider_test.go
  kubernetes/resource_kubernetes_job_test.go
  kubernetes/schema_job_spec.go
  kubernetes/structure_job.go
  website/docs/r/cron_job.html.markdown
  website/docs/r/job.html.markdown
Labels: documentation, size/M

#796 Fix modules for Go version 1.13
  go.mod
  go.sum
  vendor/modules.txt
Labels: dependencies, size/M

#802 Add Github Actions for issues+PRs
  .github/workflows/issues.yml
  .github/workflows/labeled_issues.yml
Labels: size/S

#801 Add data source for reading config maps
  kubernetes/data_source_kubernetes_config_map.go
  kubernetes/data_source_kubernetes_config_map_test.go
  kubernetes/provider.go
  website/docs/d/config_map.html.markdown
  website/kubernetes.erb
Labels: documentation, size/L
