Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2020-04, with the labels that each got.

#807 Add configuration for Typhoon based acceptance test environment
  kubernetes/test-infra/typhoon-aws/README.md
  kubernetes/test-infra/typhoon-aws/main.tf
  kubernetes/test-infra/typhoon-aws/variables.tf
Labels: size/M

#809 Update issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull_request_template.md
Labels: size/L

#731 Add kubernetes_service_account data source
  kubernetes/data_source_kubernetes_service_account.go
  kubernetes/data_source_kubernetes_service_account_test.go
  kubernetes/provider.go
  website/docs/d/service_account.html.markdown
  website/docs/r/service_account.html.markdown
  website/kubernetes.erb
Labels: documentation, size/L

#815 Update changelog
  CHANGELOG.md
Labels: size/XS

#822 Add issue pruning features
  .github/workflows/prune_stale_issues.yml
  .hashibot.hcl
Labels: size/XS

#806 Add support for ValidatingWebhookConfiguration
  go.mod
  go.sum
  kubernetes/provider.go
  kubernetes/resource_kubernetes_validating_webhook_configuration.go
  kubernetes/resource_kubernetes_validating_webhook_configuration_test.go
  kubernetes/schema_rule_with_operations.go
  kubernetes/schema_webhook_client_config.go
  kubernetes/structure_validating_webhook_configuration.go
  vendor/github.com/jinzhu/copier/Guardfile
  vendor/github.com/jinzhu/copier/License
  vendor/github.com/jinzhu/copier/README.md
  vendor/github.com/jinzhu/copier/copier.go
  vendor/github.com/jinzhu/copier/wercker.yml
  vendor/k8s.io/api/admissionregistration/v1/doc.go
  vendor/k8s.io/api/admissionregistration/v1/generated.pb.go
  vendor/k8s.io/api/admissionregistration/v1/generated.proto
  vendor/k8s.io/api/admissionregistration/v1/register.go
  vendor/k8s.io/api/admissionregistration/v1/types.go
  vendor/k8s.io/api/admissionregistration/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/admissionregistration/v1/zz_generated.deepcopy.go
  vendor/k8s.io/api/discovery/v1alpha1/doc.go
  vendor/k8s.io/api/discovery/v1alpha1/generated.pb.go
  vendor/k8s.io/api/discovery/v1alpha1/generated.proto
  vendor/k8s.io/api/discovery/v1alpha1/register.go
  vendor/k8s.io/api/discovery/v1alpha1/types.go
  vendor/k8s.io/api/discovery/v1alpha1/types_swagger_doc_generated.go
  vendor/k8s.io/api/discovery/v1alpha1/well_known_labels.go
  vendor/k8s.io/api/discovery/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/client-go/discovery/doc.go
  vendor/k8s.io/client-go/kubernetes/clientset.go
  vendor/k8s.io/client-go/kubernetes/scheme/register.go
  vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1/admissionregistration_client.go
  vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1/doc.go
  vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1/generated_expansion.go
  vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1/mutatingwebhookconfiguration.go
  vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1/validatingwebhookconfiguration.go
  vendor/k8s.io/client-go/kubernetes/typed/core/v1/pod.go
  vendor/k8s.io/client-go/kubernetes/typed/discovery/v1alpha1/discovery_client.go
  vendor/k8s.io/client-go/kubernetes/typed/discovery/v1alpha1/doc.go
  vendor/k8s.io/client-go/kubernetes/typed/discovery/v1alpha1/endpointslice.go
  vendor/k8s.io/client-go/kubernetes/typed/discovery/v1alpha1/generated_expansion.go
  vendor/k8s.io/client-go/rest/config.go
  vendor/k8s.io/client-go/rest/plugin.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/rest/transport.go
  vendor/k8s.io/client-go/rest/zz_generated.deepcopy.go
  vendor/k8s.io/client-go/tools/clientcmd/loader.go
  vendor/k8s.io/client-go/tools/clientcmd/validation.go
  vendor/k8s.io/client-go/tools/reference/ref.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/k8s.io/client-go/transport/config.go
  vendor/k8s.io/client-go/transport/round_trippers.go
  vendor/k8s.io/client-go/transport/token_source.go
  vendor/k8s.io/client-go/transport/transport.go
  vendor/k8s.io/client-go/util/flowcontrol/backoff.go
  vendor/k8s.io/client-go/util/flowcontrol/throttle.go
  vendor/k8s.io/client-go/util/homedir/homedir.go
  vendor/k8s.io/client-go/util/jsonpath/parser.go
  vendor/modules.txt
  website/docs/r/validating_webhook_configuration.html.markdown
Labels: dependencies, size/XXL
