Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2020-12, with the labels that each got.

#1079 Change replicas to TypeString for statefulset and deployment
  kubernetes/resource_kubernetes_deployment.go
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/resource_kubernetes_stateful_set.go
  kubernetes/resource_kubernetes_stateful_set_test.go
  kubernetes/schema_job_spec.go
  kubernetes/schema_stateful_set_spec.go
  kubernetes/structures_deployment.go
  kubernetes/structures_stateful_set.go
  website/docs/r/deployment.html.markdown
  website/docs/r/stateful_set.html.markdown
Labels: documentation, size/L

#1081 Added missing csi attribute in persistent_volume docs
  website/docs/r/persistent_volume.html.markdown
Labels: documentation, size/XS

#1084 Create question.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/question.md
Labels: size/S

#1093 Change fs_group, run_as_user, run_as_group to strings
  kubernetes/schema_container.go
  kubernetes/schema_pod_spec.go
  kubernetes/structures_container.go
  kubernetes/structures_pod.go
Labels: size/M

#1082 Add StateUpgraders for resources field change
  kubernetes/resource_kubernetes_cron_job.go
  kubernetes/resource_kubernetes_cron_job_migrate.go
  kubernetes/resource_kubernetes_daemonset.go
  kubernetes/resource_kubernetes_daemonset_migrate.go
  kubernetes/resource_kubernetes_deployment.go
  kubernetes/resource_kubernetes_deployment_migrate.go
  kubernetes/resource_kubernetes_job.go
  kubernetes/resource_kubernetes_job_migrate.go
  kubernetes/resource_kubernetes_pod.go
  kubernetes/resource_kubernetes_pod_migrate.go
  kubernetes/resource_kubernetes_stateful_set.go
  kubernetes/resource_kubernetes_stateful_set_migrate.go
  kubernetes/schema_container.go
  kubernetes/schema_resources_migrate.go
  kubernetes/schema_resources_migrate_test.go
Labels: size/XXL

#1096 Remove default token volume and volume_mount from Pod state
  kubernetes/structures_container.go
  kubernetes/structures_pod.go
Labels: size/S

#1052 Credentials changes for v2.0.0
  kubernetes/provider.go
  kubernetes/provider_test.go
  kubernetes/resource_kubernetes_job.go
  kubernetes/test-fixtures/kube-config-secondary.yaml
  website/docs/index.html.markdown
Labels: documentation, size/XL

#1074 Fix ForceNew and non-empty plans caused by PodSpec defaults
  GNUmakefile
  README.md
  kubernetes/data_source_kubernetes_pod.go
  kubernetes/provider_test.go
  kubernetes/resource_kubernetes_affinity_test.go
  kubernetes/resource_kubernetes_cron_job_test.go
  kubernetes/resource_kubernetes_daemonset_test.go
  kubernetes/resource_kubernetes_deployment.go
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/resource_kubernetes_job.go
  kubernetes/resource_kubernetes_job_test.go
  kubernetes/resource_kubernetes_persistent_volume_claim_test.go
  kubernetes/resource_kubernetes_pod.go
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/resource_kubernetes_replication_controller.go
  kubernetes/resource_kubernetes_replication_controller_deprecated_test.go
  kubernetes/resource_kubernetes_replication_controller_test.go
  kubernetes/resource_kubernetes_service_account.go
  kubernetes/resource_kubernetes_service_test.go
  kubernetes/resource_kubernetes_stateful_set.go
  kubernetes/resource_kubernetes_stateful_set_test.go
  kubernetes/resource_kubernetes_storage_class_test.go
  kubernetes/schema_container.go
  kubernetes/schema_job_spec.go
  kubernetes/schema_pod_spec.go
  kubernetes/schema_pod_template.go
  kubernetes/schema_stateful_set_spec.go
  kubernetes/structure_job.go
  kubernetes/structures_container.go
  kubernetes/structures_pod.go
  kubernetes/structures_replication_controller.go
  kubernetes/structures_stateful_set.go
Labels: size/XXL

#1098 StateUpgraders for LoadBalancerIngress
  kubernetes/data_source_kubernetes_ingress.go
  kubernetes/data_source_kubernetes_ingress_migrate.go
  kubernetes/data_source_kubernetes_service.go
  kubernetes/data_source_kubernetes_service_migrate.go
  kubernetes/resource_kubernetes_ingress.go
  kubernetes/resource_kubernetes_ingress_migrate.go
  kubernetes/resource_kubernetes_ingress_test.go
  kubernetes/resource_kubernetes_service.go
  kubernetes/resource_kubernetes_service_migrate.go
  kubernetes/resource_kubernetes_service_test.go
  kubernetes/schema_resources_migrate.go
  kubernetes/test-infra/eks/main.tf
  kubernetes/test-infra/eks/node-config/aws_controller_deps.yaml
  kubernetes/test-infra/eks/node-config/cert-manager-crds.yaml
  kubernetes/test-infra/eks/node-config/cert-manager-crs.yaml
  kubernetes/test-infra/eks/node-config/config.tf
  kubernetes/test-infra/eks/node-config/iam_policy.json
  kubernetes/test-infra/eks/node-config/variables.tf
  kubernetes/test-infra/eks/output.tf
  kubernetes/test-infra/eks/variables.tf
  kubernetes/test-infra/eks/vpc/vpc.tf
Labels: size/XXL

#1077 v2.0.0
  CHANGELOG.md
  website/docs/guides/v2-upgrade-guide.markdown
  website/kubernetes.erb
Labels: documentation, size/L
