Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2020-06, with the labels that each got.

#572 Fix broken links in kubernetes_cron_job documentation
  website/docs/r/cron_job.html.markdown
Labels: documentation, size/XS

#698 Adding more detail to the container port documentation
  website/docs/r/pod.html.markdown
Labels: documentation, size/XS

#862 Add community note
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull_request_template.md
Labels: size/XS

#669 Clarify Network Policy documentation
  website/docs/r/network_policy.html.markdown
Labels: documentation, size/XS

#867 Update FAQ.md
  _about/FAQ.md
Labels: size/XS

#875 Delete issues.yml to prevent auto-addition to project
  .github/workflows/issues.yml
Labels: size/XS

#869 Docs: Change host_alias to host_aliases
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/pod.html.markdown
Labels: documentation, size/XS

#824 Support optional on env valueFrom for secret key/configmap key
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/schema_container.go
  kubernetes/structures_container.go
  kubernetes/structures_container_test.go
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/pod.html.markdown
Labels: documentation, size/L

#851 add configuration for LKE based acceptance test environment
  kubernetes/test-infra/lke/README.md
  kubernetes/test-infra/lke/main.tf
Labels: size/M

#883 Add volume_binding_mode resource docs
  website/docs/r/storage_class.html.markdown
Labels: documentation, size/XS

#780 fix(provider): do not swallow client config errors
  kubernetes/provider.go
Labels: size/XS

#751 a more common provider example usage
  website/docs/index.html.markdown
Labels: documentation, size/XS

#823 Support optional flag for ConfigMap mounted as volume (closes #655)
  kubernetes/schema_pod_spec.go
  kubernetes/structures_pod.go
  kubernetes/structures_pod_test.go
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/pod.html.markdown
Labels: documentation, size/XL

#625 Add Kubernetes Job - `wait_for_completion` functionality
  _examples/job/README.md
  _examples/job/main.tf
  kubernetes/resource_kubernetes_job.go
  kubernetes/resource_kubernetes_job_test.go
  vendor/gopkg.in/yaml.v2/go.sum
  website/docs/r/job.html.markdown
Labels: acknowledged, dependencies, documentation, size/L

#893 Possible typo, missing underscore
  website/docs/d/config_map.html.markdown
Labels: documentation, size/XS

#861 Pod security policies
  go.sum
  kubernetes/provider.go
  kubernetes/resource_kubernetes_pod_security_policy.go
  kubernetes/resource_kubernetes_pod_security_policy_test.go
  kubernetes/structure_pod_security_policy_spec.go
  vendor/modules.txt
  website/docs/r/pod_security_policy.html.markdown
  website/kubernetes.erb
Labels: acknowledged, dependencies, documentation, size/XXL

#825 Add CSIDriver resource
  kubernetes/provider.go
  kubernetes/resource_kubernetes_csi_driver.go
  kubernetes/resource_kubernetes_csi_driver_test.go
  kubernetes/structure_csi_driver.go
  website/docs/r/csi_driver.html.markdown
  website/kubernetes.erb
Labels: acknowledged, documentation, size/XL
