Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2021-05, with the labels that each got.

#1243 r/service - allow updating ClusterIP to ExternalName + NodePort to ClusterIP
  kubernetes/resource_kubernetes_service_test.go
  kubernetes/structure_service_spec.go
Labels: acknowledged, size/XL

#1041 fix broken links
  GNUmakefile
  website/docs/d/ingress.html.markdown
  website/docs/d/pod.html.markdown
  website/docs/d/service.html.markdown
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/ingress.html.markdown
  website/docs/r/job.html.markdown
  website/docs/r/persistent_volume.html.markdown
  website/docs/r/pod.html.markdown
  website/docs/r/replication_controller.html.markdown
  website/docs/r/service.html.markdown
  website/docs/r/stateful_set.html.markdown
Labels: documentation, size/L, waiting-response

#1259 Enable links check and fix 2 links
  GNUmakefile
  website/docs/r/deployment.html.markdown
  website/docs/r/pod.html.markdown
Labels: documentation, size/XS

#1261 Update experimental CI for EKS
  kubernetes/test-infra/eks-experimental/README.md
  kubernetes/test-infra/eks-experimental/eks-cluster/cluster.tf
  kubernetes/test-infra/eks-experimental/eks-cluster/iam.tf
  kubernetes/test-infra/eks-experimental/eks-cluster/variables.tf
  kubernetes/test-infra/eks-experimental/eks-cluster/version.tf
  kubernetes/test-infra/eks-experimental/eks-cluster/vpc.tf
  kubernetes/test-infra/eks-experimental/kubernetes-config/kubeconfig.tpl
  kubernetes/test-infra/eks-experimental/kubernetes-config/main.tf
  kubernetes/test-infra/eks-experimental/kubernetes-config/output.tf
  kubernetes/test-infra/eks-experimental/kubernetes-config/variables.tf
  kubernetes/test-infra/eks-experimental/kubernetes-config/version.tf
  kubernetes/test-infra/eks-experimental/main.tf
  kubernetes/test-infra/eks-experimental/output.tf
  kubernetes/test-infra/eks-experimental/variables.tf
  kubernetes/test-infra/eks-experimental/vpc/outputs.tf
Labels: size/XL

#1262 Update getting-started.html.markdown
  website/docs/guides/getting-started.html.markdown
Labels: documentation, size/XS

#1244 r/resource_quota - support `scope_selector`
  kubernetes/resource_kubernetes_resource_quota.go
  kubernetes/resource_kubernetes_resource_quota_test.go
  kubernetes/structures.go
  website/docs/r/resource_quota.html.markdown
Labels: acknowledged, documentation, size/XL

#1251 Add diff suppression for hard limits on kubernetes_resource_quota
  kubernetes/resource_kubernetes_resource_quota.go
  kubernetes/resource_kubernetes_resource_quota_test.go
Labels: size/XS

#1246 r/deployment - remove computed from volume_mount
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/schema_container.go
Labels: acknowledged, size/M

#1260 Update EKS example to use two applies
  _examples/eks/README.md
  _examples/eks/eks-cluster/cluster.tf
  _examples/eks/eks-cluster/iam.tf
  _examples/eks/eks-cluster/variables.tf
  _examples/eks/eks-cluster/version.tf
  _examples/eks/eks-cluster/vpc.tf
  _examples/eks/kubernetes-config/kubeconfig.tpl
  _examples/eks/kubernetes-config/main.tf
  _examples/eks/kubernetes-config/output.tf
  _examples/eks/kubernetes-config/version.tf
  _examples/eks/main.tf
  _examples/eks/output.tf
  _examples/eks/variables.tf
  _examples/eks/versions.tf
  _examples/eks/vpc/outputs.tf
Labels: size/XL

#1255 r/deployment - allow updating from rolling update to recreate strategy
  kubernetes/resource_kubernetes_deployment.go
  kubernetes/resource_kubernetes_deployment_test.go
Labels: size/S

#1253 Filter well known labels and annotations
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/structures.go
  kubernetes/structures_test.go
  website/docs/d/namespace.html.markdown
  website/docs/r/api_service.html.markdown
  website/docs/r/certificate_signing_request.html.markdown
  website/docs/r/cluster_role.html.markdown
  website/docs/r/cluster_role_binding.html.markdown
  website/docs/r/config_map.html.markdown
  website/docs/r/cron_job.html.markdown
  website/docs/r/csi_driver.html.markdown
  website/docs/r/daemonset.html.markdown
  website/docs/r/default_service_account.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/endpoints.html.markdown
  website/docs/r/horizontal_pod_autoscaler.html.markdown
  website/docs/r/ingress.html.markdown
  website/docs/r/job.html.markdown
  website/docs/r/limit_range.html.markdown
  website/docs/r/mutating_webhook_configuration.html.markdown
  website/docs/r/namespace.html.markdown
  website/docs/r/network_policy.html.markdown
  website/docs/r/persistent_volume.html.markdown
  website/docs/r/persistent_volume_claim.html.markdown
  website/docs/r/pod.html.markdown
  website/docs/r/pod_disruption_budget.html.markdown
  website/docs/r/pod_security_policy.html.markdown
  website/docs/r/priority_class.markdown
  website/docs/r/replication_controller.html.markdown
  website/docs/r/resource_quota.html.markdown
  website/docs/r/role.html.markdown
  website/docs/r/role_binding.html.markdown
  website/docs/r/secret.html.markdown
  website/docs/r/service.html.markdown
  website/docs/r/service_account.html.markdown
  website/docs/r/stateful_set.html.markdown
  website/docs/r/storage_class.html.markdown
  website/docs/r/validating_webhook_configuration.html.markdown
Labels: documentation, size/L

#1273 r/service - add validations + import checks for all tests
  kubernetes/resource_kubernetes_service.go
  kubernetes/resource_kubernetes_service_test.go
Labels: size/M

#1276 r/storage_class - add validations
  kubernetes/resource_kubernetes_storage_class.go
Labels: size/XS

#1278 r/mutating_webhook_configuration - add validations
  kubernetes/resource_kubernetes_mutating_webhook_configuration.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration_test.go
  kubernetes/schema_rule_with_operations.go
Labels: size/L

#1275 r/pod - add plan time validations
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/schema_container.go
  kubernetes/schema_pod_spec.go
  kubernetes/structures.go
Labels: size/XL

#1277 Add support for stand-alone debug mode (launch with -debug argument)
  main.go
Labels: size/XS

#1279 r/validating_webhook_configuration - add validations
  kubernetes/resource_kubernetes_validating_webhook_configuration.go
Labels: size/XS

#1283 Migrate travis tests to actions
  .github/workflows/markdown.links.config.json
  .github/workflows/test.yml
  .travis.yml
  GNUmakefile
Labels: size/M

#1285 Datasource: `kubernetes_secret`: add `binary_data` attribute
  kubernetes/data_source_kubernetes_secret.go
  kubernetes/data_source_kubernetes_secret_test.go
  website/docs/d/secret.html.markdown
Labels: documentation, size/S

#1286 Clean up makefile to remove duplicate tests
  .github/workflows/test.yml
  GNUmakefile
  scripts/markdown-link-check.sh
Labels: size/S
