Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2021-03, with the labels that each got.

#1132 Update docs for configuring the provider
  website/docs/index.html.markdown
Labels: documentation, size/M

#1189 Fix resource_field_ref schema for projected_volume
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/schema_pod_spec.go
  website/docs/index.html.markdown
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/pod.html.markdown
Labels: documentation, size/XS

#1192 Replace EKS test-infra with example
  .go-version
  kubernetes/test-infra/eks/README.md
  kubernetes/test-infra/eks/kubernetes-config/main.tf
  kubernetes/test-infra/eks/kubernetes-config/variables.tf
  kubernetes/test-infra/eks/main.tf
  kubernetes/test-infra/eks/node-config/aws_controller_deps.yaml
  kubernetes/test-infra/eks/node-config/cert-manager-crds.yaml
  kubernetes/test-infra/eks/node-config/cert-manager-crs.yaml
  kubernetes/test-infra/eks/node-config/config.tf
  kubernetes/test-infra/eks/node-config/iam_policy.json
  kubernetes/test-infra/eks/node-config/variables.tf
  kubernetes/test-infra/eks/node-config/versions.tf
  kubernetes/test-infra/eks/versions.tf
  kubernetes/test-infra/eks/vpc/main.tf
  kubernetes/test-infra/eks/vpc/versions.tf
Labels: size/XXL

#1193 Remove kubeconfig file check
  kubernetes/provider.go
Labels: size/XS

#1194 Fix some acceptance test errors
  kubernetes/resource_kubernetes_endpoints_test.go
  kubernetes/resource_kubernetes_job_test.go
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/resource_kubernetes_service_test.go
  kubernetes/resource_kubernetes_stateful_set_test.go
Labels: size/L

#1195 Use locally compiled k8s provider in TC tests
  kubernetes/test-infra/aks/main.tf
  kubernetes/test-infra/eks/main.tf
  kubernetes/test-infra/gke/main.tf
Labels: size/XS

#1196 Fix CI tests for EKS
  kubernetes/resource_kubernetes_replication_controller_test.go
  kubernetes/test-infra/eks/main.tf
Labels: size/XS

#1197 Enable helm pre-release test in TC
  kubernetes/test-infra/external-providers/.terraformrc
Labels: size/XS

#1203 Update EKS test-infra
  kubernetes/test-infra/eks/kubernetes-config/main.tf
  kubernetes/test-infra/eks/main.tf
  kubernetes/test-infra/eks/variables.tf
  kubernetes/test-infra/eks/vpc/main.tf
Labels: size/M

#1211 Inclusive language updates
  .github/pull_request_template.md
  .github/workflows/codeql-analysis.yml
  .travis.yml
  README.md
  website/docs/index.html.markdown
Labels: documentation, size/XS

#1215 Minor update to EKS test-infra
  kubernetes/test-infra/eks/kubernetes-config/main.tf
  kubernetes/test-infra/eks/main.tf
Labels: size/XS

#1020 add support for setting the persistent volume claimRef
  kubernetes/resource_kubernetes_persistent_volume.go
  kubernetes/resource_kubernetes_persistent_volume_claim_test.go
  kubernetes/resource_kubernetes_persistent_volume_test.go
  kubernetes/structure_persistent_volume_spec.go
  kubernetes/structures_container.go
  kubernetes/structures_container_test.go
Labels: size/L

#1212 kubernetes_cron_job should not force new
  kubernetes/resource_kubernetes_cron_job_test.go
  kubernetes/resource_kubernetes_job.go
  kubernetes/schema_cron_job_spec.go
  kubernetes/schema_job_spec.go
Labels: size/S

#1210 Fix grammar issue in Network Policy documentation
  website/docs/r/network_policy.html.markdown
Labels: documentation, size/XS

#1206 create csr logs the wrong error
  kubernetes/resource_kubernetes_certificate_signing_request.go
Labels: size/XS

#1204 Add secret_namespace to volume_source azure_file
  kubernetes/resource_kubernetes_persistent_volume_test.go
  kubernetes/schema_volume_source.go
  kubernetes/structure_persistent_volume_spec.go
  kubernetes/test-infra/aks/README.md
  website/docs/guides/getting-started.html.markdown
  website/docs/r/persistent_volume.html.markdown
Labels: acknowledged, documentation, size/L

#1107 validateTypeStringNullableIntOrPercent should tolerate `100%` value
  kubernetes/validators.go
  kubernetes/validators_test.go
Labels: size/S
