Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2021-02, with the labels that each got.

#1138 Read operation should set resource id to null if not found
  kubernetes/resource_kubernetes_api_service.go
  kubernetes/resource_kubernetes_cluster_role.go
  kubernetes/resource_kubernetes_cluster_role_binding.go
  kubernetes/resource_kubernetes_config_map.go
  kubernetes/resource_kubernetes_config_map_test.go
  kubernetes/resource_kubernetes_cron_job.go
  kubernetes/resource_kubernetes_csi_driver.go
  kubernetes/resource_kubernetes_daemonset.go
  kubernetes/resource_kubernetes_deployment.go
  kubernetes/resource_kubernetes_endpoints.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v2.go
  kubernetes/resource_kubernetes_ingress.go
  kubernetes/resource_kubernetes_job.go
  kubernetes/resource_kubernetes_limit_range.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration.go
  kubernetes/resource_kubernetes_namespace.go
  kubernetes/resource_kubernetes_network_policy.go
  kubernetes/resource_kubernetes_persistent_volume.go
  kubernetes/resource_kubernetes_persistent_volume_claim.go
  kubernetes/resource_kubernetes_pod.go
  kubernetes/resource_kubernetes_pod_disruption_budget.go
  kubernetes/resource_kubernetes_pod_security_policy.go
  kubernetes/resource_kubernetes_priority_class.go
  kubernetes/resource_kubernetes_replication_controller.go
  kubernetes/resource_kubernetes_resource_quota.go
  kubernetes/resource_kubernetes_role.go
  kubernetes/resource_kubernetes_role_binding.go
  kubernetes/resource_kubernetes_secret.go
  kubernetes/resource_kubernetes_service.go
  kubernetes/resource_kubernetes_service_account.go
  kubernetes/resource_kubernetes_stateful_set.go
  kubernetes/resource_kubernetes_storage_class.go
  kubernetes/resource_kubernetes_validating_webhook_configuration.go
Labels: size/L

#1146 Fix name of datasource in getting statrted guide example
  website/docs/guides/getting-started.html.markdown
Labels: documentation, size/XS

#1145 fix diff suppression for resource quantities in pv and pvc
  kubernetes/resource_kubernetes_persistent_volume.go
  kubernetes/schema_persistent_volume_claim.go
Labels: size/XS

#1148 updating service docs
  website/docs/d/service.html.markdown
  website/docs/r/service.html.markdown
Labels: documentation, size/S

#1158 Fix namespace resource in ingress example
  _examples/ingress/main.tf
Labels: size/XS

#1143 r/ingress - wait for ingress to be deleted
  kubernetes/resource_kubernetes_api_service.go
  kubernetes/resource_kubernetes_cluster_role_binding.go
  kubernetes/resource_kubernetes_config_map.go
  kubernetes/resource_kubernetes_cron_job.go
  kubernetes/resource_kubernetes_csi_driver.go
  kubernetes/resource_kubernetes_deployment.go
  kubernetes/resource_kubernetes_endpoints.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v2.go
  kubernetes/resource_kubernetes_ingress.go
  kubernetes/resource_kubernetes_job.go
  kubernetes/resource_kubernetes_limit_range.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration_test.go
  kubernetes/resource_kubernetes_namespace.go
  kubernetes/resource_kubernetes_network_policy.go
  kubernetes/resource_kubernetes_persistent_volume_claim.go
  kubernetes/resource_kubernetes_pod.go
  kubernetes/resource_kubernetes_pod_disruption_budget.go
  kubernetes/resource_kubernetes_pod_security_policy.go
  kubernetes/resource_kubernetes_priority_class.go
  kubernetes/resource_kubernetes_replication_controller.go
  kubernetes/resource_kubernetes_resource_quota.go
  kubernetes/resource_kubernetes_role_binding.go
  kubernetes/resource_kubernetes_secret.go
  kubernetes/resource_kubernetes_service.go
  kubernetes/resource_kubernetes_service_account.go
  kubernetes/resource_kubernetes_storage_class.go
  kubernetes/resource_kubernetes_validating_webhook_configuration.go
  kubernetes/resource_kubernetes_validating_webhook_configuration_test.go
Labels: size/M

#1022 support topologySpreadConstraint in pod spec schema
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/schema_pod_spec.go
  kubernetes/structures_pod.go
  website/docs/r/pod.html.markdown
Labels: documentation, size/L

#1180 Bump terraform-plugin-sdk to v2.4.4
  go.mod
  go.sum
  vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/v2/internal/plugin/convert/diagnostics.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/v2/meta/meta.go
  vendor/modules.txt
Labels: dependencies, size/XS
