Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2021-11, with the labels that each got.

#1458 Add support for networking/v1
  kubernetes/data_source_kubernetes_ingress_test.go
  kubernetes/data_source_kubernetes_ingress_v1.go
  kubernetes/data_source_kubernetes_ingress_v1_test.go
  kubernetes/provider.go
  kubernetes/resource_kubernetes_ingress_class.go
  kubernetes/resource_kubernetes_ingress_test.go
  kubernetes/resource_kubernetes_ingress_v1.go
  kubernetes/resource_kubernetes_ingress_v1_test.go
  kubernetes/schema_backend_spec_v1.go
  kubernetes/structure_ingress_spec_v1.go
  kubernetes/structure_ingress_spec_v1_test.go
  kubernetes/structures_pod_test.go
  website/docs/d/ingress_v1.html.markdown
  website/docs/r/ingress_v1.html.markdown
Labels: documentation, size/XL

#1480 Update GH action github/issue-labeler to v2.4
  .github/workflows/issue-opened.yml
Labels: size/XS

#1473 Add support for certificates/v1 API
  kubernetes/provider.go
  kubernetes/resource_kubernetes_certificate_signing_request_test.go
  kubernetes/resource_kubernetes_certificate_signing_request_v1.go
  kubernetes/resource_kubernetes_certificate_signing_request_v1_test.go
  kubernetes/structures_certificate_signing_request_v1.go
  website/docs/r/certificate_signing_request_v1.html.markdown
Labels: documentation, size/XL

#1486 Service tests
  manifest/test/acceptance/service_cluster_ip_test.go
  manifest/test/acceptance/service_external_name_test.go
  manifest/test/acceptance/service_load_balancer_test.go
  manifest/test/acceptance/service_node_port_test.go
  manifest/test/acceptance/service_test.go
  manifest/test/acceptance/testdata/Service/service.tf
  manifest/test/acceptance/testdata/Service/service_modified.tf
  manifest/test/acceptance/testdata/Service/variables.tf
  manifest/test/acceptance/testdata/Service_ClusterIP/service.tf
  manifest/test/acceptance/testdata/Service_ClusterIP/service_modified.tf
  manifest/test/acceptance/testdata/Service_ClusterIP/variables.tf
  manifest/test/acceptance/testdata/Service_ExternalName/service.tf
  manifest/test/acceptance/testdata/Service_ExternalName/service_modified.tf
  manifest/test/acceptance/testdata/Service_ExternalName/variables.tf
  manifest/test/acceptance/testdata/Service_LoadBalancer/service.tf
  manifest/test/acceptance/testdata/Service_LoadBalancer/service_modified.tf
  manifest/test/acceptance/testdata/Service_LoadBalancer/variables.tf
  manifest/test/acceptance/testdata/Service_NodePort/service.tf
  manifest/test/acceptance/testdata/Service_NodePort/service_modified.tf
  manifest/test/acceptance/testdata/Service_NodePort/variables.tf
Labels: size/XL

#1496 Fix logo
  .github/tf.png
  README.md
Labels: size/XS

#1491 Fix crash when env is empty
  kubernetes/structures_container.go
  kubernetes/structures_container_test.go
Labels: size/M

#1502 Update prune_stale_issues.yml
  .github/workflows/prune_stale_issues.yml
Labels: size/XS

#1490 Fix invalid allowedHostPaths PodSecurityPolicy patch
  kubernetes/resource_kubernetes_pod_security_policy_test.go
  kubernetes/structure_pod_security_policy_spec.go
Labels: size/XS

#1509 Update README.md TF logo location
  README.md
Labels: size/XS

#1504 Add documentation page explaining version suffixes
  website/docs/guides/versioned-resources.markdown
Labels: documentation, size/M

#1514 Update CHANGELOG for v2.7.0
  CHANGELOG.md
Labels: size/XS
