Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2021-09, with the labels that each got.

#1397 Docs for ingress_class_name in kubernetes_ingress
  website/docs/r/ingress.html.markdown
Labels: documentation, size/XS

#1353 Add timeouts block to kubernetes_manifest
  manifest/provider/apply.go
  manifest/provider/provider.go
  manifest/provider/validate.go
  manifest/provider/waiter.go
  website/docs/r/manifest.html.markdown
Labels: documentation, size/L

#1333 Add field_manager to kubernetes_manifest
  manifest/provider/apply.go
  manifest/provider/plan.go
  manifest/provider/provider.go
  manifest/test/acceptance/fieldmanager_test.go
  manifest/test/acceptance/testdata/FieldManager/field_manager.tf
  manifest/test/acceptance/testdata/FieldManager/variables.tf
  website/docs/r/manifest.html.markdown
Labels: documentation, size/L

#1403 Discover supported apiVersion for CRD via RESTMapper
  manifest/provider/resource.go
Labels: size/XS

#1410 fields is not expected here
  website/docs/r/manifest.html.markdown
Labels: documentation, size/XS

#1422 Import fix
  manifest/provider/import.go
  manifest/test/acceptance/acceptance_test.go
  manifest/test/acceptance/fix_list_attribute_update_test.go
Labels: size/XS

#1426 Fix failing unit test for parseImportID
  manifest/provider/import.go
  manifest/provider/import_test.go
Labels: size/XS
