Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2021-04, with the labels that each got.

#1200 Docs: Add link to Kubernetes Cron Job for 'kubernetes_cron_job'
  website/docs/r/cron_job.html.markdown
Labels: documentation, size/XS

#1219 Update test-infra for EKS
  kubernetes/test-infra/aks/main.tf
  kubernetes/test-infra/eks/kubernetes-config/main.tf
  kubernetes/test-infra/eks/main.tf
  kubernetes/test-infra/eks/output.tf
  kubernetes/test-infra/gke/main.tf
Labels: size/M

#1128 doc: clarify file config authentication
  website/docs/index.html.markdown
Labels: documentation, size/XS

#1220 Update examples for EKS, GKE, AKS
  _examples/aks/aks-cluster/main.tf
  _examples/aks/aks-cluster/output.tf
  _examples/aks/kubernetes-config/main.tf
  _examples/aks/kubernetes-config/variables.tf
  _examples/aks/main.tf
  _examples/eks/kubernetes-config/main.tf
  _examples/eks/kubernetes-config/variables.tf
  _examples/eks/main.tf
  _examples/eks/output.tf
  _examples/eks/variables.tf
  _examples/eks/vpc/main.tf
  _examples/gke/gke-cluster/main.tf
  _examples/gke/gke-cluster/output.tf
  _examples/gke/kubeconfig-template.yaml
  _examples/gke/kubernetes-config/main.tf
  _examples/gke/kubernetes-config/variables.tf
  _examples/gke/main.tf
  _examples/gke/variables.tf
Labels: size/XL

#1227 Fix perpetual diff in claim_ref
  kubernetes/resource_kubernetes_persistent_volume.go
  kubernetes/resource_kubernetes_persistent_volume_claim_test.go
  kubernetes/resource_kubernetes_persistent_volume_test.go
  kubernetes/structure_persistent_volume_spec.go
  kubernetes/structure_persistent_volume_spec_test.go
  kubernetes/structures_container.go
  kubernetes/structures_container_test.go
Labels: size/L

#1228 Add binary_data attribute to kubernetes_secret
  kubernetes/resource_kubernetes_secret.go
  kubernetes/resource_kubernetes_secret_test.go
  kubernetes/structures.go
  website/docs/r/secret.html.markdown
Labels: documentation, size/L

#1233 Ensure resources are created after cluster API becomes available
  kubernetes/test-infra/eks/kubernetes-config/main.tf
  kubernetes/test-infra/eks/main.tf
Labels: size/S

#978 Match specific tolerations to prevent Diffs
  kubernetes/structures_pod.go
Labels: acknowledged, size/XS

#1254 Update EKS module version to work with terraform 0.15
  kubernetes/test-infra/eks/main.tf
Labels: size/XS
