Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2021-12, with the labels that each got.

#1361 Update Github Token in stale issue task
  .github/workflows/prune_stale_issues.yml
Labels: size/XS

#1517 fix issue triage labelling gha
  .github/workflows/issue-opened.yml
Labels: size/XS

#1526 Update GHA stale bot issue message
  .github/workflows/prune_stale_issues.yml
Labels: size/XS

#1539 Update test infrastructure for GKE
  kubernetes/test-infra/gke/kubeconfig-template.yaml
  kubernetes/test-infra/gke/main.tf
Labels: size/M

#1540 GKE test infra: use gcloud as auth provider
  kubernetes/test-infra/gke/main.tf
Labels: size/XS

#1527 Fix 1214: update timeout and fix broken link
  website/docs/r/job.html.markdown
  website/docs/r/job_v1.html.markdown
Labels: documentation, size/XS

#1423 Add MutatingWebhookConfiguration data source
  kubernetes/data_source_kubernetes_mutating_webhook_configuration.go
  kubernetes/data_source_kubernetes_mutating_webhook_configuration_test.go
  kubernetes/provider.go
  website/docs/d/mutating_webhook_configuration_v1.html.markdown
Labels: documentation, size/XL

#1542 Update FAQ.md to reflect current maintainer team
  _about/FAQ.md
Labels: size/XS

#1541 Fix the type of kubernetes_ingress_v1 port name
  kubernetes/resource_kubernetes_ingress_v1_test.go
  kubernetes/schema_backend_spec_v1.go
Labels: waiting-response, size/XS
