Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2021-06, with the labels that each got.

#1289 Add missing annotations
  kubernetes/known_labels_annotations.go
  kubernetes/structures.go
Labels: size/L

#1290 Update changelog for next release
  CHANGELOG.md
Labels: size/XS

#1294 Remove self-link from metadata
  kubernetes/schema_metadata.go
  website/docs/guides/getting-started.html.markdown
Labels: documentation, size/XS

#1292 kubernetes_service: cluster_ip should support None
  CHANGELOG.md
  kubernetes/resource_kubernetes_service.go
  kubernetes/resource_kubernetes_service_test.go
Labels: size/M

#1295 Add missing labels
  kubernetes/known_labels_annotations.go
Labels: size/XS

#1298 Revert "Filter well known labels and annotations (#1253)"
  kubernetes/known_labels_annotations.go
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/structures.go
  kubernetes/structures_test.go
  website/docs/d/namespace.html.markdown
  website/docs/r/api_service.html.markdown
  website/docs/r/certificate_signing_request.html.markdown
  website/docs/r/cluster_role.html.markdown
  website/docs/r/cluster_role_binding.html.markdown
  website/docs/r/config_map.html.markdown
  website/docs/r/cron_job.html.markdown
  website/docs/r/csi_driver.html.markdown
  website/docs/r/daemonset.html.markdown
  website/docs/r/default_service_account.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/endpoints.html.markdown
  website/docs/r/horizontal_pod_autoscaler.html.markdown
  website/docs/r/ingress.html.markdown
  website/docs/r/job.html.markdown
  website/docs/r/limit_range.html.markdown
  website/docs/r/mutating_webhook_configuration.html.markdown
  website/docs/r/namespace.html.markdown
  website/docs/r/network_policy.html.markdown
  website/docs/r/persistent_volume.html.markdown
  website/docs/r/persistent_volume_claim.html.markdown
  website/docs/r/pod.html.markdown
  website/docs/r/pod_disruption_budget.html.markdown
  website/docs/r/pod_security_policy.html.markdown
  website/docs/r/priority_class.markdown
  website/docs/r/replication_controller.html.markdown
  website/docs/r/resource_quota.html.markdown
  website/docs/r/role.html.markdown
  website/docs/r/role_binding.html.markdown
  website/docs/r/secret.html.markdown
  website/docs/r/service.html.markdown
  website/docs/r/service_account.html.markdown
  website/docs/r/stateful_set.html.markdown
  website/docs/r/storage_class.html.markdown
  website/docs/r/validating_webhook_configuration.html.markdown
Labels: documentation, size/XL

#1287 docs/stateful_set: add import section
  website/docs/r/stateful_set.html.markdown
Labels: documentation, size/XS

#1304 Migrate from GitHub HashiBot pull_request_size_labeler behavior to GitHub Actions
  .github/workflows/pull-request.yml
  .hashibot.hcl
Labels: size/S

#1306 .github/workflows: Fix waiting-response label removal
  .github/workflows/issue-comment-created.yml
Labels: size/XS
