Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2021-10, with the labels that each got.

#1401 Manifest examples
  .github/workflows/check_examples.yaml
  _examples/kubernetes_manifest/bigcrd/bigcrd.tf
  _examples/kubernetes_manifest/cluster-with-resources/.skip_checks
  _examples/kubernetes_manifest/cluster-with-resources/README.md
  _examples/kubernetes_manifest/cluster-with-resources/cluster/test.tf
  _examples/kubernetes_manifest/cluster-with-resources/main.tf
  _examples/kubernetes_manifest/cluster-with-resources/manifests/test.tf
  _examples/kubernetes_manifest/configmap/main.tf
  _examples/kubernetes_manifest/crd/main.tf
  _examples/kubernetes_manifest/deployment/deployment.tf
  _examples/kubernetes_manifest/ingress/ingress.tf
  _examples/kubernetes_manifest/namespace/namespace.tf
  _examples/kubernetes_manifest/pod/pod.tf
  _examples/kubernetes_manifest/psp/psp.tf
  _examples/kubernetes_manifest/role/role.tf
  _examples/kubernetes_manifest/service/service.tf
  _examples/kubernetes_manifest/terraform-operator/.skip_checks
  _examples/kubernetes_manifest/terraform-operator/README.md
  _examples/kubernetes_manifest/terraform-operator/api-token-secret.tf
  _examples/kubernetes_manifest/terraform-operator/namespace.tf
  _examples/kubernetes_manifest/terraform-operator/sync-workspace-role.tf
  _examples/kubernetes_manifest/terraform-operator/sync-workspace-rolebinding.tf
  _examples/kubernetes_manifest/terraform-operator/sync-workspace-secret.tf
  _examples/kubernetes_manifest/terraform-operator/sync-workspace-serviceaccount.tf
  _examples/kubernetes_manifest/terraform-operator/sync-workspaces-deployment.tf
  _examples/kubernetes_manifest/terraform-operator/variables.tf
  _examples/kubernetes_manifest/terraform-operator/workspaces.app.terraform.io.tf
  _examples/kubernetes_manifest/vault/configmap.tf
  _examples/kubernetes_manifest/vault/headless.tf
  _examples/kubernetes_manifest/vault/injector.tf
  _examples/kubernetes_manifest/vault/main.tf
  _examples/kubernetes_manifest/vault/server.tf
  _examples/kubernetes_manifest/vault/variables.tf
  _examples/kubernetes_manifest/vault/webhook.tf
  _examples/kubernetes_manifest/wait/main.tf
  manifest/scripts/check_examples.sh
Labels: size/XL

#1334 Allow setting job's parallelism to zero
  kubernetes/schema_job_spec.go
  kubernetes/structure_job.go
Labels: size/XS

#1383 fix kubernetes_job "No waiting" example usage
  website/docs/r/job.html.markdown
Labels: documentation, size/XS

#1327 Replace heredoc with jsonencode in docs
  website/docs/r/secret.html.markdown
Labels: documentation, size/XS

#1236 r/ingress_class - new resource
  kubernetes/data_source_kubernetes_ingress.go
  kubernetes/provider.go
  kubernetes/resource_kubernetes_ingress_class.go
  kubernetes/resource_kubernetes_ingress_class_test.go
  website/docs/d/ingress.html.markdown
  website/docs/r/ingress_class.html.markdown
Labels: documentation, size/XL, acknowledged

#1434 Fix docs formatting for kubernetes_secret
  website/docs/r/secret.html.markdown
Labels: documentation, size/XS

#1419 Add build matrix for multiple k8s versions
  .github/workflows/manifest_acc.yaml
  manifest/test/acceptance/wait_for_test.go
Labels: size/XS

#1417 Add acceptance test for cert-manager
  manifest/test/acceptance/certmanager_test.go
  manifest/test/acceptance/testdata/CertManager/certmanager.tf
  manifest/test/acceptance/testdata/CertManager/variables.tf
Labels: size/XL

#1280 r/secret - add `immutable` argument + validations
  kubernetes/data_source_kubernetes_secret.go
  kubernetes/data_source_kubernetes_secret_test.go
  kubernetes/resource_kubernetes_secret.go
  kubernetes/resource_kubernetes_secret_test.go
  website/docs/d/secret.html.markdown
  website/docs/r/secret.html.markdown
Labels: documentation, size/L

#1030 Add behavior field to horizontal pod autoscaler
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v2_test.go
  kubernetes/schema_horizontal_pod_autoscaler.go
  kubernetes/structure_horizontal_pod_autoscaler_v2.go
  website/docs/r/horizontal_pod_autoscaler.html.markdown
Labels: documentation, size/XL
