Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2021-01, with the labels that each got.

#1109 Remove StateUpgraders from data sources
  kubernetes/data_source_kubernetes_ingress.go
  kubernetes/data_source_kubernetes_ingress_migrate.go
  kubernetes/data_source_kubernetes_ingress_test.go
  kubernetes/data_source_kubernetes_service.go
  kubernetes/data_source_kubernetes_service_migrate.go
Labels: size/XL

#1120 remove empty provider block check
  kubernetes/provider.go
Labels: size/S

#1121 Add docs for credential refresh
  README.md
  website/docs/guides/getting-started.html.markdown
  website/docs/guides/v2-upgrade-guide.markdown
  website/docs/index.html.markdown
Labels: documentation, size/XXL

#1115 Add updated examples for GKE and EKS
  GNUmakefile
  _examples/aks/README.md
  _examples/aks/aks-cluster/main.tf
  _examples/aks/aks-cluster/output.tf
  _examples/aks/aks-cluster/variables.tf
  _examples/aks/kubernetes-config/main.tf
  _examples/aks/kubernetes-config/variables.tf
  _examples/aks/main.tf
  _examples/aks/outputs.tf
  _examples/aks/variables.tf
  _examples/certificate-signing-request/main.tf
  _examples/certificate-signing-request/variables.tf
  _examples/eks/README.md
  _examples/eks/kubernetes-config/main.tf
  _examples/eks/kubernetes-config/variables.tf
  _examples/eks/main.tf
  _examples/eks/output.tf
  _examples/eks/variables.tf
  _examples/eks/versions.tf
  _examples/eks/vpc/main.tf
  _examples/eks/vpc/outputs.tf
  _examples/gke/README.md
  _examples/gke/gke-cluster/main.tf
  _examples/gke/gke-cluster/output.tf
  _examples/gke/gke-cluster/variables.tf
  _examples/gke/kubernetes-config/kubeconfig-template.yaml
  _examples/gke/kubernetes-config/main.tf
  _examples/gke/kubernetes-config/variables.tf
  _examples/gke/main.tf
  _examples/gke/outputs.tf
  _examples/google-gke-cluster/README.md
  _examples/google-gke-cluster/main.tf
  _examples/google-gke-nfs-filestore/main.tf
  _examples/http-nginx/README.md
  _examples/http-nginx/replication-controller.tf
  _examples/http-nginx/service.tf
  _examples/http-nginx/variables.tf
  _examples/ingress/README.md
  _examples/ingress/main.tf
  _examples/job/main.tf
  scripts/fmt-examples.sh
Labels: size/XXL

#1126 FIX resources state migration should migrate empty array
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/schema_resources_migrate.go
  kubernetes/schema_resources_migrate_test.go
Labels: size/M

#1125 Update docs and examples for Ingress and Service
  website/docs/d/ingress.html.markdown
  website/docs/d/service.html.markdown
  website/docs/r/ingress.html.markdown
  website/docs/r/service.html.markdown
Labels: documentation, size/L
