Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2022-12, with the labels that each got.

#1914 Modify delete operation for resources
  .changelog/1914.txt
  kubernetes/resource_kubernetes_api_service.go
  kubernetes/resource_kubernetes_cluster_role.go
  kubernetes/resource_kubernetes_cluster_role_binding.go
  kubernetes/resource_kubernetes_config_map.go
  kubernetes/resource_kubernetes_daemonset.go
  kubernetes/resource_kubernetes_deployment.go
  kubernetes/resource_kubernetes_endpoints.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v1.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v2.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v2beta2.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration_v1.go
  kubernetes/resource_kubernetes_network_policy.go
  kubernetes/resource_kubernetes_persistent_volume_claim.go
  kubernetes/resource_kubernetes_pod.go
  kubernetes/resource_kubernetes_pod_disruption_budget.go
  kubernetes/resource_kubernetes_pod_disruption_budget_v1.go
  kubernetes/resource_kubernetes_pod_security_policy.go
Labels: size/M

#1919 Modify delete operation in the resource files.
  .changelog/1919.txt
  kubernetes/resource_kubernetes_priority_class.go
  kubernetes/resource_kubernetes_replication_controller.go
  kubernetes/resource_kubernetes_resource_quota.go
  kubernetes/resource_kubernetes_role.go
  kubernetes/resource_kubernetes_role_binding.go
  kubernetes/resource_kubernetes_secret.go
  kubernetes/resource_kubernetes_service.go
  kubernetes/resource_kubernetes_service_account.go
  kubernetes/resource_kubernetes_stateful_set.go
  kubernetes/resource_kubernetes_storage_class.go
  kubernetes/resource_kubernetes_validating_webhook_configuration.go
  kubernetes/resource_kubernetes_validating_webhook_configuration_v1.go
Labels: size/S

#1924 Delete outdated ROADMAP.md
  .github/ISSUE_TEMPLATE/config.yml
  _about/ROADMAP.md
Labels: size/M, pr/no-changelog

#1927 v2.16.1
  CHANGELOG.md
  website/docs/d/service_account.html.markdown
Labels: documentation, size/S, pr/no-changelog
