Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2022-09, with the labels that each got.

#1825 Fix job deletion fail ttl
  kubernetes/resource_kubernetes_job.go
  website/docs/r/job.html.markdown
Labels: documentation, size/XS, pr/no-changelog

#1833 [TK-1443] Add `wait_for_service_account_token` option for the resource `kubernetes_secret(_v1)`
  .changelog/1833.txt
  kubernetes/resource_kubernetes_secret.go
  kubernetes/resource_kubernetes_secret_test.go
  manifest/payload/to_value.go
  website/docs/r/secret.html.markdown
  website/docs/r/secret_v1.html.markdown
Labels: documentation, size/M

#1845 Fix typo on an example (#1843)
  website/docs/r/ingress_v1.html.markdown
Labels: documentation, size/XS
