Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2022-10, with the labels that each got.

#1846 Preemption_policy attribute
  .changelog/1846.txt
  kubernetes/resource_kubernetes_priority_class.go
  kubernetes/resource_kubernetes_priority_class_test.go
  website/docs/r/priority_class.html.markdown
  website/docs/r/priority_class_v1.html.markdown
Labels: documentation, size/S

#1849 Add immutable to configmaps
  .changelog/1849.txt
  kubernetes/resource_kubernetes_config_map.go
  kubernetes/resource_kubernetes_config_map_test.go
  website/docs/r/config_map.html.markdown
  website/docs/r/config_map_v1.html.markdown
Labels: documentation, size/M

#1854 Add "immutable" attribute to kubernetes_config_map data source
  kubernetes/data_source_kubernetes_config_map.go
Labels: size/XS, pr/no-changelog

#1815 [TK-1425] Parallelize acc tests & use gke-gcloud-auth-plugin
  .github/workflows/acceptance_tests_gke.yaml
  .gitignore
  .go-version
  GNUmakefile
  kubernetes/provider_test.go
  kubernetes/resource_kubernetes_affinity_test.go
  kubernetes/resource_kubernetes_annotations_test.go
  kubernetes/resource_kubernetes_api_service_test.go
  kubernetes/resource_kubernetes_certificate_signing_request_test.go
  kubernetes/resource_kubernetes_certificate_signing_request_v1_test.go
  kubernetes/resource_kubernetes_cluster_role_binding_test.go
  kubernetes/resource_kubernetes_cluster_role_test.go
  kubernetes/resource_kubernetes_config_map_test.go
  kubernetes/resource_kubernetes_config_map_v1_data_test.go
  kubernetes/resource_kubernetes_cron_job_test.go
  kubernetes/resource_kubernetes_cron_job_v1_test.go
  kubernetes/resource_kubernetes_csi_driver_test.go
  kubernetes/resource_kubernetes_csi_driver_v1_test.go
  kubernetes/resource_kubernetes_default_service_account_test.go
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/resource_kubernetes_endpoints_test.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_test.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v1_test.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v2_test.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v2beta2_test.go
  kubernetes/resource_kubernetes_ingress_class_test.go
  kubernetes/resource_kubernetes_ingress_test.go
  kubernetes/resource_kubernetes_ingress_v1_test.go
  kubernetes/resource_kubernetes_labels_test.go
  kubernetes/resource_kubernetes_limit_range_test.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration_test.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration_v1_test.go
  kubernetes/resource_kubernetes_namespace_test.go
  kubernetes/resource_kubernetes_network_policy_test.go
  kubernetes/resource_kubernetes_persistent_volume_claim_test.go
  kubernetes/resource_kubernetes_persistent_volume_test.go
  kubernetes/resource_kubernetes_pod_disruption_budget_test.go
  kubernetes/resource_kubernetes_pod_disruption_budget_v1_test.go
  kubernetes/resource_kubernetes_pod_security_policy_test.go
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/resource_kubernetes_priority_class_test.go
  kubernetes/resource_kubernetes_replication_controller_test.go
  kubernetes/resource_kubernetes_resource_quota_test.go
  kubernetes/resource_kubernetes_role_binding_test.go
  kubernetes/resource_kubernetes_role_test.go
  kubernetes/resource_kubernetes_secret_test.go
  kubernetes/resource_kubernetes_service_account_test.go
  kubernetes/resource_kubernetes_service_test.go
  kubernetes/resource_kubernetes_stateful_set_test.go
  kubernetes/resource_kubernetes_storage_class_test.go
  kubernetes/resource_kubernetes_validating_webhook_configuration_test.go
  kubernetes/resource_kubernetes_validating_webhook_configuration_v1_test.go
  kubernetes/test-infra/aks/.terraform.lock.hcl
  kubernetes/test-infra/eks/.terraform.lock.hcl
  kubernetes/test-infra/gke/main.tf
  tools/batchacc.go
  tools/batchacc_test.go
Labels: size/XL, pr/no-changelog

#1855 Update EKS GH Action workflow
  .github/workflows/acceptance_tests_eks.yaml
Labels: size/XS, pr/no-changelog

#1858 Update tools versions and install changelog commands
  GNUmakefile
Labels: size/XS, pr/no-changelog

#1859 Update CHANGELOG.md for v2.14.0 release
  CHANGELOG.md
Labels: size/XS, pr/no-changelog

#1861 Enable AWS test infra to scale across variable number of AZ
  .github/workflows/acceptance_tests_eks.yaml
  kubernetes/test-infra/eks/main.tf
  kubernetes/test-infra/eks/variables.tf
Labels: size/M, pr/no-changelog

#1831 Add "field_manager" attribute
  .changelog/1831.txt
  kubernetes/resource_kubernetes_annotations.go
  kubernetes/resource_kubernetes_annotations_test.go
  kubernetes/resource_kubernetes_config_map_v1_data.go
  kubernetes/resource_kubernetes_config_map_v1_data_test.go
  kubernetes/resource_kubernetes_labels.go
  kubernetes/resource_kubernetes_labels_test.go
  website/docs/r/annotations.html.markdown
  website/docs/r/config_map_v1_data.html.markdown
  website/docs/r/labels.html.markdown
Labels: documentation, size/S

#1838 Add resource_kubernetes_env
  .changelog/1838.txt
  kubernetes/provider.go
  kubernetes/resource_kubernetes_env.go
  kubernetes/resource_kubernetes_env_test.go
  kubernetes/structures_env.go
  website/docs/r/env.html.markdown
Labels: documentation, size/XL

#1869 Add support for CronJob to kubernetes_env resource
  .changelog/1869.txt
  kubernetes/resource_kubernetes_annotations.go
  kubernetes/resource_kubernetes_config_map_v1_data.go
  kubernetes/resource_kubernetes_env.go
  kubernetes/resource_kubernetes_env_test.go
  kubernetes/resource_kubernetes_labels.go
Labels: size/XL

#1853 [TK-1897] Fix `behavior` attribute of `kubernetes_horizontal_pod_autoscaler_v2(beta2)`
  .changelog/1853.txt
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v1.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v2.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v2_test.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v2beta2.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v2beta2_test.go
  kubernetes/schema_horizontal_pod_autoscaler.go
  website/docs/r/horizontal_pod_autoscaler_v2.html.markdown
  website/docs/r/horizontal_pod_autoscaler_v2beta2.html.markdown
Labels: documentation, size/XL

#1834 docs: manifest: fix typo
  website/docs/r/manifest.html.markdown
Labels: documentation, size/XS

#1828 chore(doc): Change api_version to latest
  website/docs/guides/getting-started.html.markdown
  website/docs/index.html.markdown
  website/docs/r/service.html.markdown
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/XS, pr/no-changelog
