Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2022-11, with the labels that each got.

#1887 Release v2.15.0
  CHANGELOG.md
Labels: size/XS, pr/no-changelog

#1886 Fix tests formating
  kubernetes/data_source_kubernetes_config_map_test.go
  kubernetes/data_source_kubernetes_ingress_test.go
  kubernetes/data_source_kubernetes_ingress_v1_test.go
  kubernetes/data_source_kubernetes_service_test.go
  kubernetes/data_source_kubernetes_storage_class_test.go
  kubernetes/resource_kubernetes_annotations_test.go
  kubernetes/resource_kubernetes_config_map_v1_data_test.go
  kubernetes/resource_kubernetes_cron_job_test.go
  kubernetes/resource_kubernetes_cron_job_v1_test.go
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/resource_kubernetes_env_test.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v2_test.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v2beta2_test.go
  kubernetes/resource_kubernetes_ingress_test.go
  kubernetes/resource_kubernetes_ingress_v1_test.go
  kubernetes/resource_kubernetes_job_test.go
  kubernetes/resource_kubernetes_labels_test.go
  kubernetes/resource_kubernetes_persistent_volume_test.go
  kubernetes/resource_kubernetes_pod_security_policy_test.go
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/resource_kubernetes_priority_class_test.go
  kubernetes/resource_kubernetes_replication_controller_test.go
  kubernetes/resource_kubernetes_resource_quota_test.go
  kubernetes/resource_kubernetes_secret_test.go
  kubernetes/resource_kubernetes_service_test.go
  kubernetes/resource_kubernetes_stateful_set_test.go
  kubernetes/resource_kubernetes_storage_class_test.go
Labels: size/XL, pr/no-changelog

#1805 Add the endpoints data source object
  .changelog/1805.txt
  kubernetes/data_source_kubernetes_endpoints_v1.go
  kubernetes/data_source_kubernetes_endpoints_v1_test.go
  kubernetes/provider.go
  website/docs/d/endpoints_v1.html.markdown
Labels: documentation, size/L

#1871 fix waiter crash when status not present
  manifest/provider/waiter.go
Labels: size/S

#1802 Do not remove server side fields for datasources
  .changelog/1802.txt
  manifest/provider/datasource.go
  manifest/test/acceptance/datasource_resource_status_test.go
  manifest/test/acceptance/testdata/datasource-resource-status/step1.tf
  manifest/test/acceptance/testdata/datasource-resource-status/step2.tf
  manifest/test/acceptance/testdata/datasource-resource-status/variables.tf
Labels: size/M

#1892 Fix 1324 add fs groupe change policy to security context
  .changelog/1892.txt
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/schema_pod_spec.go
  kubernetes/structures_pod.go
  website/docs/d/pod.html.markdown
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/pod.html.markdown
Labels: documentation, size/M

#1882 [TK-1960] Update `container.resources` documentation for Pod, DaemonSet and Deployment kinds
  website/docs/d/pod.html.markdown
  website/docs/d/pod_v1.html.markdown
  website/docs/r/daemon_set_v1.html.markdown
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/deployment_v1.html.markdown
  website/docs/r/pod.html.markdown
  website/docs/r/pod_v1.html.markdown
Labels: documentation, size/M, pr/no-changelog

#1895 Add runtime_class_name to pod
  .changelog/1895.txt
  kubernetes/provider_test.go
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/schema_pod_spec.go
  kubernetes/structures_pod.go
  website/docs/d/pod.html.markdown
  website/docs/d/pod_v1.html.markdown
  website/docs/r/daemon_set_v1.html.markdown
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/deployment_v1.html.markdown
  website/docs/r/pod.html.markdown
  website/docs/r/pod_v1.html.markdown
Labels: documentation, size/M

#1883 [TK-1960] Mark attribute `default_secret_name` as deprecated in the documentation
  .changelog/1883.txt
  website/docs/d/service_account.html.markdown
  website/docs/d/service_account_v1.html.markdown
  website/docs/r/default_service_account.html.markdown
  website/docs/r/default_service_account_v1.html.markdown
  website/docs/r/service_account.html.markdown
  website/docs/r/service_account_v1.html.markdown
Labels: documentation, size/S

#1889 [TK-1957] Update `container.resources` schema for Pod, DaemonSet and Deployment
  .changelog/1889.txt
  GNUmakefile
  kubernetes/resource_kubernetes_daemonset_test.go
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/schema_container.go
  kubernetes/structures_container.go
  website/docs/guides/versioned-resources.markdown
Labels: documentation, size/XL

#1902 [TK-1994] Fix timeouts for `StatefulSet`, `Deployment`, and `DaemonSet`
  .changelog/1902.txt
  kubernetes/resource_kubernetes_daemonset.go
  kubernetes/resource_kubernetes_deployment.go
  kubernetes/resource_kubernetes_stateful_set.go
Labels: size/XS

#1904 Release v2.16.0
  CHANGELOG.md
Labels: size/S, pr/no-changelog

#1898 Modify delete operation for namespaces
  .changelog/1898.txt
  kubernetes/resource_kubernetes_namespace.go
Labels: size/XS

#1903 Add CODEOWNERS file
  .github/CODEOWNERS
Labels: size/XS, pr/no-changelog
