Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2022-05, with the labels that each got.

#1708 correct kube to kubectl, minor formatting
  website/docs/guides/getting-started.html.markdown
Labels: documentation, size/XS

#1586 Fix kubernetes default service account
  kubernetes/resource_kubernetes_default_service_account.go
  kubernetes/resource_kubernetes_default_service_account_test.go
Labels: size/M

#1670 [DO NOT MERGE] RelAPI Onboarding
  .github/workflows/release.yaml
  .goreleaser.yml
  .release/release-metadata.hcl
Labels: size/XS

#1716 Fix manifest re-create issue after import
  go.mod
  go.sum
  manifest/provider/import.go
  manifest/provider/plan.go
  manifest/provider/read.go
  manifest/provider/resource.go
  manifest/test/acceptance/import_test.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/hashicorp/hc-install/internal/releasesjson/checksum_downloader.go
  vendor/github.com/hashicorp/hc-install/internal/releasesjson/downloader.go
  vendor/github.com/hashicorp/hc-install/internal/releasesjson/releases.go
  vendor/github.com/hashicorp/hc-install/product/consul.go
  vendor/golang.org/x/xerrors/LICENSE
  vendor/golang.org/x/xerrors/PATENTS
  vendor/golang.org/x/xerrors/README
  vendor/golang.org/x/xerrors/adaptor.go
  vendor/golang.org/x/xerrors/codereview.cfg
  vendor/golang.org/x/xerrors/doc.go
  vendor/golang.org/x/xerrors/errors.go
  vendor/golang.org/x/xerrors/fmt.go
  vendor/golang.org/x/xerrors/format.go
  vendor/golang.org/x/xerrors/frame.go
  vendor/golang.org/x/xerrors/internal/internal.go
  vendor/golang.org/x/xerrors/wrap.go
  vendor/modules.txt
Labels: dependencies, size/XL
