Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2022-08, with the labels that each got.

#1792 [TK-1373] Update resource and data of 'kubernetes_(default_)service_account' to handle deprecated 'default_secret_name' in Kubernetes 1.24.0+
  kubernetes/data_source_kubernetes_service_account.go
  kubernetes/data_source_kubernetes_service_account_test.go
  kubernetes/provider.go
  kubernetes/resource_kubernetes_default_service_account.go
  kubernetes/resource_kubernetes_service.go
  kubernetes/resource_kubernetes_service_account.go
  kubernetes/resource_kubernetes_service_account_test.go
  kubernetes/structure_service_spec.go
  website/docs/d/service_account.html.markdown
  website/docs/d/service_account_v1.html.markdown
  website/docs/r/default_service_account.html.markdown
  website/docs/r/default_service_account_v1.html.markdown
  website/docs/r/service_account.html.markdown
  website/docs/r/service_account_v1.html.markdown
Labels: documentation, size/L

#1780 Better error messages from OpenAPI schema transformations
  manifest/morph/morph.go
  manifest/morph/morph_test.go
  manifest/provider/apply.go
  manifest/provider/plan.go
  manifest/provider/upgrade_state.go
  manifest/test/acceptance/testdata/ComputedFields/webhook/deploy/webhook.tf
Labels: size/XL

#1810 Update CHANGELOG.md file for release v2.13.0
  CHANGELOG.md
Labels: size/XS

#1797 add test for loadbalanceingress IP/Hostname check
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/resource_kubernetes_service_test.go
Labels: size/M

#1811 update labeled_issues.yml
  .github/workflows/labeled_issues.yml
Labels: size/XS

#1813 [TK-78009] Fix propagation of non-fatal Diagnostics in the type morphing logic
  _examples/kubernetes_manifest/deployment/deployment.tf
  manifest/morph/morph.go
  manifest/morph/morph_test.go
Labels: size/L

#1820 Update CHANGELOG.md for v2.13.1 release
  CHANGELOG.md
Labels: size/XS

#1816 update TF & EKS Cluster versions
  .github/workflows/acceptance_tests_eks.yaml
Labels: size/XS

#1800 Autogenerate changelog generation
  .changelog/changelog.tmpl
  .changelog/note.tmpl
  .github/workflows/changelog-checker.yml
  CHANGELOG_GUIDE.md
  GNUmakefile
Labels: size/L, pr/no-changelog
