Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2022-03, with the labels that each got.

#1593 Force new resource when changing apiVersion or Kind
  manifest/provider/plan.go
Labels: size/S

#1405 Fix waitForDeploymentReplicasFunc not waiting for rollout when generation > 1
  kubernetes/resource_kubernetes_deployment.go
Labels: size/XS

#1626 Update 'Docker config' code example of kubernetes_secret(_v1) resource.
  website/docs/r/secret.html.markdown
  website/docs/r/secret_v1.html.markdown
Labels: documentation, size/XS

#1619 Handle case when Job has been completed and removed, and the provider…
  kubernetes/resource_kubernetes_job.go
Labels: size/XS

#1613 Make attribute http of resource kubernetes_ingress_v1 optional
  kubernetes/resource_kubernetes_ingress_v1.go
  kubernetes/resource_kubernetes_ingress_v1_test.go
  kubernetes/structure_ingress_spec_v1.go
  website/docs/r/ingress_v1.html.markdown
Labels: documentation, size/L

#1617 Add a new securityContext attribute 'seccomp_profile' to pod and container spec
  kubernetes/resource_kubernetes_daemonset_test.go
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/schema_container.go
  kubernetes/schema_pod_spec.go
  kubernetes/structures_container.go
  kubernetes/structures_pod.go
  website/docs/d/pod.html.markdown
  website/docs/d/pod_v1.html.markdown
  website/docs/r/daemon_set_v1.html.markdown
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/deployment_v1.html.markdown
  website/docs/r/pod.html.markdown
  website/docs/r/pod_v1.html.markdown
Labels: documentation, size/XL

#1634 Don't fail when unable to find default SA token secret
  kubernetes/data_source_kubernetes_service_account.go
  kubernetes/data_source_kubernetes_service_account_test.go
  kubernetes/resource_kubernetes_service_account.go
  website/docs/d/service_account.html.markdown
  website/docs/d/service_account_v1.html.markdown
  website/docs/r/default_service_account.html.markdown
  website/docs/r/default_service_account_v1.html.markdown
  website/docs/r/service_account.html.markdown
  website/docs/r/service_account_v1.html.markdown
Labels: documentation, size/M

#1645 Update GKE infra code to support aplha features.
  kubernetes/test-infra/gke/main.tf
Labels: size/S

#1612 Move ingress_class_name to an argument, in spec block
  website/docs/r/ingress_v1.html.markdown
Labels: documentation, size/XS

#1648 v2.9.0
  .goreleaser.yml
  CHANGELOG.md
  kubernetes/data_source_kubernetes_mutating_webhook_configuration_test.go
  kubernetes/structures_container.go
Labels: size/S

#1657 Update HPA documentation
  website/docs/r/horizontal_pod_autoscaler.html.markdown
  website/docs/r/horizontal_pod_autoscaler_v1.html.markdown
  website/docs/r/horizontal_pod_autoscaler_v2beta2.html.markdown
Labels: documentation, size/XS

#1658 Fix crash when multiple `match_expression` are used in `kubernetes_resource_quota`
  kubernetes/resource_kubernetes_resource_quota_test.go
  kubernetes/structures.go
Labels: size/M

#1628 Make attribute 'rule' optional of validating_webhook_configuration_v1 and mutating_webhook_configuration_v1
  kubernetes/data_source_kubernetes_mutating_webhook_configuration_v1.go
  kubernetes/data_source_kubernetes_mutating_webhook_configuration_v1_test.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration_test.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration_v1.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration_v1_test.go
  kubernetes/resource_kubernetes_validating_webhook_configuration.go
  kubernetes/resource_kubernetes_validating_webhook_configuration_test.go
  kubernetes/resource_kubernetes_validating_webhook_configuration_v1.go
  kubernetes/resource_kubernetes_validating_webhook_configuration_v1_test.go
  website/docs/d/mutating_webhook_configuration_v1.html.markdown
  website/docs/r/mutating_webhook_configuration.html.markdown
  website/docs/r/mutating_webhook_configuration_v1.html.markdown
  website/docs/r/validating_webhook_configuration.html.markdown
  website/docs/r/validating_webhook_configuration_v1.html.markdown
Labels: documentation, size/XL

#1660 Add kubernetes_annotations resource
  kubernetes/provider.go
  kubernetes/resource_kubernetes_annotations.go
  kubernetes/resource_kubernetes_annotations_test.go
  website/docs/r/annotations.html.markdown
Labels: documentation, size/XL

#1650 Fix issue when the change of `seLinuxOptions.Type` doesn't update the state file
  kubernetes/structures_pod.go
Labels: size/XS

#1647 Add support for HPA Container Resource metrics
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v2beta2_test.go
  kubernetes/schema_horizontal_pod_autoscaler.go
  kubernetes/structure_horizontal_pod_autoscaler_v2.go
  website/docs/r/horizontal_pod_autoscaler_v2beta2.html.markdown
Labels: documentation, size/L

#1550 Update labeled_issues.yml to fix gha
  .github/workflows/labeled_issues.yml
Labels: size/XS
