Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2022-04, with the labels that each got.

#1671 Add kubernetes_config_map_v1_data resource
  kubernetes/provider.go
  kubernetes/resource_kubernetes_annotations.go
  kubernetes/resource_kubernetes_config_map_v1_data.go
  kubernetes/resource_kubernetes_config_map_v1_data_test.go
  kubernetes/resource_kubernetes_labels.go
  website/docs/r/config_map_v1_data.html.markdown
Labels: documentation, size/XL

#1668 Add `app_protocol` attribute to `kubernetes_service`
  kubernetes/data_source_kubernetes_service.go
  kubernetes/data_source_kubernetes_service_test.go
  kubernetes/resource_kubernetes_service.go
  kubernetes/resource_kubernetes_service_test.go
  kubernetes/structure_service_spec.go
  website/docs/d/service.html.markdown
  website/docs/d/service_v1.html.markdown
  website/docs/r/service.html.markdown
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/M

#1677 Fix GKE acceptance tests
  kubernetes/resource_kubernetes_persistent_volume_claim_test.go
  kubernetes/resource_kubernetes_persistent_volume_test.go
  kubernetes/test-infra/gke/main.tf
Labels: size/XS

#1681 Move some resources and data source under the subcategory manifest
  website/docs/d/resource.html.markdown
  website/docs/r/annotations.html.markdown
  website/docs/r/labels.html.markdown
  website/docs/r/manifest.html.markdown
Labels: documentation, size/XS

#1680 v2.10.0
  CHANGELOG.md
Labels: size/XS

#1689 Remove outdated regression tests
  GNUmakefile
  kubernetes/data_source_kubernetes_ingress_test.go
  kubernetes/data_source_kubernetes_ingress_v1_test.go
  kubernetes/provider_test.go
  kubernetes/resource_kubernetes_config_map_test.go
  kubernetes/resource_kubernetes_daemonset_test.go
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v1_test.go
  kubernetes/resource_kubernetes_ingress_test.go
  kubernetes/resource_kubernetes_job_test.go
  kubernetes/resource_kubernetes_persistent_volume_claim_test.go
  kubernetes/resource_kubernetes_persistent_volume_test.go
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/resource_kubernetes_replication_controller_test.go
  kubernetes/resource_kubernetes_service_test.go
  kubernetes/resource_kubernetes_stateful_set_test.go
  kubernetes/resource_kubernetes_validating_webhook_configuration_test.go
  kubernetes/resource_kubernetes_validating_webhook_configuration_v1_test.go
  kubernetes/test-infra/external-providers/.terraformrc
  kubernetes/test-infra/external-providers/main.tf
Labels: size/XL

#1662 Add `ip_families` and `ip_family_policy` attributes to `kubernetes_service`
  kubernetes/data_source_kubernetes_service.go
  kubernetes/data_source_kubernetes_service_test.go
  kubernetes/resource_kubernetes_service.go
  kubernetes/resource_kubernetes_service_test.go
  kubernetes/structure_service_spec.go
  website/docs/d/service.html.markdown
  website/docs/d/service_v1.html.markdown
  website/docs/r/service.html.markdown
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/L

#1686 Upgrade terraform-plugin-mux to v0.6.0
  go.mod
  go.sum
  main.go
  manifest/test/acceptance/wait_test.go
  vendor/github.com/hashicorp/terraform-plugin-mux/.goreleaser.yml
  vendor/github.com/hashicorp/terraform-plugin-mux/CHANGELOG.md
  vendor/github.com/hashicorp/terraform-plugin-mux/README.md
  vendor/github.com/hashicorp/terraform-plugin-mux/doc.go
  vendor/github.com/hashicorp/terraform-plugin-mux/go.mod
  vendor/github.com/hashicorp/terraform-plugin-mux/go.sum
  vendor/github.com/hashicorp/terraform-plugin-mux/internal/logging/context.go
  vendor/github.com/hashicorp/terraform-plugin-mux/internal/logging/doc.go
  vendor/github.com/hashicorp/terraform-plugin-mux/internal/logging/environment_variables.go
  vendor/github.com/hashicorp/terraform-plugin-mux/internal/logging/keys.go
  vendor/github.com/hashicorp/terraform-plugin-mux/internal/logging/mux.go
  vendor/github.com/hashicorp/terraform-plugin-mux/schema_server.go
  vendor/github.com/hashicorp/terraform-plugin-mux/tf5muxserver/doc.go
  vendor/github.com/hashicorp/terraform-plugin-mux/tf5muxserver/dynamic_value_equality.go
  vendor/github.com/hashicorp/terraform-plugin-mux/tf5muxserver/mux_server.go
  vendor/github.com/hashicorp/terraform-plugin-mux/tf5muxserver/mux_server_ApplyResourceChange.go
  vendor/github.com/hashicorp/terraform-plugin-mux/tf5muxserver/mux_server_ConfigureProvider.go
  vendor/github.com/hashicorp/terraform-plugin-mux/tf5muxserver/mux_server_GetProviderSchema.go
  vendor/github.com/hashicorp/terraform-plugin-mux/tf5muxserver/mux_server_ImportResourceState.go
  vendor/github.com/hashicorp/terraform-plugin-mux/tf5muxserver/mux_server_PlanResourceChange.go
  vendor/github.com/hashicorp/terraform-plugin-mux/tf5muxserver/mux_server_PrepareProviderConfig.go
  vendor/github.com/hashicorp/terraform-plugin-mux/tf5muxserver/mux_server_ReadDataSource.go
  vendor/github.com/hashicorp/terraform-plugin-mux/tf5muxserver/mux_server_ReadResource.go
  vendor/github.com/hashicorp/terraform-plugin-mux/tf5muxserver/mux_server_StopProvider.go
  vendor/github.com/hashicorp/terraform-plugin-mux/tf5muxserver/mux_server_UpgradeResourceState.go
  vendor/github.com/hashicorp/terraform-plugin-mux/tf5muxserver/mux_server_ValidateDataSourceConfig.go
  vendor/github.com/hashicorp/terraform-plugin-mux/tf5muxserver/mux_server_ValidateResourceTypeConfig.go
  vendor/github.com/hashicorp/terraform-plugin-mux/tf5muxserver/schema_equality.go
  vendor/github.com/hashicorp/terraform-plugin-mux/tf5muxserver/schema_type.go
  vendor/modules.txt
Labels: dependencies, size/XL

#1661 Fix conversion of big.Float to float64 in kubernetes_manifest
  .github/workflows/check_examples.yaml
  .github/workflows/manifest_acc.yaml
  manifest/payload/from_value.go
  manifest/payload/from_value_test.go
  manifest/test/acceptance/customresource_test.go
  manifest/test/acceptance/testdata/CustomResource/custom_resource.tf
  manifest/test/acceptance/testdata/CustomResource/terraform.tfvars
Labels: size/S

#1646 Handle 'x-kubernetes-preserve-unknown-fields' type annotation
  manifest/const.go
  manifest/morph/morph.go
  manifest/openapi/schema.go
  manifest/payload/from_value.go
  manifest/payload/from_value_test.go
  manifest/payload/to_value.go
  manifest/provider/plan.go
  manifest/test/acceptance/customresource_x_preserve_unknown_fields_test.go
  manifest/test/acceptance/testdata/x-kubernetes-preserve-unknown-fields/crd/test.tf
  manifest/test/acceptance/testdata/x-kubernetes-preserve-unknown-fields/crd/variables.tf
  manifest/test/acceptance/testdata/x-kubernetes-preserve-unknown-fields/test-cr-1.tf
  manifest/test/acceptance/testdata/x-kubernetes-preserve-unknown-fields/test-cr-2.tf
  manifest/test/acceptance/testdata/x-kubernetes-preserve-unknown-fields/variables.tf
Labels: size/XL

#1640 Fix identification of 'int-or-string' type attributes
  manifest/openapi/schema.go
  manifest/payload/to_value.go
Labels: size/XS

#1697 Fix cluster role aggregation rules selectors
  kubernetes/resource_kubernetes_cluster_role_test.go
  kubernetes/structures_rbac.go
  kubernetes/structures_rbac_test.go
Labels: size/L

#1704 Update CHANGELOG.md v2.11 with missed bug fix change
  CHANGELOG.md
Labels: size/XS

#1595 Add nested condition block to wait block
  manifest/provider/provider.go
  manifest/provider/validate.go
  manifest/provider/waiter.go
  manifest/test/acceptance/testdata/Wait/wait_for_conditions.tf
  manifest/test/acceptance/wait_test.go
  website/docs/r/manifest.html.markdown
Labels: documentation, size/L

#1706 Fix HCL formatting in manifest documentation page
  website/docs/r/manifest.html.markdown
Labels: documentation, size/XS
