Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2023-06, with the labels that each got.

#2128 Update CHANGELOG.md for v2.21.0 release
  CHANGELOG.md
Labels: size/XS, pr/no-changelog

#2129 Update release workflow version
  .github/workflows/release.yaml
Labels: size/XS, pr/no-changelog

#2132 Update CHANGELOG for v2.21.1
  CHANGELOG.md
Labels: size/XS, pr/no-changelog

#2096 Fix import instruction on manifest doc (minor)
  website/docs/r/manifest.html.markdown
Labels: documentation, size/XS, pr/no-changelog

#2119 Adds support for waiting for default service account in ns resource
  .changelog/2119.txt
  kubernetes/resource_kubernetes_namespace.go
  kubernetes/resource_kubernetes_namespace_test.go
  website/docs/d/namespace.html.markdown
Labels: documentation, size/M

#2138 Correct field_manager argument name in r/node_taint doc
  website/docs/r/node_taint.html.markdown
Labels: documentation, size/XS

#2142 bump actions/stale to v8.0.0
  .github/workflows/prune_stale_issues.yml
Labels: size/XS, pr/no-changelog

#1638 Add `tls_server_name` provider options.
  .changelog/1638.txt
  kubernetes/provider.go
  kubernetes/provider_test.go
  manifest/provider/configure.go
  manifest/provider/provider_config.go
  website/docs/index.html.markdown
Labels: documentation, size/S

#2056 Add GHA for running AKS
  .github/workflows/acceptance_tests_aks.yaml
Labels: size/S, pr/no-changelog

#2153 Fix go version in aks gha
  .github/workflows/acceptance_tests_aks.yaml
Labels: size/XS, pr/no-changelog

#2155 bump github actions gcloud/auth
  .github/workflows/acceptance_tests_gke.yaml
Labels: size/XS, pr/no-changelog

#2156 Fix kubeconfig in AKS GHA
  .github/workflows/acceptance_tests_aks.yaml
Labels: size/XS, pr/no-changelog

#2157 fix terraform version in AKS GHA
  .github/workflows/acceptance_tests_aks.yaml
Labels: size/XS, pr/no-changelog

#2118 Add `kubernetes/data_source_kubernetes_persistent_volume.go`
  .changelog/2118.txt
  kubernetes/data_source_kubernetes_persistent_volume.go
  kubernetes/data_source_kubernetes_persistent_volume_test.go
  kubernetes/provider.go
  website/docs/d/persistent_volume_v1.html.markdown
Labels: documentation, size/XL

#2160 Fix ARM_SUBSCRIPTION_ID in AKS GHA
  .github/workflows/acceptance_tests_aks.yaml
Labels: size/XS, pr/no-changelog

#2158 chore(ci): fix acceptance tests
  .github/config/acceptance_tests_kind_config.yaml
  .github/config/seccomp-profiles/audit.json
  .github/workflows/acceptance_tests_kind.yaml
  kubernetes/provider_test.go
  kubernetes/resource_kubernetes_cron_job_v1_test.go
  kubernetes/resource_kubernetes_daemonset_test.go
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/resource_kubernetes_job_test.go
  kubernetes/resource_kubernetes_pod_test.go
Labels: size/M, pr/no-changelog

#2169 Updated references to rbac documentation page
  website/docs/r/cluster_role_binding.html.markdown
  website/docs/r/cluster_role_binding_v1.html.markdown
  website/docs/r/role_binding.html.markdown
  website/docs/r/role_binding_v1.html.markdown
Labels: documentation, size/XS, pr/no-changelog

#2164 🐛 Fix an issue in `kubernetes_manifest` resource
  .changelog/2164.txt
  manifest/morph/scaffold.go
  manifest/morph/scaffold_test.go
Labels: size/L
