Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2023-12, with the labels that each got.

#2359 Fix typo in manifest documentation
  website/docs/r/manifest.html.markdown
Labels: documentation, size/XS, pr/no-changelog

#2344 Support empty TLS blocks in ingress_v1
  .changelog/2344.txt
  kubernetes/provider_ignore_metadata_test.go
  kubernetes/resource_kubernetes_ingress_v1_test.go
  kubernetes/resource_kubernetes_ingress_v1beta1_test.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration_test.go
  kubernetes/resource_kubernetes_node_taint_test.go
  kubernetes/resource_kubernetes_pod_v1_test.go
  kubernetes/resource_kubernetes_validating_webhook_configuration_v1_test.go
  kubernetes/resource_kubernetes_validating_webhook_configuration_v1beta1_test.go
  kubernetes/structure_ingress_spec.go
  kubernetes/structure_ingress_spec_v1.go
Labels: size/L

#2333 feat: Support spec.persistentVolumeClaimRetentionPolicy in kubernetes_stateful_set
  .changelog/2333.txt
  kubernetes/resource_kubernetes_stateful_set_v1_test.go
  kubernetes/schema_stateful_set_spec.go
  kubernetes/structures_stateful_set.go
  website/docs/r/stateful_set.html.markdown
  website/docs/r/stateful_set_v1.html.markdown
Labels: documentation, size/L

#2357 Split GH workflows
  .changelog/changelog.tmpl
  .github/workflows/acceptance_tests_aks.yaml
  .github/workflows/acceptance_tests_eks.yaml
  .github/workflows/acceptance_tests_gke.yaml
  .github/workflows/acceptance_tests_kind.yaml
  .github/workflows/checkers-and-linters.yml
  .github/workflows/unit-tests.yml
  GNUmakefile
Labels: size/M, pr/no-changelog

#2362 Switch to namespace-aware metadata for cron jobtemplate and sts template
  .changelog/2362.txt
  kubernetes/resource_kubernetes_cron_job_v1_test.go
  kubernetes/resource_kubernetes_stateful_set_v1_test.go
  kubernetes/schema_cron_job_spec_v1.go
  kubernetes/schema_pod_template.go
Labels: size/XS

#2341 Add Golang linter
  .github/workflows/golangci-lint.yaml
  .golangci.yml
  GNUmakefile
  kubernetes/provider.go
  kubernetes/provider_test.go
  kubernetes/resource_kubernetes_certificate_signing_request.go
  kubernetes/resource_kubernetes_certificate_signing_request_v1.go
  kubernetes/resource_kubernetes_cron_job_v1.go
  kubernetes/resource_kubernetes_cron_job_v1beta1.go
  kubernetes/resource_kubernetes_csi_driver_v1.go
  kubernetes/resource_kubernetes_csi_driver_v1beta1.go
  kubernetes/resource_kubernetes_daemon_set_v1.go
  kubernetes/resource_kubernetes_default_service_account_v1.go
  kubernetes/resource_kubernetes_deployment_v1.go
  kubernetes/resource_kubernetes_ingress_class_v1.go
  kubernetes/resource_kubernetes_ingress_v1.go
  kubernetes/resource_kubernetes_ingress_v1beta1.go
  kubernetes/resource_kubernetes_job_v1.go
  kubernetes/resource_kubernetes_namespace_v1.go
  kubernetes/resource_kubernetes_persistent_volume_claim_v1.go
  kubernetes/resource_kubernetes_persistent_volume_claim_v1_test.go
  kubernetes/resource_kubernetes_persistent_volume_v1.go
  kubernetes/resource_kubernetes_pod_v1.go
  kubernetes/resource_kubernetes_replication_controller_v1.go
  kubernetes/resource_kubernetes_resource_quota_v1.go
  kubernetes/resource_kubernetes_secret_v1.go
  kubernetes/resource_kubernetes_service_account_v1.go
  kubernetes/resource_kubernetes_service_v1.go
  kubernetes/resource_kubernetes_stateful_set_v1.go
  kubernetes/resource_kubernetes_storage_class_v1.go
  kubernetes/schema_cron_job_spec_v1.go
  kubernetes/schema_cron_job_spec_v1beta1.go
  kubernetes/schema_pod_spec.go
  kubernetes/structure_persistent_volume_claim.go
  kubernetes/structure_persistent_volume_spec.go
  kubernetes/structures_test.go
  kubernetes/validators.go
  manifest/openapi/foundry_v2_test.go
  manifest/payload/to_value.go
  manifest/provider/clients.go
  manifest/provider/configure.go
  manifest/provider/datasource.go
  manifest/provider/plan.go
  manifest/provider/plugin.go
  manifest/provider/resource.go
  manifest/provider/waiter.go
  manifest/test/plugintest/config.go
  manifest/test/plugintest/helper.go
  manifest/test/plugintest/working_dir.go
Labels: size/XL, pr/no-changelog

#2364 🧹 Remove unnecessary error returns and handlings
  kubernetes/resource_kubernetes_certificate_signing_request_v1.go
  kubernetes/resource_kubernetes_cron_job_migrate.go
  kubernetes/resource_kubernetes_csi_driver_v1.go
  kubernetes/resource_kubernetes_csi_driver_v1beta1.go
  kubernetes/resource_kubernetes_daemonset_migrate.go
  kubernetes/resource_kubernetes_deployment_migrate.go
  kubernetes/resource_kubernetes_ingress_migrate.go
  kubernetes/resource_kubernetes_job_migrate.go
  kubernetes/resource_kubernetes_job_v1.go
  kubernetes/resource_kubernetes_pod_migrate.go
  kubernetes/resource_kubernetes_pod_security_policy_v1beta1.go
  kubernetes/resource_kubernetes_replication_controller_migrate.go
  kubernetes/resource_kubernetes_service_migrate.go
  kubernetes/resource_kubernetes_service_v1.go
  kubernetes/resource_kubernetes_stateful_set_migrate.go
  kubernetes/schema_resources_migrate.go
  kubernetes/schema_resources_migrate_test.go
  kubernetes/structure_csi_driver.go
  kubernetes/structure_csi_driver_v1.go
  kubernetes/structure_hostalias.go
  kubernetes/structure_job.go
  kubernetes/structure_network_policy.go
  kubernetes/structure_network_policy_test.go
  kubernetes/structure_pod_security_policy_spec.go
  kubernetes/structure_service_spec.go
  kubernetes/structures_certificate_signing_request_v1.go
  kubernetes/structures_container.go
  kubernetes/structures_container_test.go
  kubernetes/structures_env.go
  kubernetes/structures_pod.go
  kubernetes/structures_stateful_set.go
  kubernetes/structures_tokenrequest.go
Labels: size/XL, pr/no-changelog
