Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2023-03, with the labels that each got.

#1984 Add HashiCorp copyright headers
  .copywrite.hcl
  .github/workflows/hc-copywrite.yml
Labels: size/S, pr/no-changelog

#2028 Created a field for generate_name in secret data source
  .changelog/2028.txt
  kubernetes/data_source_kubernetes_secret.go
  kubernetes/data_source_kubernetes_secret_test.go
Labels: size/M

#2026 Add scheduler_name attribute with docs and test
  .changelog/2026.txt
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/schema_pod_spec.go
  kubernetes/structures_pod.go
  website/docs/r/deployment.html.markdown
  website/docs/r/deployment_v1.html.markdown
  website/docs/r/pod.html.markdown
  website/docs/r/pod_v1.html.markdown
Labels: documentation, size/XS

#2030 Add Terraform Config for provisioning aks cluster
  kubernetes/test-infra/aks-new/.gitignore
  kubernetes/test-infra/aks-new/main.tf
  kubernetes/test-infra/aks-new/variables.tf
Labels: size/M, pr/no-changelog

#2018 Add Diagnostic when determining Terraform type fails
  .changelog/2018.txt
  manifest/morph/morph.go
Labels: size/M

#2041 🤖 Update GitHub workflows
  .github/workflows/acceptance_tests_eks.yaml
  .github/workflows/acceptance_tests_gke.yaml
  .github/workflows/acceptance_tests_kind.yaml
  .github/workflows/check_examples.yaml
  .github/workflows/manifest_acc.yaml
  .github/workflows/test.yml
  .go-version
Labels: size/M, pr/no-changelog

#2044 🤖 Update Check examples GH workflow
  _examples/kubernetes_manifest/ingress/ingress.tf
  _examples/kubernetes_manifest/psp/psp.tf
  _examples/kubernetes_manifest/vault/server.tf
  _examples/kubernetes_manifest/vault/webhook.tf
Labels: size/S, pr/no-changelog

#2024 Add `kubernetes_token_request` resource
  .changelog/2024.txt
  kubernetes/provider.go
  kubernetes/resource_kubernetes_tokenrequest.go
  kubernetes/resource_kubernetes_tokenrequest_test.go
  kubernetes/schema_token_request.go
  kubernetes/structures_tokenrequest.go
  website/docs/r/token_request_v1.html.markdown
Labels: documentation, size/XL

#2054 Use actual type of input value in morpher diagnostic.
  .changelog/2054.txt
  manifest/morph/morph.go
Labels: size/XS

#2055 Fix crash in manifest when configuration contains DynamicPseudotyped unknown values.
  .changelog/2055.txt
  manifest/morph/scaffold.go
Labels: size/XS

#2060 v2.19.0
  .changelog/changelog.tmpl
  CHANGELOG.md
  kubernetes/schema_token_request.go
Labels: size/S, pr/no-changelog

#2061 Fix diff when importing podspec resources containing volume_mount
  .changelog/2061.txt
  kubernetes/structures_container.go
  kubernetes/structures_container_test.go
Labels: size/M

#2062 Sdk lints
  kubernetes/resource_kubernetes_certificate_signing_request.go
  kubernetes/resource_kubernetes_persistent_volume.go
  kubernetes/resource_kubernetes_persistent_volume_claim.go
  kubernetes/resource_kubernetes_storage_class.go
Labels: size/XS, pr/no-changelog

#2063 add force and force_manager attribute to `kubernetes_node_taints` docs
  website/docs/r/node_taint.html.markdown
Labels: pr/no-changelog
