Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2023-07, with the labels that each got.

#2173 🐛 Fix the wait conditions issue in the kubernetes_manifest resource
  .changelog/2173.txt
  kubernetes/test-infra/gke/main.tf
  manifest/provider/apply.go
  manifest/test/acceptance/testdata/Wait/wait_for_fields_annotations.tf
  manifest/test/acceptance/wait_test.go
  manifest/test/helper/state/state_helper.go
Labels: size/L

#2137 Feature/add addresses info to nodes
  kubernetes/data_source_kubernetes_nodes_test.go
  kubernetes/schema_node_spec.go
  kubernetes/structures_node.go
  website/docs/d/nodes.html.markdown
Labels: documentation, waiting-response, size/S, pr/no-changelog

#2154 chore(lint): make consistent make() calls
  kubernetes/patch_operations.go
  kubernetes/resource_kubernetes_ingress_class.go
  kubernetes/structure_csi_driver.go
  kubernetes/structure_csi_driver_v1.go
  kubernetes/structure_endpoints.go
  kubernetes/structure_endpointslice.go
  kubernetes/structure_ingress_spec.go
  kubernetes/structure_ingress_spec_v1.go
  kubernetes/structure_label_selector.go
  kubernetes/structure_network_policy.go
  kubernetes/structure_pod_security_policy_spec.go
  kubernetes/structure_service_spec.go
  kubernetes/structures.go
  kubernetes/structures_affinity.go
  kubernetes/structures_certificate_signing_request.go
  kubernetes/structures_certificate_signing_request_v1.go
  kubernetes/structures_container.go
  kubernetes/structures_node.go
  kubernetes/structures_rbac.go
  kubernetes/structures_storage_class.go
  manifest/payload/to_value.go
Labels: size/L, pr/no-changelog

#2159 chore(test): enable test for TTLAfterFinished feature gate
  kubernetes/resource_kubernetes_job_test.go
Labels: size/S, pr/no-changelog

#2161 chore(lint): remove unused code
  kubernetes/resource_kubernetes_config_map_test.go
  kubernetes/resource_kubernetes_daemonset_test.go
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/resource_kubernetes_persistent_volume_test.go
  kubernetes/resource_kubernetes_service_test.go
  kubernetes/resource_kubernetes_validating_webhook_configuration_test.go
  kubernetes/schema_endpointslice.go
  kubernetes/structure_ingress_spec.go
  kubernetes/structure_ingress_spec_v1.go
  kubernetes/structure_pod_disruption_budget.go
  kubernetes/structure_pod_disruption_budget_v1.go
  kubernetes/structures.go
Labels: size/XL, pr/no-changelog

#2178 Enable nightly execution of `kind` test
  .github/workflows/acceptance_tests_kind.yaml
Labels: size/XS, pr/no-changelog

#2180 Fix `schedule` and `cron`
  .github/workflows/acceptance_tests_kind.yaml
Labels: size/XS, pr/no-changelog

#2179 Fix test infra EKS code
  kubernetes/test-infra/eks/main.tf
  kubernetes/test-infra/eks/variables.tf
Labels: size/XS, pr/no-changelog

#2182 🎉 v2.22.0
  CHANGELOG.md
Labels: size/XS, pr/no-changelog

#2181 Update FAQ.md
  _about/FAQ.md
Labels: size/XS, pr/no-changelog

#2191 Fix kind workflow
  .github/workflows/acceptance_tests_kind.yaml
Labels: size/XS, pr/no-changelog

#2166 Add lint-type-assertion check for `/manifest`
  GNUmakefile
  scripts/errcheck.sh
  scripts/errcheck_excludes.txt
Labels: size/S, pr/no-changelog

#2141 Supported `Succeeded` and `Failed` states in Target Pods
  .changelog/2141.txt
  kubernetes/resource_kubernetes_pod.go
  website/docs/r/pod.html.markdown
Labels: documentation, size/XS

#2183 Add `ephemeral volumes` to Pod Spec
  .changelog/2183.txt
  kubernetes/resource_kubernetes_persistent_volume_claim_test.go
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/schema_pod_spec.go
  kubernetes/structure_persistent_volume_spec.go
  kubernetes/structures_pod.go
  website/docs/r/pod.html.markdown
Labels: documentation, size/L

#2190 Replace images in acceptance tests
  kubernetes/resource_kubernetes_deployment_test.go
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/resource_kubernetes_replication_controller_test.go
  kubernetes/resource_kubernetes_stateful_set_test.go
Labels: size/M, pr/no-changelog

#2199 🐛 Fix generic ephemeral volume
  .changelog/2199.txt
  kubernetes/resource_kubernetes_persistent_volume_claim_test.go
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/schema_pod_spec.go
  kubernetes/structure_persistent_volume_spec.go
  kubernetes/structures.go
  kubernetes/structures_pod.go
  website/docs/r/daemon_set_v1.html.markdown
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/deployment_v1.html.markdown
  website/docs/r/pod.html.markdown
  website/docs/r/pod_v1.html.markdown
Labels: documentation, size/XL

#2193 Fix formatting for Markdown links
  website/docs/d/pod.html.markdown
  website/docs/d/pod_v1.html.markdown
  website/docs/r/daemon_set_v1.html.markdown
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/deployment_v1.html.markdown
  website/docs/r/namespace.html.markdown
  website/docs/r/namespace_v1.html.markdown
  website/docs/r/persistent_volume.html.markdown
  website/docs/r/persistent_volume_claim.html.markdown
  website/docs/r/persistent_volume_claim_v1.html.markdown
  website/docs/r/persistent_volume_v1.html.markdown
  website/docs/r/pod.html.markdown
  website/docs/r/pod_v1.html.markdown
Labels: documentation, size/S, pr/no-changelog

#2163 update flow of wait timeout; creates tfstate after TF timeout
  .changelog/2163.txt
  manifest/provider/apply.go
  manifest/provider/waiter.go
  manifest/test/acceptance/wait_test.go
  manifest/test/helper/state/state_helper.go
Labels: size/S

#2205 JIRA GHA Integration
  .github/workflows/jira_issues.yaml
  .github/workflows/jira_pr.yaml
Labels: size/L, pr/no-changelog
