Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2023-09, with the labels that each got.

#2256 Remove TF_ACC_TERRAFORM_VERSION from the GHA
  .github/workflows/acceptance_tests_kind.yaml
Labels: size/XS, pr/no-changelog

#2257 Update pod disruption tests
  kubernetes/resource_kubernetes_pod_disruption_budget_test.go
  kubernetes/resource_kubernetes_pod_disruption_budget_v1_test.go
Labels: size/L, pr/no-changelog

#2260 Fix fluky pod affinity tests
  kubernetes/resource_kubernetes_pod_v1_affinity_test.go
Labels: size/S, pr/no-changelog

#2266 Update Pod affinity tests
  kubernetes/resource_kubernetes_pod_v1_affinity_test.go
  kubernetes/resource_kubernetes_pod_v1_test.go
Labels: size/M, pr/no-changelog

#2268 Add termination_grace_period_seconds to pod tests
  kubernetes/resource_kubernetes_daemon_set_v1_test.go
  kubernetes/resource_kubernetes_deployment_v1_test.go
  kubernetes/resource_kubernetes_job_v1_test.go
  kubernetes/resource_kubernetes_pod_v1_test.go
  kubernetes/resource_kubernetes_stateful_set_v1_test.go
Labels: size/L, pr/no-changelog

#2262 Update Networking tests
  kubernetes/data_source_kubernetes_ingress.go
  kubernetes/provider.go
  kubernetes/resource_kubernetes_ingress_class_v1.go
  kubernetes/resource_kubernetes_ingress_class_v1_test.go
  kubernetes/resource_kubernetes_ingress_test.go
  kubernetes/resource_kubernetes_ingress_v1_test.go
  kubernetes/resource_kubernetes_ingress_v1beta1.go
  kubernetes/resource_kubernetes_ingress_v1beta1_test.go
  kubernetes/resource_kubernetes_network_policy_test.go
  kubernetes/resource_kubernetes_network_policy_v1.go
  kubernetes/resource_kubernetes_network_policy_v1_test.go
  kubernetes/structure_network_policy.go
  kubernetes/structure_network_policy_test.go
Labels: size/XL, pr/no-changelog

#2263 Update Token Request tests
  kubernetes/resource_kubernetes_tokenrequest_test.go
  kubernetes/resource_kubernetes_tokenrequest_v1.go
  kubernetes/resource_kubernetes_tokenrequest_v1_test.go
  kubernetes/schema_token_request.go
  kubernetes/structures_tokenrequest.go
Labels: size/L, pr/no-changelog

#2272 Update annotations test
  kubernetes/resource_kubernetes_annotations_test.go
Labels: size/XS, pr/no-changelog

#2271 Update k8s labels test
  kubernetes/resource_kubernetes_labels_test.go
Labels: size/XS, pr/no-changelog

#2274 Update runtime class tests
  kubernetes/resource_kubernetes_pod_v1_test.go
  kubernetes/resource_kubernetes_runtime_class_v1_test.go
Labels: size/M, pr/no-changelog

#2270 Update csi tests
  kubernetes/provider.go
  kubernetes/resource_kubernetes_csi_driver_v1_test.go
  kubernetes/resource_kubernetes_csi_driver_v1beta1.go
  kubernetes/resource_kubernetes_csi_driver_v1beta1_test.go
Labels: size/S, pr/no-changelog

#2258 Update pod security test
  kubernetes/provider.go
  kubernetes/resource_kubernetes_pod_security_policy_test.go
  kubernetes/resource_kubernetes_pod_security_policy_v1beta1.go
  kubernetes/resource_kubernetes_pod_security_policy_v1beta1_test.go
Labels: size/XL, pr/no-changelog

#2269 Update storage class tests
  kubernetes/data_source_kubernetes_storage_class_v1.go
  kubernetes/provider.go
  kubernetes/resource_kubernetes_persistent_volume_claim_v1_test.go
  kubernetes/resource_kubernetes_storage_class_v1.go
  kubernetes/resource_kubernetes_storage_class_v1_test.go
Labels: size/M, pr/no-changelog

#2267 Update webhook tests
  kubernetes/provider.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration_test.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration_v1_test.go
  kubernetes/resource_kubernetes_validating_webhook_configuration_v1_test.go
  kubernetes/resource_kubernetes_validating_webhook_configuration_v1beta1.go
  kubernetes/resource_kubernetes_validating_webhook_configuration_v1beta1_test.go
Labels: size/M, pr/no-changelog

#2265 Update Priority Class Tests
  kubernetes/provider.go
  kubernetes/resource_kubernetes_priority_class_test.go
  kubernetes/resource_kubernetes_priority_class_v1.go
  kubernetes/resource_kubernetes_priority_class_v1_test.go
Labels: size/XL, pr/no-changelog

#2261 Update RBAC tests
  kubernetes/provider.go
  kubernetes/resource_kubernetes_cluster_role_binding_test.go
  kubernetes/resource_kubernetes_cluster_role_binding_v1.go
  kubernetes/resource_kubernetes_cluster_role_binding_v1_test.go
  kubernetes/resource_kubernetes_cluster_role_v1.go
  kubernetes/resource_kubernetes_cluster_role_v1_test.go
  kubernetes/resource_kubernetes_role_binding_v1.go
  kubernetes/resource_kubernetes_role_binding_v1_test.go
  kubernetes/resource_kubernetes_role_test.go
  kubernetes/resource_kubernetes_role_v1.go
  kubernetes/resource_kubernetes_role_v1_test.go
Labels: size/XL, pr/no-changelog

#2277 Fix AWS EKS tests
  .github/workflows/acceptance_tests_eks.yaml
  .gitignore
  kubernetes/resource_kubernetes_certificate_signing_request_v1_test.go
  kubernetes/resource_kubernetes_cluster_role_binding_v1_test.go
  kubernetes/resource_kubernetes_config_map_v1_test.go
  kubernetes/resource_kubernetes_csi_driver_v1_test.go
  kubernetes/resource_kubernetes_csi_driver_v1beta1_test.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_test.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v1_test.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v2_test.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v2beta2_test.go
  kubernetes/resource_kubernetes_ingress_class_v1_test.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration_test.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration_v1_test.go
  kubernetes/resource_kubernetes_network_policy_v1_test.go
  kubernetes/resource_kubernetes_persistent_volume_v1_test.go
  kubernetes/resource_kubernetes_pod_disruption_budget_test.go
  kubernetes/resource_kubernetes_pod_disruption_budget_v1_test.go
  kubernetes/resource_kubernetes_pod_security_policy_v1beta1_test.go
  kubernetes/resource_kubernetes_role_binding_v1_test.go
  kubernetes/resource_kubernetes_stateful_set_v1_test.go
  kubernetes/resource_kubernetes_validating_webhook_configuration_v1_test.go
  kubernetes/resource_kubernetes_validating_webhook_configuration_v1beta1_test.go
  kubernetes/test-infra/aws-ebs-csi-driver/README.md
  kubernetes/test-infra/aws-ebs-csi-driver/main.tf
  kubernetes/test-infra/aws-ebs-csi-driver/variables.tf
  kubernetes/test-infra/eks/main.tf
  kubernetes/test-infra/eks/variables.tf
Labels: size/L, pr/no-changelog

#2280 Update AWS EKS GHA workflow
  .github/workflows/acceptance_tests_eks.yaml
  kubernetes/test-infra/eks/variables.tf
Labels: size/XS, pr/no-changelog

#2279 Update manifest.html.markdown with mentions of the actual errors related to computed_fields
  website/docs/r/manifest.html.markdown
Labels: documentation, size/XS

#2278 Enable nightly execution of AKS test
  .github/workflows/acceptance_tests_aks.yaml
  .github/workflows/acceptance_tests_eks.yaml
  kubernetes/test-infra/aks-new/main.tf
  kubernetes/test-infra/aks-new/variables.tf
Labels: size/S, pr/no-changelog

#2287 Example module for configuring EKS for OIDC authentication
  .changelog/2287.txt
  _examples/eks/eks-cluster/cluster.tf
  _examples/eks/eks-cluster/variables.tf
  _examples/eks/eks-cluster/version.tf
  _examples/eks/eks-oidc/README.md
  _examples/eks/eks-oidc/main.tf
Labels: size/M

#2283 Schedule GKE test
  .github/workflows/acceptance_tests_gke.yaml
Labels: size/XS, pr/no-changelog

#2297 Fix GLIBC issue - change OS
  .github/workflows/acceptance_tests_gke.yaml
Labels: size/XS, pr/no-changelog

#2284 Update priority_class(_v1) docs
  website/docs/r/priority_class.html.markdown
  website/docs/r/priority_class_v1.html.markdown
Labels: documentation, size/XS, pr/no-changelog

#2300 Update AKS tests
  .github/workflows/acceptance_tests_aks.yaml
  kubernetes/data_source_kubernetes_mutating_webhook_configuration_v1_test.go
  kubernetes/provider_test.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration_test.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration_v1_test.go
  kubernetes/resource_kubernetes_persistent_volume_v1_test.go
  kubernetes/resource_kubernetes_pod_v1_test.go
  kubernetes/resource_kubernetes_validating_webhook_configuration_v1_test.go
Labels: size/M, pr/no-changelog

#2296 add `match_fields` to nodeAffinity
  .changelog/2296.txt
  kubernetes/resource_kubernetes_pod_v1_affinity_test.go
  kubernetes/schema_affinity_spec.go
Labels: size/M
