Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2023-02, with the labels that each got.

#1972 Add `template_annotations` field to `kubernetes_annotations` resource.
  .changelog/1972.txt
  kubernetes/resource_kubernetes_annotations.go
  kubernetes/resource_kubernetes_annotations_test.go
  website/docs/r/annotations.html.markdown
Labels: documentation, size/XL

#1971 Add `timezone` to `kubernetes_cron_jobs`
  .changelog/1971.txt
  kubernetes/provider.go
  kubernetes/resource_kubernetes_cron_job_migrate.go
  kubernetes/resource_kubernetes_cron_job_v1.go
  kubernetes/resource_kubernetes_cron_job_v1_test.go
  kubernetes/resource_kubernetes_cron_job_v1beta1.go
  kubernetes/resource_kubernetes_cron_job_v1beta1_test.go
  kubernetes/schema_cron_job_spec_v1.go
  kubernetes/schema_cron_job_spec_v1beta1.go
  kubernetes/structure_cron_job_v1.go
  kubernetes/structure_cron_job_v1beta1.go
  website/docs/r/cron_job_v1.html.markdown
Labels: documentation, size/L

#1991 Update FAQ.md
  _about/FAQ.md
Labels: size/XS, pr/no-changelog

#1989 Update provider docs to mention not using KUBECONFIG
  website/docs/index.html.markdown
Labels: documentation, size/XS, pr/no-changelog

#1993 🤖 Update GH actions with pinned versions
  .github/workflows/acceptance_tests_gke.yaml
  .github/workflows/labeled_issues.yml
  .github/workflows/lock.yml
  .github/workflows/prune_stale_issues.yml
Labels: size/XS, pr/no-changelog

#1997 Update 'kubernetes_job' and 'kubernetes_job_v1' docs
  .changelog/1997.txt
  kubernetes/schema_job_spec.go
  website/docs/r/job.html.markdown
  website/docs/r/job_v1.html.markdown
Labels: documentation, size/XS

#1999 🐛 Fix idempotent delete operation
  .changelog/1999.txt
  kubernetes/resource_kubernetes_mutating_webhook_configuration.go
  kubernetes/resource_kubernetes_network_policy.go
  kubernetes/resource_kubernetes_persistent_volume_claim.go
Labels: size/S

#1995 Update changelog files
  .changelog/1519.txt
  .changelog/1921.txt
  .changelog/1967.txt
  .changelog/1971.txt
  .changelog/1972.txt
  .changelog/1989.txt
Labels: size/S, pr/no-changelog

#1996 🎉 Release `v2.18.0`
  CHANGELOG.md
Labels: size/S, pr/no-changelog

#2000 Update `kubernetes_manifest` tests, their dependencies and GH workflows
  .github/workflows/check_examples.yaml
  .github/workflows/manifest_acc.yaml
  .github/workflows/manifest_unit.yaml
  manifest/test/acceptance/cronjob_test.go
  manifest/test/acceptance/hpa_test.go
  manifest/test/acceptance/testdata/ComputedFields/webhook/Dockerfile
  manifest/test/acceptance/testdata/ComputedFields/webhook/go.mod
  manifest/test/acceptance/testdata/ComputedFields/webhook/go.sum
  manifest/test/acceptance/testdata/CronJob/cronjob.tf
  manifest/test/acceptance/testdata/HPA/hpa.tf
  manifest/test/acceptance/testdata/HPA/hpa_modified.tf
Labels: size/XL, pr/no-changelog

#2008 Fix waiter crash when conditions are not present
  .changelog/2008.txt
  manifest/provider/waiter.go
  manifest/test/acceptance/testdata/Wait/wait_for_condition_invalid.tf
  manifest/test/acceptance/wait_test.go
Labels: size/M

#2012 v2.18.1
  CHANGELOG.md
Labels: size/XS

#2006 Remove Computed boolean value from volume
  .changelog/2006.txt
  kubernetes/schema_pod_spec.go
Labels: size/XS

#1983 Only Remove internal keys from objects, not templates / job_template
  .changelog/1983.txt
  kubernetes/resource_kubernetes_cron_job_v1.go
  kubernetes/resource_kubernetes_cron_job_v1_test.go
  kubernetes/structure_cron_job_v1.go
  kubernetes/structures.go
Labels: size/S
