Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2023-04, with the labels that each got.

#2046 Remove limit for taints in `kubernetes_node_taint` resource
  .changelog/2046.txt
  kubernetes/resource_kubernetes_node_taint.go
  kubernetes/resource_kubernetes_node_taint_test.go
  kubernetes/schema_node_spec.go
Labels: size/XL

#2067 Add support for `initContainers` in `kubernetes_env` resource
  .changelog/2067.txt
  go.mod
  kubernetes/resource_kubernetes_env.go
  kubernetes/resource_kubernetes_env_test.go
  website/docs/r/env.html.markdown
Labels: documentation, size/XL

#2078 Fix tests for HPAv2Beta2 since it is unavailable in 1.26
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v2beta2_test.go
Labels: size/XS, pr/no-changelog

#2077 Fix an issue with `kubernetes_node_taint`
  .changelog/2077.txt
  kubernetes/resource_kubernetes_node_taint.go
Labels: size/XS

#2083 Update CHANGELOG.md for v2.20.0 release
  CHANGELOG.md
Labels: size/XS, pr/no-changelog

#2085 remove defaultSecret warning message
  .changelog/2085.txt
  kubernetes/resource_kubernetes_service_account.go
Labels: size/S
