Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2023-11, with the labels that each got.

#2337 Bump Kubernetes dependencies from x.25.11 to x.27.7
  .changelog/2337.txt
  .changelog/changelog.tmpl
  .github/workflows/acceptance_tests_kind.yaml
  go.mod
  go.sum
  kubernetes/resource_kubernetes_ingress_v1.go
  kubernetes/resource_kubernetes_ingress_v1beta1.go
  kubernetes/structure_ingress_spec.go
  kubernetes/structure_ingress_spec_v1.go
  manifest/test/acceptance/testdata/ComputedFields/webhook/Dockerfile
  manifest/test/acceptance/testdata/ComputedFields/webhook/go.mod
  manifest/test/acceptance/testdata/ComputedFields/webhook/go.sum
Labels: size/L

#2354 Docs improvements for wait feature.
  website/docs/r/manifest.html.markdown
Labels: documentation, size/XS, pr/no-changelog

#2353 Add a new field `volume_mode` to `kubernetes_persistent_volume_claim(_v1)`
  .changelog/2353.txt
  kubernetes/data_source_kubernetes_persistent_volume_claim_v1.go
  kubernetes/data_source_kubernetes_persistent_volume_claim_v1_test.go
  kubernetes/resource_kubernetes_persistent_volume_claim_v1_test.go
  kubernetes/schema_persistent_volume_claim.go
  kubernetes/structure_persistent_volume_claim.go
  kubernetes/structures.go
  kubernetes/structures_test.go
  website/docs/d/persistent_volume_claim.html.markdown
  website/docs/d/persistent_volume_claim_v1.html.markdown
  website/docs/r/persistent_volume_claim.html.markdown
  website/docs/r/persistent_volume_claim_v1.html.markdown
  website/docs/r/stateful_set_v1.html.markdown
Labels: documentation, size/L
