Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2023-10, with the labels that each got.

#2290 Add `OS` to `PodSpec`
  .changelog/2290.txt
  kubernetes/schema_pod_spec.go
  kubernetes/structures_pod.go
  website/docs/r/pod.html.markdown
Labels: documentation, size/S

#2308 Update FAQ.md
  _about/FAQ.md
Labels: size/XS, pr/no-changelog

#2298 Fix GKE tests
  kubernetes/test-infra/gke/main.tf
  kubernetes/test-infra/gke/versions.tf
Labels: size/XS, pr/no-changelog

#2314 Make kind workflow runs on PRs
  .github/workflows/acceptance_tests_kind.yaml
Labels: size/XS, pr/no-changelog

#2315 Fix OS Attribute
  kubernetes/resource_kubernetes_pod_v1_test.go
  kubernetes/schema_pod_spec.go
  kubernetes/structures_pod.go
  website/docs/r/pod.html.markdown
  website/docs/r/pod_v1.html.markdown
Labels: documentation, size/M, pr/no-changelog

#2313 🧹 Clean up test-infra and tools
  .github/workflows/acceptance_tests_aks.yaml
  .github/workflows/acceptance_tests_eks.yaml
  .github/workflows/acceptance_tests_gke.yaml
  .github/workflows/acceptance_tests_kind.yaml
  GNUmakefile
  kubernetes/test-infra/aks-new/.gitignore
  kubernetes/test-infra/aks-new/main.tf
  kubernetes/test-infra/aks-new/variables.tf
  kubernetes/test-infra/aks/main.tf
  kubernetes/test-infra/aks/outputs.tf
  kubernetes/test-infra/aks/terraform.tf
  kubernetes/test-infra/aks/variables.tf
  kubernetes/test-infra/aks/versions.tf
  kubernetes/test-infra/aws-ebs-csi-driver/versions.tf
  kubernetes/test-infra/eks-experimental/README.md
  kubernetes/test-infra/eks-experimental/eks-cluster/cluster.tf
  kubernetes/test-infra/eks-experimental/eks-cluster/iam.tf
  kubernetes/test-infra/eks-experimental/eks-cluster/variables.tf
  kubernetes/test-infra/eks-experimental/eks-cluster/vpc.tf
  kubernetes/test-infra/eks-experimental/kubernetes-config/kubeconfig.tpl
  kubernetes/test-infra/eks-experimental/kubernetes-config/main.tf
  kubernetes/test-infra/eks-experimental/kubernetes-config/output.tf
  kubernetes/test-infra/eks-experimental/kubernetes-config/variables.tf
  kubernetes/test-infra/eks-experimental/kubernetes-config/version.tf
  kubernetes/test-infra/eks-experimental/output.tf
  kubernetes/test-infra/eks-experimental/variables.tf
  kubernetes/test-infra/eks/terraform.tf
  kubernetes/test-infra/gke/main.tf
  kubernetes/test-infra/gke/outputs.tf
  kubernetes/test-infra/gke/terraform.tf
  kubernetes/test-infra/gke/variables.tf
  kubernetes/test-infra/lke/README.md
  kubernetes/test-infra/lke/main.tf
  kubernetes/test-infra/typhoon-aws/main.tf
  kubernetes/test-infra/typhoon-aws/module_1_19.tf
  kubernetes/test-infra/typhoon-aws/module_1_20.tf
  kubernetes/test-infra/typhoon-aws/variables.tf
  tools/batchacc.go
  tools/batchacc_test.go
Labels: size/XL, pr/no-changelog

#2317 Bump `golang.org/x` dependencies
  .github/workflows/manifest_acc.yaml
  .github/workflows/manifest_unit.yaml
  manifest/test/acceptance/testdata/ComputedFields/webhook/go.mod
  manifest/test/acceptance/testdata/ComputedFields/webhook/go.sum
Labels: size/S, pr/no-changelog

#2309 Update Pod Scheduler test
  kubernetes/resource_kubernetes_pod_v1_test.go
Labels: size/XS, pr/no-changelog

#2320 Switch nightly AWS EKS tests to SPOT instances
  .github/workflows/acceptance_tests_eks.yaml
  kubernetes/test-infra/eks/main.tf
  kubernetes/test-infra/eks/variables.tf
Labels: size/XS, pr/no-changelog

#2319 Example OIDC configuration modules for GKE
  .changelog/2319.txt
  _examples/eks/eks-oidc/main.tf
  _examples/gke/gke-cluster/main.tf
  _examples/gke/gke-cluster/variables.tf
  _examples/gke/gke-oidc/README.md
  _examples/gke/gke-oidc/gke.tf
  _examples/gke/gke-oidc/k8s.tf
  _examples/gke/gke-oidc/outputs.tf
  _examples/gke/gke-oidc/variables.tf
Labels: size/L

#2322 Update stateful_set resource tests
  kubernetes/resource_kubernetes_stateful_set_v1_test.go
Labels: size/XS, pr/no-changelog

#2323 Add ClusterRoleBinding and small corrections to GKE OIDC config
  _examples/eks/eks-oidc/main.tf
  _examples/gke/gke-oidc/k8s.tf
  _examples/gke/gke-oidc/variables.tf
Labels: size/S, pr/no-changelog

#2307 Add os tests
  kubernetes/schema_pod_spec.go
  kubernetes/structures_pod.go
Labels: size/M, pr/no-changelog

#2324 Add a more concrete eg of in-cluster config
  _examples/in-cluster/README.md
  _examples/in-cluster/main.tf
  _examples/in-cluster/namespace.tf
  _examples/in-cluster/pod.tf
  _examples/in-cluster/provider.tf
  website/docs/index.html.markdown
Labels: documentation, size/L, pr/no-changelog

#2330 🚀 Clean up tests
  kubernetes/resource_kubernetes_deployment_v1_test.go
  kubernetes/resource_kubernetes_persistent_volume_v1_test.go
  kubernetes/resource_kubernetes_pod_v1_test.go
  kubernetes/resource_kubernetes_replication_controller_v1_test.go
  kubernetes/resource_kubernetes_stateful_set_v1_test.go
Labels: size/S, pr/no-changelog
