Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2023-01, with the labels that each got.

#1944 Update docs to reflect new field name
  website/docs/guides/getting-started.html.markdown
Labels: documentation, size/XS, pr/no-changelog

#1922 Typo fix
  website/docs/d/pod.html.markdown
  website/docs/d/pod_v1.html.markdown
  website/docs/r/daemon_set_v1.html.markdown
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/deployment_v1.html.markdown
  website/docs/r/pod.html.markdown
  website/docs/r/pod_v1.html.markdown
Labels: documentation, size/XS, pr/no-changelog

#1936 Add kubernetes_ingress_v1 timeouts
  .changelog/1936.txt
  kubernetes/provider_test.go
  kubernetes/resource_kubernetes_ingress_v1.go
  kubernetes/resource_kubernetes_ingress_v1_test.go
  website/docs/r/ingress_v1.html.markdown
Labels: documentation, size/S

#1899 Allow `generate_name` on cluster roles + bindings, and role bindings
  .changelog/1899.txt
  kubernetes/resource_kubernetes_cluster_role.go
  kubernetes/resource_kubernetes_cluster_role_binding.go
  kubernetes/resource_kubernetes_cluster_role_binding_test.go
  kubernetes/resource_kubernetes_cluster_role_test.go
  kubernetes/resource_kubernetes_role_binding.go
  kubernetes/resource_kubernetes_role_binding_test.go
Labels: size/L

#1949 Fix HCL formatting in docs and tests
  .github/workflows/test.yml
  kubernetes/resource_kubernetes_cluster_role_binding_test.go
  website/docs/guides/getting-started.html.markdown
Labels: documentation, size/XS, pr/no-changelog

#1799 update resources/verbs docs to represent all
  website/docs/r/cluster_role_v1.html.markdown
Labels: documentation, size/XS

#1947 Make attribute `ingress_class_name` of resource `kubernetes_ingress_v1` computed
  .changelog/1947.txt
  kubernetes/resource_kubernetes_ingress_test.go
  kubernetes/resource_kubernetes_ingress_v1.go
  kubernetes/resource_kubernetes_ingress_v1_test.go
Labels: size/M

#1935 Make Deleting PVs Idempotent
  .changelog/1935.txt
  kubernetes/resource_kubernetes_persistent_volume.go
Labels: size/XS

#1952 .github/workflows: Switch pr-size-labeler action to upstream
  .github/workflows/pull-request.yml
Labels: pr/no-changelog

#1959 🐛 Update GitHub CodeQL workflow
  .github/workflows/codeql-analysis.yml
Labels: size/XS, pr/no-changelog

#1958 🐛 Fix acceptance tests and GH workflows
  kubernetes/resource_kubernetes_cron_job_test.go
  kubernetes/resource_kubernetes_pod_disruption_budget_test.go
Labels: size/XS, pr/no-changelog

#1915 Add GRPC liveness/readiness/startup_probe
  .changelog/1915.txt
  kubernetes/resource_kubernetes_pod_test.go
  kubernetes/schema_container.go
  kubernetes/structures_container.go
  website/docs/d/pod.html.markdown
  website/docs/d/pod_v1.html.markdown
  website/docs/r/daemon_set_v1.html.markdown
  website/docs/r/daemonset.html.markdown
  website/docs/r/deployment.html.markdown
  website/docs/r/deployment_v1.html.markdown
  website/docs/r/pod.html.markdown
  website/docs/r/pod_v1.html.markdown
Labels: documentation, size/L

#1519 Fix 1322: allow_volume_expansion fix
  kubernetes/resource_kubernetes_storage_class.go
  kubernetes/resource_kubernetes_storage_class_test.go
Labels: size/M, pr/no-changelog

#1961 🤖 Update GitHub workflows to use pinned commit hash versions
  .github/workflows/acceptance_tests_eks.yaml
  .github/workflows/acceptance_tests_gke.yaml
  .github/workflows/acceptance_tests_kind.yaml
  .github/workflows/changelog-checker.yml
  .github/workflows/check_examples.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/issue-comment-created.yml
  .github/workflows/issue-opened.yml
  .github/workflows/manifest_acc.yaml
  .github/workflows/manifest_unit.yaml
  .github/workflows/pull-request.yml
  .github/workflows/release.yaml
  .github/workflows/test.yml
Labels: size/L, pr/no-changelog

#1962 🤖 Update GitHub release workflow
  .github/workflows/release.yaml
Labels: size/XS, pr/no-changelog

#1921 Add data source kubernetes_nodes, resource kubernetes_node_taint
  .changelog/1921.txt
  go.mod
  go.sum
  kubernetes/data_source_kubernetes_nodes.go
  kubernetes/data_source_kubernetes_nodes_test.go
  kubernetes/provider.go
  kubernetes/resource_kubernetes_node_taint.go
  kubernetes/resource_kubernetes_node_taint_test.go
  kubernetes/schema_node_spec.go
  kubernetes/structures_node.go
  vendor/k8s.io/kubernetes/LICENSE
  vendor/k8s.io/kubernetes/pkg/apis/core/BUILD
  vendor/k8s.io/kubernetes/pkg/apis/core/OWNERS
  vendor/k8s.io/kubernetes/pkg/apis/core/annotation_key_constants.go
  vendor/k8s.io/kubernetes/pkg/apis/core/doc.go
  vendor/k8s.io/kubernetes/pkg/apis/core/field_constants.go
  vendor/k8s.io/kubernetes/pkg/apis/core/helper/BUILD
  vendor/k8s.io/kubernetes/pkg/apis/core/helper/helpers.go
  vendor/k8s.io/kubernetes/pkg/apis/core/json.go
  vendor/k8s.io/kubernetes/pkg/apis/core/objectreference.go
  vendor/k8s.io/kubernetes/pkg/apis/core/register.go
  vendor/k8s.io/kubernetes/pkg/apis/core/resource.go
  vendor/k8s.io/kubernetes/pkg/apis/core/taint.go
  vendor/k8s.io/kubernetes/pkg/apis/core/toleration.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/pkg/util/taints/BUILD
  vendor/k8s.io/kubernetes/pkg/util/taints/taints.go
  vendor/modules.txt
  website/docs/d/nodes.html.markdown
  website/docs/r/node_taint.html.markdown
  website/kubernetes.erb
Labels: documentation, dependencies, size/XL

#1967 Add data source `kubernetes_resources`
  .changelog/1967.txt
  manifest/provider/datasource.go
  manifest/provider/provider.go
  manifest/test/acceptance/datasource_test.go
  manifest/test/acceptance/testdata/datasource_plural/step1.tf
  manifest/test/acceptance/testdata/datasource_plural/step2.tf
  website/docs/d/resources.html.markdown
Labels: documentation, size/XL

#1978 Update k8s.io/kubernetes to v1.25.5
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/apis/core/BUILD
  vendor/k8s.io/kubernetes/pkg/apis/core/OWNERS
  vendor/k8s.io/kubernetes/pkg/apis/core/annotation_key_constants.go
  vendor/k8s.io/kubernetes/pkg/apis/core/doc.go
  vendor/k8s.io/kubernetes/pkg/apis/core/field_constants.go
  vendor/k8s.io/kubernetes/pkg/apis/core/helper/BUILD
  vendor/k8s.io/kubernetes/pkg/apis/core/helper/helpers.go
  vendor/k8s.io/kubernetes/pkg/apis/core/json.go
  vendor/k8s.io/kubernetes/pkg/apis/core/objectreference.go
  vendor/k8s.io/kubernetes/pkg/apis/core/register.go
  vendor/k8s.io/kubernetes/pkg/apis/core/resource.go
  vendor/k8s.io/kubernetes/pkg/apis/core/taint.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/pkg/util/taints/BUILD
  vendor/k8s.io/kubernetes/pkg/util/taints/taints.go
  vendor/modules.txt
Labels: dependencies, size/XL, pr/no-changelog

#1979 Fix nodes datasource test assertions
  kubernetes/data_source_kubernetes_nodes_test.go
Labels: size/XS, pr/no-changelog
