Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2024-05, with the labels that each got.

#2485 Fix typo preventing the use of KUBE_PROXY_URL env variable
  .changelog/2485.txt
  manifest/provider/configure.go
Labels: bug, size/XS

#2486 Changelog for release v2.30.0
  CHANGELOG.md
Labels: size/XS, pr/no-changelog

#2491 Fix nodeTaintsPolicy panic when NodeAffinityPolicy undefined
  kubernetes/structures_pod.go
Labels: size/XS

#2495 Fix PR Triage action
  .github/workflows/pull-request.yml
Labels: pr/no-changelog

#2498 Remove duplicates 1
  docs/resources/annotations.md
  docs/resources/api_service.md
  docs/resources/api_service_v1.md
  docs/resources/certificate_signing_request.md
  docs/resources/certificate_signing_request_v1.md
  docs/resources/cluster_role.md
  docs/resources/cluster_role_binding.md
  docs/resources/cluster_role_binding_v1.md
  docs/resources/cluster_role_v1.md
  docs/resources/config_map.md
  docs/resources/config_map_v1.md
  docs/resources/config_map_v1_data.md
  docs/resources/cron_job.md
  docs/resources/cron_job_v1.md
  docs/resources/csi_driver.md
  docs/resources/csi_driver_v1.md
  templates/resources/annotations.md.tmpl
  templates/resources/api_service.md.tmpl
  templates/resources/api_service_v1.md.tmpl
  templates/resources/certificate_signing_request.md.tmpl
  templates/resources/certificate_signing_request_v1.md.tmpl
  templates/resources/cluster_role.md.tmpl
  templates/resources/cluster_role_binding.md.tmpl
  templates/resources/cluster_role_binding_v1.md.tmpl
  templates/resources/cluster_role_v1.md.tmpl
  templates/resources/config_map.md.tmpl
  templates/resources/config_map_v1.md.tmpl
  templates/resources/config_map_v1_data.md.tmpl
  templates/resources/cron_job.md.tmpl
  templates/resources/cron_job_v1.md.tmpl
  templates/resources/csi_driver.md.tmpl
  templates/resources/csi_driver_v1.md.tmpl
Labels: size/XL

#2499 Remove duplicates 2
  docs/resources/daemon_set_v1.md
  docs/resources/daemonset.md
  docs/resources/default_service_account.md
  docs/resources/default_service_account_v1.md
  docs/resources/deployment.md
  docs/resources/deployment_v1.md
  docs/resources/endpoint_slice_v1.md
  docs/resources/endpoints.md
  docs/resources/endpoints_v1.md
  docs/resources/env.md
  docs/resources/horizontal_pod_autoscaler.md
  docs/resources/horizontal_pod_autoscaler_v1.md
  docs/resources/horizontal_pod_autoscaler_v2.md
  docs/resources/horizontal_pod_autoscaler_v2beta2.md
  templates/resources/daemon_set_v1.md.tmpl
  templates/resources/daemonset.md.tmpl
  templates/resources/default_service_account.md.tmpl
  templates/resources/default_service_account_v1.md.tmpl
  templates/resources/deployment.md.tmpl
  templates/resources/deployment_v1.md.tmpl
  templates/resources/endpoint_slice_v1.md.tmpl
  templates/resources/endpoints.md.tmpl
  templates/resources/endpoints_v1.md.tmpl
  templates/resources/env.md.tmpl
  templates/resources/horizontal_pod_autoscaler.md.tmpl
  templates/resources/horizontal_pod_autoscaler_v1.md.tmpl
  templates/resources/horizontal_pod_autoscaler_v2.md.tmpl
  templates/resources/horizontal_pod_autoscaler_v2beta2.md.tmpl
Labels: size/XL

#2500 Remove duplicate sections 3
  docs/guides/v2-upgrade-guide.md
  docs/resources/ingress.md
  docs/resources/ingress_class.md
  docs/resources/ingress_class_v1.md
  docs/resources/ingress_v1.md
  docs/resources/job.md
  docs/resources/job_v1.md
  docs/resources/labels.md
  docs/resources/limit_range.md
  docs/resources/limit_range_v1.md
  docs/resources/manifest.md
  docs/resources/mutating_webhook_configuration.md
  docs/resources/mutating_webhook_configuration_v1.md
  docs/resources/network_policy.md
  docs/resources/network_policy_v1.md
  docs/resources/node_taint.md
  templates/resources/ingress.md.tmpl
  templates/resources/ingress_class.md.tmpl
  templates/resources/ingress_class_v1.md.tmpl
  templates/resources/ingress_v1.md.tmpl
  templates/resources/job.md.tmpl
  templates/resources/job_v1.md.tmpl
  templates/resources/labels.md.tmpl
  templates/resources/limit_range.md.tmpl
  templates/resources/limit_range_v1.md.tmpl
  templates/resources/manifest.md.tmpl
  templates/resources/mutating_webhook_configuration.md.tmpl
  templates/resources/mutating_webhook_configuration_v1.md.tmpl
  templates/resources/network_policy.md.tmpl
  templates/resources/network_policy_v1.md.tmpl
  templates/resources/node_taint.md.tmpl
Labels: size/XL

#2501 Remove duplicate sections 4
  docs/resources/persistent_volume.md
  docs/resources/persistent_volume_claim.md
  docs/resources/persistent_volume_claim_v1.md
  docs/resources/persistent_volume_v1.md
  docs/resources/pod.md
  docs/resources/pod_disruption_budget.md
  docs/resources/pod_disruption_budget_v1.md
  docs/resources/pod_security_policy.md
  docs/resources/pod_security_policy_v1beta1.md
  docs/resources/pod_v1.md
  docs/resources/priority_class.md
  docs/resources/priority_class_v1.md
  templates/resources/persistent_volume.md.tmpl
  templates/resources/persistent_volume_claim.md.tmpl
  templates/resources/persistent_volume_claim_v1.md.tmpl
  templates/resources/persistent_volume_v1.md.tmpl
  templates/resources/pod.md.tmpl
  templates/resources/pod_disruption_budget.md.tmpl
  templates/resources/pod_disruption_budget_v1.md.tmpl
  templates/resources/pod_security_policy.md.tmpl
  templates/resources/pod_security_policy_v1beta1.md.tmpl
  templates/resources/pod_v1.md.tmpl
  templates/resources/priority_class.md.tmpl
  templates/resources/priority_class_v1.md.tmpl
Labels: size/XL

#2502 Remove duplicate sections 5
  docs/data-sources/pod.md
  docs/data-sources/pod_v1.md
  docs/index.md
  docs/resources/certificate_signing_request_v1.md
  docs/resources/ingress.md
  docs/resources/ingress_v1.md
  docs/resources/mutating_webhook_configuration.md
  docs/resources/mutating_webhook_configuration_v1.md
  docs/resources/network_policy.md
  docs/resources/network_policy_v1.md
  docs/resources/pod_security_policy.md
  docs/resources/pod_security_policy_v1beta1.md
  docs/resources/replication_controller.md
  docs/resources/replication_controller_v1.md
  docs/resources/resource_quota.md
  docs/resources/resource_quota_v1.md
  docs/resources/role.md
  docs/resources/role_binding.md
  docs/resources/role_binding_v1.md
  docs/resources/role_v1.md
  docs/resources/secret.md
  docs/resources/secret_v1.md
  docs/resources/service.md
  docs/resources/service_account.md
  docs/resources/service_account_v1.md
  docs/resources/service_v1.md
  docs/resources/stateful_set.md
  docs/resources/stateful_set_v1.md
  docs/resources/storage_class.md
  docs/resources/storage_class_v1.md
  docs/resources/token_request_v1.md
  docs/resources/validating_webhook_configuration.md
  docs/resources/validating_webhook_configuration_v1.md
  templates/resources/replication_controller.md.tmpl
  templates/resources/replication_controller_v1.md.tmpl
  templates/resources/resource_quota.md.tmpl
  templates/resources/resource_quota_v1.md.tmpl
  templates/resources/role.md.tmpl
  templates/resources/role_binding.md.tmpl
  templates/resources/role_binding_v1.md.tmpl
  templates/resources/role_v1.md.tmpl
  templates/resources/secret.md.tmpl
  templates/resources/secret_v1.md.tmpl
  templates/resources/service.md.tmpl
  templates/resources/service_account.md.tmpl
  templates/resources/service_account_v1.md.tmpl
  templates/resources/service_v1.md.tmpl
  templates/resources/stateful_set.md.tmpl
  templates/resources/stateful_set_v1.md.tmpl
  templates/resources/storage_class.md.tmpl
  templates/resources/storage_class_v1.md.tmpl
  templates/resources/token_request_v1.md.tmpl
  templates/resources/validating_webhook_configuration.md.tmpl
  templates/resources/validating_webhook_configuration_v1.md.tmpl
Labels: documentation, size/XL

#2492 Update GH Runner labels to use single runner name
  .github/workflows/acceptance_tests_aks.yaml
  .github/workflows/acceptance_tests_eks.yaml
  .github/workflows/acceptance_tests_gke.yaml
  .github/workflows/acceptance_tests_kind.yaml
Labels: size/XS
