Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2024-06, with the labels that each got.

#2510 Add support for deferred actions
  .changelog/2510.txt
  .github/workflows/acceptance_test_dfa.yaml
  _examples/deferred-actions/cluster.tf
  _examples/deferred-actions/crd.tf
  _examples/deferred-actions/workspace.tf
  go.mod
  go.sum
  internal/framework/provider/provider.go
  internal/mux/mux.go
  kubernetes/provider.go
  kubernetes/resource_kubernetes_env_test.go
  kubernetes/structures.go
  kubernetes/structures_test.go
  kubernetes/test-dfa/config-basic/cluster.tf
  kubernetes/test-dfa/config-basic/crd.tf
  kubernetes/test-dfa/config-basic/workspace.tf
  kubernetes/test-dfa/deferred_actions_test.go
  main.go
  manifest/provider/configure.go
  manifest/provider/import.go
  manifest/provider/plan.go
  manifest/provider/plugin.go
  manifest/provider/provider_config.go
  manifest/provider/read.go
  manifest/provider/server.go
Labels: size/XL

#2521 Simplify past tags detection in release workflow
  .github/workflows/release.yaml
Labels: size/XS, pr/no-changelog

#2513 add `oncall_review_assigner` step into `issue-opened.yml` workflow
  .github/workflows/issue-opened.yml
Labels: enhancement, size/S, pr/no-changelog

#2526 Refine issue assigner in `issue-opened.yml`
  .github/workflows/issue-opened.yml
Labels: size/XS, pr/no-changelog

#2528 `issue-assigner`: use 201 status code for error handling
  .github/workflows/issue-opened.yml
Labels: size/XS, pr/no-changelog
