Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2024-12, with the labels that each got.

#2642 `CI`: require `Ephemeral` Tests to use `1.10` + add `1.10` TF into CI
  .github/workflows/acceptance_tests_aks.yaml
  .github/workflows/acceptance_tests_eks.yaml
  .github/workflows/acceptance_tests_gke.yaml
  .github/workflows/acceptance_tests_kind.yaml
  .github/workflows/check_examples.yaml
  internal/framework/provider/authenticationv1/ephemeral_token_request_v1_test.go
  internal/framework/provider/certificatesv1/ephemeral_certificate_signing_request_v1_test.go
Labels: size/XS, pr/no-changelog

#2643 `CI`: remove the use of Github vars in workflows
  .github/workflows/acceptance_tests_aks.yaml
  .github/workflows/acceptance_tests_eks.yaml
  .github/workflows/acceptance_tests_gke.yaml
  .github/workflows/acceptance_tests_kind.yaml
Labels: size/S, pr/no-changelog

#2647 Release v2.35.0
  CHANGELOG.md
  kubernetes/resource_kubernetes_daemon_set_v1_test.go
Labels: size/XS, pr/no-changelog

#2653 🐛 Update max_unavailable and max_surge validate functions
  .changelog/2653.txt
  kubernetes/resource_kubernetes_daemon_set_v1.go
  kubernetes/resource_kubernetes_daemon_set_v1_test.go
Labels: size/S

#2650 Revert "Handle Jobs with ttl_seconds_after_finished = 0 correctly"
  .changelog/2650.txt
  kubernetes/resource_kubernetes_job_v1.go
  kubernetes/resource_kubernetes_job_v1_test.go
  kubernetes/schema_job_spec.go
Labels: size/M

#2659 v2.35.1
  CHANGELOG.md
Labels: size/XS, pr/no-changelog
