Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2024-02, with the labels that each got.

#2403 📚 Add releasing guide
  RELEASING.md
Labels: size/S, pr/no-changelog

#2413 Clean flatten metadata
  kubernetes/structures.go
  website/docs/index.html.markdown
Labels: documentation, size/S, pr/no-changelog

#2414 Bump terraform-plugin-framework to v1.5.0
  go.mod
  go.sum
Labels: size/S, pr/no-changelog

#2422 Add warning about mixing provider credentials with exec blocks
  website/docs/index.html.markdown
Labels: documentation, size/XS, pr/no-changelog

#2407 Improve service account secret docs examples
  website/docs/r/secret.html.markdown
  website/docs/r/secret_v1.html.markdown
  website/docs/r/service_account.html.markdown
  website/docs/r/service_account_v1.html.markdown
Labels: documentation, size/S, pr/no-changelog

#2423 Use `templatefile()` instead of `"template_file" provider` in GKE example
  _examples/google-gke-nfs-filestore/main.tf
Labels: size/XS, pr/no-changelog

#2429 feat: Add missing topologySpreadConstraints
  .changelog/2429.txt
  kubernetes/resource_kubernetes_pod_v1_test.go
  kubernetes/schema_pod_spec.go
  kubernetes/structures_pod.go
  website/docs/r/pod.html.markdown
  website/docs/r/pod_v1.html.markdown
Labels: documentation, size/M
