Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2024-08, with the labels that each got.

#2565 PSS-277: Bump hashicorp/ghaction-terraform-provider-release/.github/workflows/hashicorp.yml to v4.0.1
  .github/workflows/release.yaml
Labels: size/XS, pr/no-changelog

#2306 kubernetes_server_version data source
  .changelog/2306.txt
  docs/data-sources/server_version.md
  kubernetes/data_source_kubernetes_server_version.go
  kubernetes/data_source_kubernetes_server_version_test.go
  kubernetes/provider.go
  templates/data-sources/server_version.md.tmpl
Labels: waiting-response, size/L, no-documentation

#2560 📚 Fix documentation formatting
  kubernetes/data_source_kubernetes_pod_v1.go
  kubernetes/data_source_kubernetes_service_account_v1.go
  kubernetes/resource_kubernetes_namespace_v1.go
  kubernetes/resource_kubernetes_persistent_volume_v1.go
  kubernetes/resource_kubernetes_pod_v1.go
  kubernetes/resource_kubernetes_service_account_v1.go
Labels: size/XS, pr/no-changelog

#2566 Update Changelog Guide
  CHANGELOG_GUIDE.md
Labels: size/XS, pr/no-changelog

#2493 min_ready_seconds parameter support for statefulset
  .changelog/2493.txt
  docs/resources/stateful_set_v1.md
  kubernetes/resource_kubernetes_stateful_set_v1_test.go
  kubernetes/schema_stateful_set_spec.go
  kubernetes/structures_stateful_set.go
Labels: size/M, no-documentation

#2563 run acceptance tests with multiple versions of kubernetes
  .github/workflows/acceptance_tests_kind.yaml
  kubernetes/data_source_kubernetes_service_account_v1_test.go
  kubernetes/resource_kubernetes_cron_job_v1_test.go
  kubernetes/resource_kubernetes_cron_job_v1beta1_test.go
  kubernetes/resource_kubernetes_job_v1_test.go
  kubernetes/resource_kubernetes_persistent_volume_v1_test.go
  kubernetes/resource_kubernetes_pod_v1_test.go
  kubernetes/resource_kubernetes_stateful_set_v1_test.go
Labels: size/M, pr/no-changelog

#2568 Clean up manifest acceptence test workflow matrix.
  .github/workflows/manifest_acc.yaml
Labels: size/XS, pr/no-changelog

#2570 Return current state when requesting deferral.
  .changelog/2570.txt
  .github/workflows/acceptance_test_dfa.yaml
  manifest/provider/import.go
  manifest/provider/plan.go
  manifest/provider/read.go
Labels: size/M

#2571 Update CHANGELOG for v2.32.0 release
  CHANGELOG.md
Labels: size/XS, pr/no-changelog
