Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2024-10, with the labels that each got.

#2592 Fix deletion not found handling in the delete operation and adding related tests
  .changelog/2592.txt
  manifest/provider/apply.go
  manifest/test/acceptance/delete_not_found_test.go
  manifest/test/acceptance/testdata/DeleteNotFoundTest/resource.tf
  manifest/test/acceptance/testdata/DeleteNotFoundTest/variables.tf
Labels: enhancement, size/M

#2600 v2.33.0
  CHANGELOG.md
Labels: size/XS, pr/no-changelog

#2602 Fix reference link in K8s Deployment documentation
  docs/resources/deployment.md
  docs/resources/deployment_v1.md
Labels: size/XS, pr/no-changelog, no-documentation

#2595 Fix restart_policy validation in Deployment
  .changelog/2595.txt
  .github/workflows/documentation-check.yaml
  docs/resources/deployment_v1.md
  kubernetes/resource_kubernetes_deployment_v1.go
  kubernetes/resource_kubernetes_deployment_v1_test.go
Labels: size/M, no-documentation

#2605 `CI`: remove Documentation Check
  .github/workflows/documentation-check.yaml
  _about/CONTRIBUTING.md
Labels: size/M, pr/no-changelog, no-documentation

#2604 Adding secretV1Data resource
  .changelog/2604.txt
  docs/resources/secret_v1_data.md
  kubernetes/provider.go
  kubernetes/resource_kubernetes_secret_v1_data.go
  kubernetes/resource_kubernetes_secret_v1_data_test.go
Labels: size/XL, no-documentation

#2596 Handle Jobs with ttl_seconds_after_finished = 0 correctly
  .changelog/2596.txt
  kubernetes/resource_kubernetes_job_v1.go
  kubernetes/resource_kubernetes_job_v1_test.go
  kubernetes/schema_job_spec.go
Labels: enhancement, size/M
