Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2024-04, with the labels that each got.

#2428 Add provider defined functions for encoding and decoding Kubernetes manifests
  .changelog/2428.txt
  .github/workflows/provider_functions_unit.yaml
  GNUmakefile
  go.mod
  go.sum
  internal/framework/provider/functions/decode.go
  internal/framework/provider/functions/encode.go
  internal/framework/provider/functions/functions_test.go
  internal/framework/provider/functions/manifest_decode.go
  internal/framework/provider/functions/manifest_decode_multi.go
  internal/framework/provider/functions/manifest_decode_multi_test.go
  internal/framework/provider/functions/manifest_decode_test.go
  internal/framework/provider/functions/manifest_encode.go
  internal/framework/provider/functions/manifest_encode_test.go
  internal/framework/provider/functions/testdata/decode_manifest_invalid.yaml
  internal/framework/provider/functions/testdata/decode_manifest_invalid_syntax.yaml
  internal/framework/provider/functions/testdata/decode_multi.yaml
  internal/framework/provider/functions/testdata/decode_single.yaml
  internal/framework/provider/provider.go
  website/docs/d/nodes.html.markdown
  website/docs/functions/manifest_decode.html.markdown
  website/docs/functions/manifest_decode_multi.html.markdown
  website/docs/functions/manifest_encode.html.markdown
Labels: documentation, size/XL

#2461 FIX decoding nil values in manifest_decode()
  .changelog/2461.txt
  internal/framework/provider/functions/decode.go
  internal/framework/provider/functions/manifest_decode_multi_test.go
  internal/framework/provider/functions/manifest_decode_test.go
  internal/framework/provider/functions/testdata/decode_single.yaml
Labels: size/XS

#2464 Revert on datasources throwing error for non-existent resources
  .changelog/2464.txt
  kubernetes/data_source_kubernetes_config_map_v1.go
  kubernetes/data_source_kubernetes_config_map_v1_test.go
  kubernetes/data_source_kubernetes_endpoints_v1.go
  kubernetes/data_source_kubernetes_endpoints_v1_test.go
  kubernetes/data_source_kubernetes_ingress.go
  kubernetes/data_source_kubernetes_ingress_test.go
  kubernetes/data_source_kubernetes_ingress_v1.go
  kubernetes/data_source_kubernetes_ingress_v1_test.go
  kubernetes/data_source_kubernetes_mutating_webhook_configuration_v1.go
  kubernetes/data_source_kubernetes_mutating_webhook_configuration_v1_test.go
  kubernetes/data_source_kubernetes_namespace_v1.go
  kubernetes/data_source_kubernetes_namespace_v1_test.go
  kubernetes/data_source_kubernetes_nodes.go
  kubernetes/data_source_kubernetes_nodes_test.go
  kubernetes/data_source_kubernetes_persistent_volume_claim_v1.go
  kubernetes/data_source_kubernetes_persistent_volume_claim_v1_test.go
  kubernetes/data_source_kubernetes_pod_v1.go
  kubernetes/data_source_kubernetes_pod_v1_test.go
  kubernetes/data_source_kubernetes_secret_v1.go
  kubernetes/data_source_kubernetes_secret_v1_test.go
  kubernetes/data_source_kubernetes_service_account_v1.go
  kubernetes/data_source_kubernetes_service_account_v1_test.go
  kubernetes/data_source_kubernetes_service_v1.go
  kubernetes/data_source_kubernetes_service_v1_test.go
  kubernetes/data_source_kubernetes_storage_class_v1.go
  kubernetes/data_source_kubernetes_storage_class_v1_test.go
Labels: size/XL

#2465 Update CHANGELOG for v2.29.0 release
  CHANGELOG.md
Labels: size/XS, pr/no-changelog

#2456 add 1.8 tf support for GHA workflows `This should not be merged until the release of Terraform 1.8`
  .github/workflows/check_examples.yaml
  .github/workflows/manifest_acc.yaml
  .github/workflows/provider_functions_unit.yaml
Labels: size/XS, pr/no-changelog

#2372 🐛 Fix manifest object type mutation
  .changelog/2372.txt
  manifest/morph/scaffold.go
  manifest/provider/datasource.go
  manifest/test/acceptance/datasource_resources_test.go
  manifest/test/acceptance/testdata/DataSourceResources/pods_data_source.tf
  manifest/test/helper/kubernetes/kubernetes_helper.go
Labels: size/L

#2478 Edit resource template files
  .markdownlint.yml
  docs/resources/annotations.md
  docs/resources/api_service.md
  docs/resources/api_service_v1.md
  docs/resources/certificate_signing_request.md
  docs/resources/certificate_signing_request_v1.md
  docs/resources/cluster_role.md
  docs/resources/cluster_role_binding.md
  docs/resources/cluster_role_binding_v1.md
  docs/resources/cluster_role_v1.md
  docs/resources/config_map.md
  docs/resources/config_map_v1.md
  docs/resources/config_map_v1_data.md
  docs/resources/cron_job.md
  docs/resources/cron_job_v1.md
  docs/resources/csi_driver.md
  docs/resources/csi_driver_v1.md
  kubernetes/resource_kubernetes_annotations.go
  kubernetes/resource_kubernetes_api_service_v1.go
  kubernetes/resource_kubernetes_certificate_signing_request.go
  kubernetes/resource_kubernetes_certificate_signing_request_v1.go
  kubernetes/resource_kubernetes_cluster_role_binding_v1.go
  kubernetes/resource_kubernetes_cluster_role_v1.go
  kubernetes/resource_kubernetes_config_map_v1.go
  kubernetes/resource_kubernetes_config_map_v1_data.go
  kubernetes/resource_kubernetes_cron_job_v1.go
  kubernetes/resource_kubernetes_csi_driver_v1.go
  templates/resources/annotations.md.tmpl
  templates/resources/api_service.md.tmpl
  templates/resources/api_service_v1.md.tmpl
  templates/resources/certificate_signing_request.md.tmpl
  templates/resources/certificate_signing_request_v1.md.tmpl
  templates/resources/cluster_role.md.tmpl
  templates/resources/cluster_role_binding.md.tmpl
  templates/resources/cluster_role_binding_v1.md.tmpl
  templates/resources/cluster_role_v1.md.tmpl
  templates/resources/config_map.md.tmpl
  templates/resources/config_map_v1.md.tmpl
  templates/resources/config_map_v1_data.md.tmpl
  templates/resources/cron_job.md.tmpl
  templates/resources/cron_job_v1.md.tmpl
  templates/resources/csi_driver.md.tmpl
  templates/resources/csi_driver_v1.md.tmpl
Labels: size/XL, pr/no-changelog

#2480 Edit resource template files - batch 3
  .markdownlint.yml
  docs/resources/ingress.md
  docs/resources/ingress_class.md
  docs/resources/ingress_class_v1.md
  docs/resources/ingress_v1.md
  docs/resources/job.md
  docs/resources/job_v1.md
  docs/resources/labels.md
  docs/resources/limit_range.md
  docs/resources/limit_range_v1.md
  docs/resources/manifest.md
  docs/resources/mutating_webhook_configuration.md
  docs/resources/mutating_webhook_configuration_v1.md
  docs/resources/namespace.md
  docs/resources/network_policy.md
  docs/resources/network_policy_v1.md
  docs/resources/node_taint.md
  kubernetes/resource_kubernetes_ingress_class_v1.go
  kubernetes/resource_kubernetes_ingress_v1.go
  kubernetes/resource_kubernetes_job_v1.go
  kubernetes/resource_kubernetes_labels.go
  kubernetes/resource_kubernetes_limit_range_v1.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration_v1.go
  kubernetes/resource_kubernetes_network_policy_v1.go
  kubernetes/resource_kubernetes_node_taint.go
  templates/resources/ingress.md.tmpl
  templates/resources/ingress_class.md.tmpl
  templates/resources/ingress_class_v1.md.tmpl
  templates/resources/ingress_v1.md.tmpl
  templates/resources/job.md.tmpl
  templates/resources/job_v1.md.tmpl
  templates/resources/labels.md.tmpl
  templates/resources/limit_range.md.tmpl
  templates/resources/limit_range_v1.md.tmpl
  templates/resources/manifest.md.tmpl
  templates/resources/mutating_webhook_configuration.md.tmpl
  templates/resources/mutating_webhook_configuration_v1.md.tmpl
  templates/resources/namespace.md.tmpl
  templates/resources/network_policy.md.tmpl
  templates/resources/network_policy_v1.md.tmpl
  templates/resources/node_taint.md.tmpl
Labels: size/XL

#2481 Edit resource template files - batch 4
  docs/resources/mutating_webhook_configuration.md
  docs/resources/mutating_webhook_configuration_v1.md
  docs/resources/persistent_volume.md
  docs/resources/persistent_volume_claim.md
  docs/resources/persistent_volume_claim_v1.md
  docs/resources/persistent_volume_v1.md
  docs/resources/pod.md
  docs/resources/pod_disruption_budget.md
  docs/resources/pod_disruption_budget_v1.md
  docs/resources/pod_security_policy.md
  docs/resources/pod_security_policy_v1beta1.md
  docs/resources/pod_v1.md
  docs/resources/priority_class.md
  docs/resources/priority_class_v1.md
  docs/resources/replication_controller.md
  docs/resources/replication_controller_v1.md
  docs/resources/resource_quota.md
  docs/resources/resource_quota_v1.md
  docs/resources/role.md
  docs/resources/role_binding.md
  docs/resources/role_binding_v1.md
  docs/resources/role_v1.md
  kubernetes/resource_kubernetes_persistent_volume_claim_v1.go
  kubernetes/resource_kubernetes_persistent_volume_v1.go
  kubernetes/resource_kubernetes_pod_disruption_budget.go
  kubernetes/resource_kubernetes_pod_disruption_budget_v1.go
  kubernetes/resource_kubernetes_pod_security_policy_v1beta1.go
  kubernetes/resource_kubernetes_pod_v1.go
  kubernetes/resource_kubernetes_priority_class_v1.go
  kubernetes/resource_kubernetes_replication_controller_v1.go
  kubernetes/resource_kubernetes_resource_quota_v1.go
  kubernetes/resource_kubernetes_role_binding_v1.go
  kubernetes/resource_kubernetes_role_v1.go
  templates/resources/persistent_volume.md.tmpl
  templates/resources/persistent_volume_claim.md.tmpl
  templates/resources/persistent_volume_claim_v1.md.tmpl
  templates/resources/persistent_volume_v1.md.tmpl
  templates/resources/pod.md.tmpl
  templates/resources/pod_disruption_budget.md.tmpl
  templates/resources/pod_disruption_budget_v1.md.tmpl
  templates/resources/pod_security_policy.md.tmpl
  templates/resources/pod_security_policy_v1beta1.md.tmpl
  templates/resources/pod_v1.md.tmpl
  templates/resources/priority_class.md.tmpl
  templates/resources/priority_class_v1.md.tmpl
  templates/resources/replication_controller.md.tmpl
  templates/resources/replication_controller_v1.md.tmpl
  templates/resources/resource_quota.md.tmpl
  templates/resources/resource_quota_v1.md.tmpl
  templates/resources/role.md.tmpl
  templates/resources/role_binding.md.tmpl
  templates/resources/role_binding_v1.md.tmpl
  templates/resources/role_v1.md.tmpl
Labels: size/XL

#2482 Edit resource template files - batch 5
  docs/resources/mutating_webhook_configuration.md
  docs/resources/secret.md
  docs/resources/secret_v1.md
  docs/resources/service.md
  docs/resources/service_account.md
  docs/resources/service_account_v1.md
  docs/resources/service_v1.md
  docs/resources/stateful_set.md
  docs/resources/stateful_set_v1.md
  docs/resources/storage_class.md
  docs/resources/storage_class_v1.md
  docs/resources/token_request_v1.md
  docs/resources/validating_webhook_configuration.md
  docs/resources/validating_webhook_configuration_v1.md
  kubernetes/resource_kubernetes_secret_v1.go
  kubernetes/resource_kubernetes_service_account_v1.go
  kubernetes/resource_kubernetes_service_v1.go
  kubernetes/resource_kubernetes_stateful_set_v1.go
  kubernetes/resource_kubernetes_storage_class_v1.go
  kubernetes/resource_kubernetes_tokenrequest_v1.go
  kubernetes/resource_kubernetes_validating_webhook_configuration_v1.go
  templates/resources/secret.md.tmpl
  templates/resources/secret_v1.md.tmpl
  templates/resources/service.md.tmpl
  templates/resources/service_account.md.tmpl
  templates/resources/service_account_v1.md.tmpl
  templates/resources/service_v1.md.tmpl
  templates/resources/stateful_set.md.tmpl
  templates/resources/stateful_set_v1.md.tmpl
  templates/resources/storage_class.md.tmpl
  templates/resources/storage_class_v1.md.tmpl
  templates/resources/token_request_v1.md.tmpl
  templates/resources/validating_webhook_configuration.md.tmpl
  templates/resources/validating_webhook_configuration_v1.md.tmpl
Labels: size/XL, pr/no-changelog
