Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2024-11, with the labels that each got.

#2612 Add conditions attribute to kubernetes_nodes data source
  .changelog/2612.txt
  docs/data-sources/nodes.md
  kubernetes/data_source_kubernetes_nodes_test.go
  kubernetes/schema_node_spec.go
  kubernetes/structures_node.go
Labels: size/M

#2619 `CI`: add `v3-major-release` into CI testing
  .github/workflows/acceptance_test_dfa.yaml
  .github/workflows/acceptance_tests_kind.yaml
  .github/workflows/check_examples.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/manifest_acc.yaml
  .github/workflows/manifest_unit.yaml
  .github/workflows/provider_functions_unit.yaml
  .github/workflows/unit-tests.yml
Labels: size/S, pr/no-changelog, CI

#2620 `CI`: proper version checking for `v1.31.2` version testing
  .github/workflows/acceptance_tests_kind.yaml
  .github/workflows/manifest_acc.yaml
Labels: size/S, pr/no-changelog

#2624 CI: use include to prevent PRs on main to use `v1.31.2`
  .github/workflows/acceptance_tests_kind.yaml
  .github/workflows/manifest_acc.yaml
Labels: size/M, pr/no-changelog

#2628 Add ephemeral resources: `kubernetes_token_request_v1`, `kubernetes_certificate_signing_request_v1`
  .changelog/2628.txt
  .github/workflows/acceptance_tests_aks.yaml
  .github/workflows/acceptance_tests_eks.yaml
  .github/workflows/acceptance_tests_gke.yaml
  .github/workflows/acceptance_tests_kind.yaml
  GNUmakefile
  docs/ephemeral-resources/kubernetes_certificate_signing_request_v1.md
  docs/ephemeral-resources/kubernetes_token_request_v1.md
  go.mod
  go.sum
  internal/framework/provider/authenticationv1/authenticationv1_test.go
  internal/framework/provider/authenticationv1/ephemeral_token_request_v1.go
  internal/framework/provider/authenticationv1/ephemeral_token_request_v1_test.go
  internal/framework/provider/certificatesv1/certificatesv1_test.go
  internal/framework/provider/certificatesv1/ephemeral_certificate_signing_request_v1.go
  internal/framework/provider/certificatesv1/ephemeral_certificate_signing_request_v1_test.go
  internal/framework/provider/functions/functions_test.go
  internal/framework/provider/provider.go
  internal/framework/provider/provider_configure.go
  internal/framework/provider/provider_test.go
  internal/mux/mux.go
Labels: size/XL

#2634 fix terraform version in kind GHA
  .github/workflows/acceptance_tests_kind.yaml
Labels: size/XS, pr/no-changelog

#2635 v2.34.0
  CHANGELOG.md
Labels: size/XS, pr/no-changelog
