Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2025-06, with the labels that each got.

#2699 Do less Kubernetes API requests
  .changelog/2699.txt
  manifest/provider/cache.go
  manifest/provider/clients.go
  manifest/provider/resource.go
  manifest/provider/server.go
Labels: size/XL

#2380 🐛 Fix Pod spec toleration when the spec is a template
  .changelog/2380.txt
  kubernetes/data_source_kubernetes_pod_v1.go
  kubernetes/data_source_kubernetes_pod_v1_test.go
  kubernetes/resource_kubernetes_deployment_v1_test.go
  kubernetes/resource_kubernetes_pod_v1.go
  kubernetes/structures_daemonset.go
  kubernetes/structures_deployment.go
  kubernetes/structures_pod.go
  kubernetes/structures_pod_test.go
  kubernetes/structures_replication_controller.go
  kubernetes/structures_stateful_set.go
Labels: size/L

#2744 Update issue-opened.yml
  .github/workflows/issue-opened.yml
Labels: size/XS, pr/no-changelog

#2751 Resource identity support in SDKv2 Resources
  .changelog/2751.txt
  .github/workflows/checkers-and-linters.yml
  kubernetes/resource_kubernetes_cluster_role_binding_v1.go
  kubernetes/resource_kubernetes_cluster_role_binding_v1_test.go
  kubernetes/resource_kubernetes_cluster_role_v1.go
  kubernetes/resource_kubernetes_cluster_role_v1_test.go
  kubernetes/resource_kubernetes_config_map_v1.go
  kubernetes/resource_kubernetes_cron_job_v1.go
  kubernetes/resource_kubernetes_cron_job_v1_test.go
  kubernetes/resource_kubernetes_daemon_set_v1.go
  kubernetes/resource_kubernetes_daemon_set_v1_test.go
  kubernetes/resource_kubernetes_deployment_v1.go
  kubernetes/resource_kubernetes_deployment_v1_test.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v2.go
  kubernetes/resource_kubernetes_horizontal_pod_autoscaler_v2_test.go
  kubernetes/resource_kubernetes_ingress_class_v1.go
  kubernetes/resource_kubernetes_ingress_class_v1_test.go
  kubernetes/resource_kubernetes_ingress_v1.go
  kubernetes/resource_kubernetes_ingress_v1_test.go
  kubernetes/resource_kubernetes_job_v1.go
  kubernetes/resource_kubernetes_job_v1_test.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration_v1.go
  kubernetes/resource_kubernetes_mutating_webhook_configuration_v1_test.go
  kubernetes/resource_kubernetes_namespace_v1.go
  kubernetes/resource_kubernetes_namespace_v1_test.go
  kubernetes/resource_kubernetes_network_policy_v1.go
  kubernetes/resource_kubernetes_network_policy_v1_test.go
  kubernetes/resource_kubernetes_pod_v1.go
  kubernetes/resource_kubernetes_pod_v1_test.go
  kubernetes/resource_kubernetes_role_binding_v1.go
  kubernetes/resource_kubernetes_role_binding_v1_test.go
  kubernetes/resource_kubernetes_role_v1.go
  kubernetes/resource_kubernetes_role_v1_test.go
  kubernetes/resource_kubernetes_secret_v1.go
  kubernetes/resource_kubernetes_secret_v1_test.go
  kubernetes/resource_kubernetes_service_account_v1.go
  kubernetes/resource_kubernetes_service_account_v1_test.go
  kubernetes/resource_kubernetes_service_v1.go
  kubernetes/resource_kubernetes_service_v1_test.go
  kubernetes/resource_kubernetes_stateful_set_v1.go
  kubernetes/resource_kubernetes_stateful_set_v1_test.go
  kubernetes/resource_kubernetes_validating_webhook_configuration_v1.go
  kubernetes/resource_kubernetes_validating_webhook_configuration_v1_test.go
  kubernetes/resourceidentity.go
Labels: size/XL
