Repository hashicorp/terraform-provider-kubernetes, pull requests merged in 2025-05, with the labels that each got.

#2729 Update CRT security scanner configuration
  .release/security-scan.hcl
Labels: size/XS, pr/no-changelog

#2730 v2.37.0
  CHANGELOG.md
Labels: size/XS, pr/no-changelog

#2731 Bump CRT release version
  version/VERSION
Labels: size/XS, pr/no-changelog

#2733 Satisfy provider protocol requirements for Terraform >= v1.21.1
  .changelog/2733.txt
  .github/workflows/check_examples.yaml
  go.mod
  go.sum
  manifest/provider/server.go
Labels: size/S

#2734 Prepare release v2.37.1
  CHANGELOG.md
  version/VERSION
Labels: size/XS, pr/no-changelog

#2737 Add resource identity to kubernetes_manifest
  .changelog/2737.txt
  manifest/provider/apply.go
  manifest/provider/import.go
  manifest/provider/read.go
  manifest/provider/resourceidentity.go
  manifest/provider/server.go
  manifest/test/acceptance/configmap_test.go
  manifest/test/helper/state/state_helper.go
  manifest/test/plugintest/working_dir.go
Labels: size/L
